Sugati/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>A_Total_Promotional_Credit_Memo__c</fullName>
        <label>Total Promotional Credit Memo</label>
        <summarizedField>Credit_Memo__c.CM_Total_Credit_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Credit_Memo__c.CM_Type__c</field>
            <operation>equals</operation>
            <value>Promotion</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Credit_Memo__c.CM_Is_Expired__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Credit_Memo__c.CM_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <fields>
        <fullName>CG_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Groups</relationshipLabel>
        <relationshipName>Client_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Booking_Currency__c</fullName>
        <label>Booking Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Days_to_Departure__c</fullName>
        <formula>IF(  AND(TEXT(StageName) &lt;&gt; &quot;Enquiry gone cold&quot;,O_Departure_Date__c &gt; DATEVALUE(Now())) , O_Departure_Date__c - DATEVALUE(Now()), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>IF( TEXT(StageName) &lt;&gt; &quot;Enquiry gone cold&quot; , O_Departure_Date__c - DATEVALUE(Now()), 0)</inlineHelpText>
        <label>Days to Departure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Outstanding__c</fullName>
        <formula>Amount - O_Total_Payment_Without_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Cost_Payment__c.object
<CustomObject>
    <fields>
        <fullName>SCP_Is_Agent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Agent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SCP_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Costs &amp; Payments</relationshipLabel>
        <relationshipName>Supplier_Cost_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCP_Outstanding_Amount__c</fullName>
        <formula>SCP_Total__c-SCP_Total_Payment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SCP_Supplier_Currency__c</fullName>
        <formula>TEXT(SCP_Exchange_Rate__r.ER_Base_Currency__c)</formula>
        <label>Supplier Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCP_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Costs &amp; Payments</relationshipLabel>
        <relationshipName>Supplier_Cost_payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCP_Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Supplier Cost &amp; Payment</label>
    <nameField>
        <displayFormat>SCP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs &amp; Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Payment__c.object
<CustomObject>
    <fields>
        <fullName>P_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>P_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Supplier_Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBP_Supplier_Cost_Currency_Value__c</fullName>
        <label>Supplier Cost Currency Value</label>
        <referenceTo>Supplier_Cost_Payment__c</referenceTo>
        <relationshipLabel>Supplier_Payments</relationshipLabel>
        <relationshipName>Supplier_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SB_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SP_Authorised_by__c</fullName>
        <label>Authorised by</label>
        <picklist>
            <picklistValues>
                <fullName>Gustav</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Swapna</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SP_Bank_Account__c</fullName>
        <label>Bank Account</label>
        <picklist>
            <picklistValues>
                <fullName>Account 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account 4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SP_Comment__c</fullName>
        <description>Comment put in for Steve</description>
        <inlineHelpText>Supplier Comment</inlineHelpText>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SP_Costing_ROE__c</fullName>
        <formula>SBP_Supplier_Cost_Currency_Value__r.SCP_Exchange_Rate__r.ER_Exchange_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Costing ROE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_Currency__c</fullName>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FJD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HKD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MYR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SP_Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SP_Exchange_Rate__c</fullName>
        <inlineHelpText>Payment RoE</inlineHelpText>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_FX_Gain_Loss__c</fullName>
        <formula>( P_Amount__c / SP_Costing_ROE__c) - (P_Amount__c / SP_Exchange_Rate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FX Gain/Loss</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_Inv_Date__c</fullName>
        <label>Inv Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SP_Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SP_Paid_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Paid By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Supplier_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SP_Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SP_Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Bank Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SP_Payment_RoE__c</fullName>
        <label>Payment RoE</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_Remittance_Comments__c</fullName>
        <label>Remittance Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SP_Remittance_Comments_office_copy__c</fullName>
        <label>Remittance Comments (office copy)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SP_Transferred_To_Accts__c</fullName>
        <label>Transferred To Accts</label>
        <type>Date</type>
    </fields>
    <label>Supplier Payment</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier_Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/SupplierPaymentController.cls
public without sharing class  SupplierPaymentController{
    public String oppRecord {get;set;}
    public Opportunity opp{get;set;}
    public String nameSpacePrefix{get;set;}
    public transient  String pickLists {get; set;}
    public String lstSupplierBookings{get; set;}
    
    public SupplierPaymentController(Apexpages.standardcontroller controller){
        oppRecord = '';
        try{
            ApexClass cs =[select NamespacePrefix from ApexClass where Name ='HolidayEnquiryController'];
            if(cs.NamespacePrefix != null){
                nameSpacePrefix = cs.NamespacePrefix+'__';
            }
            else{
                nameSpacePrefix = '';
            }
            opp = [SELECT id,Account.A_Total_Promotional_Credit_Memo__c, currencyISOCode,O_Days_to_Departure__c, Name, O_Booking_Currency__c, AccountId, Amount, O_Outstanding__c, O_Departure_Date__c,
                                (Select Id, Name from Client_Groups__r order by Name) from Opportunity where Id =: controller.getId()];
            
            List<Supplier_Cost_Payment__c> lstSBC = [Select Id,SCP_Outstanding_Amount__c,SCP_Supplier_Currency__c,CurrencyIsoCode, SCP_Supplier__r.Name, SCP_Total__c, 
                                                        SCP_Supplier__c from Supplier_Cost_Payment__c where SCP_Opportunity__c = :opp.Id order by SCP_Supplier__r.Name];
                                    
            lstSupplierBookings = JSON.serialize(lstSBC);
            oppRecord = JSON.serialize(opp);
            pickLists = JSON.serialize(Utility.describePickLists(Utility.getNameSpacePrefix()+'Supplier_Payment__c'));
        }
        Catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Error : '+e.getMessage());
            ApexPages.addmessage(myMsg);
        }
    }
    
    
    //Get all the client payments detail of this opportunity
    @RemoteAction
    public static String getSupplierPayments(String oppId){
        List<Supplier_Payment__c> lstSupplierPayments = [Select Id,SP_Bank_Account__c, SP_Note__c, SP_Transferred_To_Accts__c, P_Amount__c, SP_Authorised_by__c, SP_Comment__c, SP_Costing_ROE__c, 
                                                            SP_Currency__c, SP_Due_Date__c, SP_Exchange_Rate__c, SP_FX_Gain_Loss__c, P_Invoice__c, 
                                                            SP_Paid_By__c, SP_Payment_Date__c, SP_Payment_Method__c, SP_Payment_RoE__c, SB_Payment_Type__c
                                                            ,SBP_Supplier_Cost_Currency_Value__r.SCP_Supplier__r.Name, SBP_Supplier_Cost_Currency_Value__r.SCP_Is_Agent__c,SP_Inv_Date__c,SP_Remittance_Comments__c,SP_Remittance_Comments_office_copy__c  
                                                            from Supplier_Payment__c  where SBP_Supplier_Cost_Currency_Value__r.SCP_Opportunity__c = :oppId order by CreatedDate];    
            return JSON.serialize(lstSupplierPayments);       
    }
    
    //Get all supplier cost and payment
    @RemoteAction
    public static String getSupplierCostnPayment(String oppId){
        List<Supplier_Cost_Payment__c> lstSupplierCostPayment = [Select Id,SCP_Outstanding_Amount__c,SCP_Supplier_Currency__c,CurrencyIsoCode, SCP_Supplier__r.Name, SCP_Total__c, 
                                                        SCP_Supplier__c from Supplier_Cost_Payment__c where SCP_Opportunity__c = :oppId];    
        return JSON.serialize(lstSupplierCostPayment);     
    }
    
    
    //Save Supplier Payments
    @RemoteAction
    public static String saveSupplierPayments(String SPJSON, String oppId){
        try{
            Supplier_Payment__c selectedCP = (Supplier_Payment__c) JSON.deserialize(SPJSON, Supplier_Payment__c.class);
            upsert selectedCP;
            List<Supplier_Payment__c> lstSupplierPayments = [Select Id,SP_Bank_Account__c, SP_Note__c, SP_Transferred_To_Accts__c, P_Amount__c, SP_Authorised_by__c, SP_Comment__c, SP_Costing_ROE__c, 
                                                                SP_Currency__c, SP_Due_Date__c, SP_Exchange_Rate__c, SP_FX_Gain_Loss__c, P_Invoice__c, 
                                                                SP_Paid_By__c, SP_Payment_Date__c, SP_Payment_Method__c, SP_Payment_RoE__c, SB_Payment_Type__c
                                                                ,SBP_Supplier_Cost_Currency_Value__r.SCP_Supplier__r.Name, SBP_Supplier_Cost_Currency_Value__r.SCP_Is_Agent__c,SP_Inv_Date__c,SP_Remittance_Comments__c,SP_Remittance_Comments_office_copy__c 
                                                                from Supplier_Payment__c  where SBP_Supplier_Cost_Currency_Value__r.SCP_Opportunity__c = :oppId order by CreatedDate];    
            return JSON.serialize(lstSupplierPayments); 
        }catch(Exception e){System.assert(false, e.getMessage());return null;} 
        
    }
    
    //Save All Supplier Payments
    @RemoteAction
    public static String saveAllSupplierPayments(String SPJSON, String oppId){
        try{
            List<Supplier_Payment__c> selectedCP = (List<Supplier_Payment__c>) JSON.deserialize(SPJSON, List<Supplier_Payment__c>.class);
            insert selectedCP;
            List<Supplier_Payment__c> lstSupplierPayments = [Select Id,SP_Bank_Account__c, SP_Note__c, SP_Transferred_To_Accts__c, P_Amount__c, SP_Authorised_by__c, SP_Comment__c, SP_Costing_ROE__c, 
                                                                SP_Currency__c, SP_Due_Date__c, SP_Exchange_Rate__c, SP_FX_Gain_Loss__c, P_Invoice__c, 
                                                                SP_Paid_By__c, SP_Payment_Date__c, SP_Payment_Method__c, SP_Payment_RoE__c, SB_Payment_Type__c
                                                                ,SBP_Supplier_Cost_Currency_Value__r.SCP_Supplier__r.Name, SBP_Supplier_Cost_Currency_Value__r.SCP_Is_Agent__c 
                                                                from Supplier_Payment__c  where SBP_Supplier_Cost_Currency_Value__r.SCP_Opportunity__c = :oppId order by CreatedDate];    
            return JSON.serialize(lstSupplierPayments); 
        }catch(Exception e){System.assert(false, e.getMessage());return null;}   
    }

}