Sugati/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>A_Total_Compensation_Credit_Memo__c</fullName>
        <label>Total Compensation Credit Memo</label>
        <summarizedField>Credit_Memo__c.CM_Total_Credit_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Credit_Memo__c.CM_Type__c</field>
            <operation>equals</operation>
            <value>Compensation</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Credit_Memo__c.CM_Is_Expired__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Credit_Memo__c.CM_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>A_Total_Promotional_Credit_Memo__c</fullName>
        <label>Total Promotional Credit Memo</label>
        <summarizedField>Credit_Memo__c.CM_Total_Credit_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Credit_Memo__c.CM_Type__c</field>
            <operation>equals</operation>
            <value>Promotion</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Credit_Memo__c.CM_Is_Expired__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Credit_Memo__c.CM_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Credit_Memo__c</fullName>
        <label>Credit and Discount</label>
        <summarizedField>Credit_Memo__c.CM_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Credit_Memo__c.CM_Is_Expired__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Credit_Memo__c.CM_Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Pax__c</fullName>
        <formula>IF(O_Is_Group_Booking__c,IF(Adult_Old__c &gt; 0, Adult_Old__c, O_Adult__c) + IF( O_Child_Old__c  &gt; 0, O_Child_Old__c, O_Children__c) + IF(  O_Infant_Old__c   &gt; 0, O_Infant_Old__c, O_Infant__c)-3,IF(Adult_Old__c &gt; 0, Adult_Old__c, O_Adult__c) + IF( O_Child_Old__c  &gt; 0, O_Child_Old__c, O_Children__c) + IF(  O_Infant_Old__c   &gt; 0, O_Infant_Old__c, O_Infant__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Reference_Number__c</fullName>
        <label>Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/OpportunityDetailController.cls
public with sharing class OpportunityDetailController{
    
    
    public String OppId;
    public String logourl{get;set;}
    public OpportunityDetailController(){
        OppId = apexpages.currentpage().getParameters().get('id');
        if(oppId == '' || oppId == null){
            OppId = apexpages.currentpage().getParameters().get('HEoppId');    
        }
    }
    public Opportunity Opp{get;set;}
    public String nameSpacePrefix{get;set;}
    
    
    public Opportunity getOppD(){
        ApexClass cs =[select NamespacePrefix from ApexClass where Name =:'HolidayEnquiryController'];
        if(cs.NamespacePrefix != null){
            nameSpacePrefix = cs.NamespacePrefix+'__';
        }
        else{
            nameSpacePrefix = '';
        }
        if(OppId != '' && OppId != null){
            return  [select id,name,O_Reference_Number__c,Account.name,Account.Total_Credit_Memo__c,O_Departure_Date__c,O_Return_Date__c,
                    Account.A_Total_Compensation_Credit_Memo__c,Account.A_Total_Promotional_Credit_Memo__c,O_Pax__c from Opportunity where id =: OppId];
        }
        return null;
    }
    
    public void refreshComponent(){
    
    }
}