Sugati/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>A_Email__c</fullName>
        <inlineHelpText>Account Email is required</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>A_First_Name__c</fullName>
        <description>First name (Eg: Tim, Donna)</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>A_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>A_Postal_Code__c</fullName>
        <formula>BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>A_Salutation__c</fullName>
        <label>Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>Baron</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baroness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dame</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HRH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lady</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maj Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rabbi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rev</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sir</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The Hon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The RT Hon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viscount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viscountess</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Occupancy_Type__c</fullName>
        <label>Occupancy Type</label>
        <picklist>
            <picklistValues>
                <fullName>Adult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Holiday_Type__c.object
<CustomObject>
    <label>Holiday Type</label>
    <nameField>
        <label>Holiday Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>L_Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>L_Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Booking_Currency__c</fullName>
        <label>Booking Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Lead_Email_Address__c</fullName>
        <description>This is to be used with workflow only.</description>
        <label>Lead Email Address</label>
        <type>Email</type>
    </fields>
    
    
    <fields>
        <fullName>Pipeline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Pipeline</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Where_to_go__c.object
<CustomObject>
    <description>Places / Cities</description>
    <fields>
        <fullName>W_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Where to go</relationshipLabel>
        <relationshipName>Where_to_go</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Where to go</label>
    <nameField>
        <label>Where to go Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Where to go</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/ConvertLeadController.cls
public with sharing class ConvertLeadController {
    public Lead leadRec;
    public Boolean fromHE;
    
    //Constructor
    public ConvertLeadController(ApexPages.StandardController controller) {
        leadRec = [Select id, Name, createdDate, Salutation,CurrencyIsoCode, HasOptedOutOfEmail, Message__c, FirstName, LastName, Postalcode, L_Division__c, L_Location__c, Email, LeadSource, Phone, Description, IsConverted from Lead WHERE id =: controller.getId()];
    }
    
    //Method that will convert lead
    public PageReference initConversion(){
        SavePoint sp = Database.setSavePoint();
        try{
            LeadStatus convertStatus = [Select MasterLabel from LeadStatus  where IsConverted = true limit 1];
            Database.LeadConvert lc = new Database.LeadConvert();
            Database.LeadConvertResult lcResult;
            Opportunity Opp;
            Account accRec;
            Contact conRec;
            //Create a savepoint to rollback the changes in case of any exception
            
            String divisionName = '';
            if (!leadRec.isConverted) {
                divisionName = leadRec.L_Division__c;
                lc = new Database.LeadConvert();
                String oppName = leadRec.Name;
                lc.setLeadId(leadRec.Id);
                lc.setOpportunityName(oppName);
                lc.setConvertedStatus(convertStatus.MasterLabel);
                boolean matchedRecordFound = false;
                boolean matchedRecordContcat = false;
                //Check for matched accounts
                
                String lName = '%'+leadRec.Name+'%';
                if(leadRec.Email != null && leadRec.Email != ''){
                    for(Account acc : [SELECT id FROM Account WHERE Name like :lName AND (A_Email__c = :leadRec.Email  OR Phone = :leadRec.Phone OR A_Postal_Code__c = :leadRec.PostalCode) order by lastModifiedDate  limit 1]){
                        lc.setAccountId(acc.id);
                        accRec = acc;
                    }
                }
                if(accRec != null && accRec.Id != null){
                    for(Contact con : [Select Id from Contact where AccountId = :accRec.Id And Name like :lName AND (Email = :leadRec.Email OR Phone = :leadRec.Phone OR MailingPostalCode = :leadRec.PostalCode) order by lastModifiedDate  limit 1]){
                        lc.setContactId(con.id);
                    }
                }
                List<Holiday_Type__c> lstHolidayType = [Select Id from Holiday_Type__c where Name = 'Generic' limit 1];
                lcResult = Database.convertLead(lc);
                List<Travelling_Country__c> travellingCountries = new List<Travelling_Country__c>();  
                Date d = Date.today();         
                /*** Create an opportunity *****/
                if(lcResult != null){
                    Opp = new Opportunity();
                    Opp.Id = lcResult.getOpportunityId();
                    Map<String,Id> recordTypeMap = new Map<String,Id>();
                    oppName = '';
                    if(leadRec.FirstName != null)
                        oppName = leadRec.FirstName+' ';
                    if(leadRec.LastName != null)
                        oppName += leadRec.LastName;
                    Opp.name = 'New Enquiry';
                    Opp.StageName = 'Enquiry';
                    Opp.CloseDate = Date.newInstance(d.year(), d.month(), d.day());
                    if(leadRec.Email != null)
                        Opp.O_Lead_Email_Address__c = leadRec.Email;
                    if(leadRec.LeadSource != null)
                        Opp.LeadSource = leadRec.LeadSource;
                    if(leadRec.Description != null)
                        Opp.Description = leadRec.Description;
                    opp.closeDate = leadRec.createdDate.date();
                    Opp.O_Booking_Currency__c = leadRec.CurrencyIsoCode; 
                    Opp.CurrencyIsoCode = leadRec.CurrencyIsoCode; 
                    if(lstHolidayType.size() > 0){
                        Opp.O_Holiday_Type__c = lstHolidayType[0].Id;
                    }
                    Opp.Pipeline__c = true;
                    Opp.Type = 'Individual';
                    if(leadRec.Message__c != null)
                        opp.Description = leadRec.Message__c;
                    
                    /** Contact **/
                    List<Account> lstAccount = [Select Id,BillingStreet,BillingCity,BillingState,BillingPostalcode,BillingCountry from Account where Id = :lc.getAccountId() limit 1];
                    Contact cont = new Contact();
                    cont.Id = lcResult.getContactId();
                    cont.HasOptedOutOfEmail = leadRec.HasOptedOutOfEmail;
                    cont.Occupancy_Type__c = 'Adult';
                    if(lstAccount.size() > 0 ){
                        cont.mailingStreet = lstAccount[0].BillingStreet;
                        cont.MailingCity = lstAccount[0].BillingCity;
                        cont.MailingState = lstAccount[0].BillingState;
                        cont.MailingPostalcode = lstAccount[0].BillingPostalcode;
                        cont.MailingCountry = lstAccount[0].BillingCountry;
                    }
                    cont.Description = '';
                    update cont;
                    
                    
                    if(accRec != null){
                        Opp.AccountId = accRec.Id;
                    }
                    else{
                        Account Acc = new Account();
                        acc.Id = lcResult.getAccountId();
                        String Name = '';
                        if(leadRec.Salutation != null){
                            name = leadRec.Salutation+' ';
                            Acc.A_Salutation__c = leadRec.Salutation;
                        }
                        if(leadRec.FirstName != null){
                            name += leadRec.FirstName+' ';
                            Acc.A_First_Name__c = leadRec.FirstName;
                        }
                        if(leadRec.LastName != null){
                            name += leadRec.LastName;
                            Acc.A_Last_Name__c = leadRec.LastName;
                        }
                        Acc.name = Name;
                        if(Opp.O_Lead_Email_Address__c != null)
                            Acc.A_Email__c = Opp.O_Lead_Email_Address__c;
                        if(leadRec.PostalCode != null){
                            Acc.BillingPostalCode = leadRec.PostalCode;
                        }
                        upsert Acc;
                    }
                    upsert opp;
                }
            }
            
            /** Create Travelling Country for each location  **/
            if(lcResult != null && leadRec.L_Location__c != null){
                List<String> countries = new List<String>();
                Map<String, Travelling_Country__c> mapTravellingCountries = new Map<String,Travelling_Country__c>();
                Map<String, Id> mapCountries = new Map<String, Id>();
                for(Country__c country : [Select id, name from Country__c where name != null]){
                    mapCountries.put(country.name.touppercase(), country.id);    
                }
                Map<String, String> wheretogotoCountrytMap = new Map<String,String>();
                for(Where_to_go__c wheretogo : [select id,name,W_Country__c,W_Country__r.Name from Where_to_go__c]){
                    wheretogotoCountrytMap.put(wheretogo.Name.touppercase(),wheretogo.W_Country__r.Name);
                }
                if(leadRec.L_Location__c != null && leadRec.L_Location__c.contains(';')){
                    for(String country : leadRec.L_Location__c.split(';')){
                        if(country.contains('|')){
                            countries.add(country.trim().split('\\|')[0]);
                        }
                        else{
                            countries.add(country.trim());
                        }
                    }
                } 
                else if(leadRec.L_Location__c != null && leadRec.L_Location__c.contains(',')){
                    for(String country : leadRec.L_Location__c.split(',')){
                        if(country.contains('|')){
                            countries.add(country.trim().split('\\|')[0]);
                        }
                        else{
                            countries.add(country.trim());
                        }
                    }
                }   
                else if(leadRec.L_Location__c != null){  
                    if(leadRec.L_Location__c.contains('|')){
                        countries.add(leadRec.L_Location__c.trim().split('\\|')[0]);
                    }
                    else{
                        countries.add(leadRec.L_Location__c.trim());
                    } 
                }  
                for(String countryName : countries){
                    if(mapCountries.containsKey(countryName.trim().touppercase())){
                        mapTravellingCountries.put(countryName.trim().touppercase(), new Travelling_Country__c(TC_Country__c = mapCountries.get(countryName.trim().touppercase()), TC_Opportunity__c = opp.id));    
                    }    
                    else if(wheretogotoCountrytMap.containsKey(countryname.touppercase())){
                        String countryNameTemp = wheretogotoCountrytMap.get(countryname.touppercase());
                        if(mapCountries.containsKey(countryNameTemp.trim().touppercase()))
                            mapTravellingCountries.put(countryName.trim().touppercase(), new Travelling_Country__c(TC_Country__c = mapCountries.get(countryNameTemp.trim().touppercase()), TC_Opportunity__c = opp.id));    

                    }
                }
                insert mapTravellingCountries.values();
            }
            if(ApexPages.currentPage().getParameters().get('ret') == 'HE'){
                PageReference pgRef = Page.HolidayEnquiry;
                pgRef.getParameters().put('Id',opp.Id);
                return pgRef;
            } 
            if(opp != null){
                PageReference pgRef = new PageReference('/'+opp.id);    
                return pgRef;
            }
            else{
                return null;    
            }
        }
        catch(Exception e){
            //Rollback the changes
            Database.rollback(sp);
            System.assert(false,e.getMessage() + e.getStackTraceString());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, e.getMessage() + '  ' + e.getStackTraceString()));
            PageReference pgRef = new PageReference('/'+leadRec.id);    
            return pgRef;
        }
    }
}