Sugati/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>A_First_Name__c</fullName>
        <description>First name (Eg: Tim, Donna)</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>A_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Client_Payment__c.object
<CustomObject>
    <fields>
        <fullName>CP_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Payments</relationshipLabel>
        <relationshipName>Client_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Payment</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Client Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/CSS_Styler__c.object
<CustomObject>
    <fields>
        <fullName>Email_Font_Color__c</fullName>
        <label>Email Font Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Font_Family__c</fullName>
        <label>Email Font-Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Font_Size__c</fullName>
        <label>Email Font-Size</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Font_Style__c</fullName>
        <label>Email Font Style</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS Styler</label>
    <nameField>
        <label>CSS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Stylers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Email_Template__c.object
<CustomObject>
    <description>A list of email templates</description>
    <fields>
        <fullName>ET_Page_Section__c</fullName>
        <label>Page/Section Name</label>
        <picklist>
            <picklistValues>
                <fullName>Acknowledgement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday Suggestions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SupplierPayments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Int Flight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuck-Tuck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dom Flights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excursion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Light Aircraft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meet &amp; Greet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Jet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Road Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Speed Boat Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Transfer with Excursion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sea Plane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Road Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Speed Boat Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Transfer with Excursion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP Meet And Greet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cruise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SupplierPaymentsNew</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ET_Template_Name__c</fullName>
        <label>Template Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ET_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Holiday_Suggestion_Email_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email Template</label>
    <nameField>
        <displayFormat>HSET-{0000000000}</displayFormat>
        <label>Holiday Suggestion Email Template ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Templates</pluralLabel>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>Is this for Email Templates?</description>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Error_Message__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>AckPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClientPayments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CopyOpportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CoverPageSelector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FileUpload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FinalDoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HolidayEnquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HolidaySuggestion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ItineraryBuilder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ItineraryCategory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ManageTasks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDFSetting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SendEmail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SupplierPayments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Error Message</label>
    <nameField>
        <label>Error Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Lead_Passenger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Passenger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Follow_Up_Time__c</fullName>
        <label>Follow Up Time</label>
        <type>DateTime</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/AckComponentTest.cls
@isTest
public with sharing Class AckComponentTest{
    
    @testSetup
    static void setupData(){
        CSS_Styler__c css = new CSS_Styler__c(Name = 'TestPage', Email__c = true, Email_Font_Family__c = 'test', Email_Font_Size__c  = '10', Email_Font_Style__c = 'test', Email_Font_Color__c= 'test',Is_Active__c=true);
        insert css;
        System.assertNotEquals(css.Id, null);     
        css = new CSS_Styler__c(Name = 'SendEmail', Email__c = true, Email_Font_Family__c = 'test', Email_Font_Size__c  = '10', Email_Font_Style__c = 'test', Email_Font_Color__c= 'test',Is_Active__c=true);
        insert css;
        TestServices.createSiteCustomSetting();
        
    }
    
    @isTest
    public static void testGetErrorMessages(){
        Error_Message__c errmsg = new Error_Message__c(
            name = 'Test Error', 
            page_name__c = 'Test Page', 
            error_message__c = 'Test Error Message');
        insert errmsg;
        
        Map<String,String> mapErrorMessage = new Map<String,String>();
        mapErrorMessage.put('Test Error', 'Test Error Message');
        
        System.assertEquals(mapErrorMessage, AckComponent.getErrorMessages('Test Page'));
    }
    
    @isTest
    public static void testGetContact(){
    
        // BEGIN Setup
        List<Account> acctList = new List<Account> {
            new Account (Name = 'Test Account')
        };
        insert acctList;
        
        List<Opportunity> oppList = new List<Opportunity> {
            new Opportunity(
                Name      = 'Opportunity 1',
                AccountID = acctList[0].id,
                StageName = 'Test',
                CloseDate = Date.today()
            )
        };
        insert oppList;
        
        List<Contact> contactList = new List<Contact> {
            new Contact(
                AccountID = acctList[0].id,
                FirstName = 'John',
                LastName  = 'Smith',
                Email     = 'john@domain.com'
            )
        };
        insert contactList;
        // END Setup
        
        /**
         * Test with oppId 
         */
        System.assertEquals('john@domain.com', AckComponent.getContact(oppList[0].id).get(0).value);
        System.assertEquals('John Smith (john@domain.com)', AckComponent.getContact(oppList[0].id).get(0).label);
        
        /**
         * Test without oppId 
         */
        System.assertEquals(new List<AckComponent.pickListValue>(), AckComponent.getContact(''));
        System.assertEquals(new List<AckComponent.pickListValue>(), AckComponent.getContact(null));   
    }
    
    @isTest
    public static void testGetTemplate(){
    
        // BEGIN Setup
        
        System.runAs(new User(Id = UserInfo.getUserId())){ 
            Test.startTest(); 
            
            EmailTemplate emailTemp = new EmailTemplate(
                DeveloperName = 'test',
                TemplateType  = 'Custom',
                FolderId      = UserInfo.getUserId(), 
                Name          = 'Template Name',
                Body          = '',
                HtmlValue     = '<html></html>',
                isActive      = true
            );
            insert emailTemp;
            System.debug(emailTemp.id);
            
            Test.stopTest(); 
        }   
         
        List<Account> acctList = new List<Account> {
            new Account (
                Name            = 'Test Account',
                A_First_Name__c = 'John',
                A_Last_Name__c  = 'Smith'
            )
        };
        insert acctList;
        
        List<Opportunity> oppList = new List<Opportunity> {
            new Opportunity(
                Name      = 'Opportunity 1',
                AccountID = acctList[0].id,
                StageName = 'Test',
                CloseDate = Date.today(),
                O_Follow_Up_Time__c = System.today()
            ),
            new Opportunity(
                Name      = 'Opportunity 2',
                AccountID = acctList[0].id,
                StageName = 'Test',
                CloseDate = Date.today(),
                 O_Follow_Up_Time__c = System.today()
            )
        };
        insert oppList;
        
        List<Contact> contactList = new List<Contact> {
            new Contact(
                AccountID = acctList[0].id,
                FirstName = 'John',
                LastName  = 'Smith',
                Email     = 'john@domain.com'
            ),
            new Contact(
                AccountID = acctList[0].id,
                FirstName = 'Mary',
                LastName  = 'Brown',
                Email     = 'mary@domain.com'
            )
        };
        insert contactList;
        
        List<Client_Payment__c> clientPayments = new List<Client_Payment__c>(); 
        clientPayments.add(new Client_Payment__c (CP_Opportunity__c = oppList[0].Id));
        insert clientPayments;
        
        List<Group_Member__c> gmList = new List<Group_Member__c> {
            new Group_Member__c(
                GM_Contact__c        = contactList[0].Id,
                GM_Opportunity__c    = oppList[0].Id,
                GM_Lead_Passenger__c = true
            ),
            new Group_Member__c(
                GM_Contact__c        = contactList[1].Id,
                GM_Opportunity__c    = oppList[1].Id,
                GM_Lead_Passenger__c = true
            )
        };
        insert gmList;
        
        Email_Template__c et = new Email_Template__c(
            ET_Page_Section__c  = 'Page Name',
            ET_Template_Name__c = 'Template Name',
            ET_User__c          = UserInfo.getUserId()
        );
        insert et;
        
        
        // END Setup
        
        /**
         * Test with oppId 
         */
        System.System.assert(AckComponent.getTemplate(oppList[0].id, 'Page Name', 'TestPage') != null);
        System.System.assert(AckComponent.getTemplate(oppList[1].Id, 'Page Name', 'TestPage') != null);
        
        /**
         * Test without oppId 
         */
        //System.assert(AckComponent.getTemplate(null, 'Page Name') == null);
        System.assert(AckComponent.getTemplate(oppList[0].id, '', '') == null); 
        
        AckComponent.EmailWrapper ew = new AckComponent.EmailWrapper('Email Content');
        ew.selectedTo  = new List<AckComponent.pickListValue>{new AckComponent.pickListValue('to@domain.com', 'To')};
        ew.selectedCc  = new List<AckComponent.pickListValue>{new AckComponent.pickListValue('cc@domain.com', 'CC')};
        ew.selectedBcc = new List<AckComponent.pickListValue>{new AckComponent.pickListValue('bcc@domain.com', 'BCC')};
        Attachment att = new Attachment(body=Blob.valueOf('test'), name='test', parentId=oppList[0].Id);
        insert att;
        
        System.assertEquals('Sucess', AckComponent.sendEmail(ew, 'Email Body', oppList[0].Id, '', '', new List<String>{att.Id})); 
        System.assertEquals('Sucess', AckComponent.sendEmail(ew, 'Email Body', oppList[0].Id, 'Acknowledgement', 'TestPage', new List<String>{att.Id})); 
        System.assertEquals('Sucess', AckComponent.sendEmail(ew, 'Email Body', oppList[0].Id, 'Holiday Suggestions', 'TestPage', new List<String>{att.Id}));     
        
        System.System.assert(AckComponent.getSelectedTemplate(oppList[0].id, 'Page Name', et.Id, null, null, null) != null);
        System.System.assert(AckComponent.getSelectedTemplate(oppList[0].id, 'Page Name', et.Id, null, oppList[0].id, new List<String>{oppList[0].Id}) != null);
        
        System.System.assert(AckComponent.getFolderReports('Page Name', oppList[0].id) != null);
    }
    
    @isTest
    public static void testSaveBroucheRequestContact(){
        // BEGIN Setup
        List<Account> acctList = new List<Account> {
            new Account (Name = 'Test Account')
        };
        insert acctList;
        
        List<Opportunity> oppList = new List<Opportunity> {
            new Opportunity(
                Name  = 'Opportunity 1',
                AccountID = acctList[0].id,
                StageName = 'Test',
                O_Departure_Date__c = Date.today(),
                CloseDate = Date.today()
            ),
            
            new Opportunity(
                Name  = 'Opportunity 1',
                AccountID = acctList[0].id,
                StageName = 'Test',
                O_Departure_Date__c = Date.today(),
                CloseDate = Date.today()
            )
        };
        insert oppList;
        
        List<Contact> contactList = new List<Contact> {
            new Contact(
                AccountID = acctList[0].id,
                FirstName = 'John',
                LastName  = 'Smith',
                Email     = 'john@domain.com'
            )
        };
        insert contactList;
       
        // END Setup
        // Set the pageRef to Quote 1
        PageReference pageRef = Page.HolidayEnquiry;
        
        // Set the current page
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', oppList[0].Id);
        AckComponent ack = new AckComponent();
        ack.emailAddresses = 'test@test.com';
        ack.emailW = 'test';
        ack.emailTemp = new EmailTemplate();
        System.assertEquals(1, AckComponent.getOppRecords(oppList[0].Id).size());
        System.assertEquals(true, AckComponent.saveBroucheRequestContact(JSON.serialize(contactList[0])));   
    }
}