Sugati/src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>WH_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>What_to_do</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>What to do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <fields>
        <fullName>C_Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Adult__c</fullName>
        <inlineHelpText>Total no of adults in a given family.</inlineHelpText>
        <label>Adult</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Adult</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Choose an agent if this is an agent booking.</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Booking_Currency__c</fullName>
        <label>Booking Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Children__c</fullName>
        <label>Children</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Child</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Destination_Map_Image_ID__c</fullName>
        <label>Destination Map Image ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Infant__c</fullName>
        <label>Infant</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Infant</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Map_Type__c</fullName>
        <label>Map Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Outstanding__c</fullName>
        <formula>Amount - O_Total_Payment_Without_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <fields>
        <fullName>S_Country__c</fullName>
        <formula>IF(ISBLANK(S_What_to_do__c) ,  S_Where_to_go__r.W_Country__r.Name ,  S_What_to_do__r.WH_Country__r.Name )</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tourist Board</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>S_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <recordTypes>
        <fullName>Accommodation</fullName>
        <active>true</active>
        <label>Accommodation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SB_Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SB_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SB_What_to_do__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>What to do</label>
        <referenceTo>Activity__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SB_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <recordTypes>
        <fullName>Accommodation</fullName>
        <active>true</active>
        <description>Accommodation</description>
        <label>Accommodation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>TC_Country__r.Name</formula>
        <label>Country Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TC_Accommodation_Region__c</fullName>
        <label>Accommodation/Region</label>
        <picklist>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodation</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_DestinationMap_Image_ID__c</fullName>
        <label>DestinationMap Image ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Where_to_go__c.object
<CustomObject>
    <description>Places / Cities</description>
    <fields>
        <fullName>W_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Where to go</relationshipLabel>
        <relationshipName>Where_to_go</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Where to go</label>
    <nameField>
        <label>Where to go Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Where to go</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/DestinationMapController.cls
/******************************************************
*  Controller class for Destination Map Page
*  Author - Naval Sharma
*  Date - 12/12/2015
*******************************************************/

public with sharing class DestinationMapController{

    public DestinationMapController(ApexPages.StandardController controller) {
        String oppId = controller.getId();
        if(oppId != null){
            OppRec = [select id, Name,Account.Name,O_Agent__r.id,O_Agent__r.Name, O_Departure_Date__c, O_Return_Date__c,Owner.Name,Owner.Username,
                           O_Adult__c,O_Children__c,O_Infant__c,O_Map_Type__c,O_Holiday_Type__c,Amount,O_Outstanding__c,O_Destination_Map_Image_ID__c,O_Booking_Currency__c,
                           (Select Id, name, TC_Country__r.Name,TC_DestinationMap_Image_ID__c,TC_Accommodation_Region__c from Travelling_Countries__r)
                           from Opportunity  where Id=:oppId];
            strForSettingPage = JSON.serialize(getMapTravellingCountry());
        }
    }

    public String oppId {get; set;}
    public Opportunity OppRec {get; set;}
    public String Countrieslst {get; set;}
    public String CountryListAcc {get; set;}
    public Map<String,Set<String>> mapCountryToAccom {get; set;} 
    public Map<String, Set<String>>  MapCountryToWTGList {get; set;} 
    public String strForSettingPage{get; set;}
    public String strmapCountryToAccom{get; set;}
    public String strMapCountryToWTGList{get; set;}
    public DestinationMapController(){}
    
    public Map<String,Travelling_Country__c> getMapTravellingCountry(){
        Map<String,Travelling_Country__c> mapTC = new Map<String,Travelling_Country__c>();
        try{
            MapCountryToWTGList = new Map<String, Set<String>>();
            mapCountryToAccom = new Map<String,Set<String>>();
            Countrieslst = '';
            CountryListAcc = '';
            List<String> lstCountries = new List<String>();
            for(Travelling_Country__c tc : [SELECT Name, TC_Country__c, TC_DestinationMap_Image_ID__c, TC_Accommodation_Region__c, 
                                           TC_Country__r.name, TC_Country__r.C_Notes__c FROM Travelling_Country__c WHERE 
                                           TC_Opportunity__r.Id= :oppRec.Id  ORDER BY Country_Name__c]){
                mapTC.put(tc.TC_Country__r.Name, tc);    
            }
            for(Supplier_Booking__c sb : [SELECT id, SB_What_to_do__r.WH_Country__c, SB_Supplier__c, SB_Supplier__r.Name, SB_Supplier__r.S_Type__c, SB_Supplier__r.S_Country__c, SB_Supplier__r.S_Where_to_go__r.Name, SB_Supplier__r.S_Where_to_go__r.W_Country__c, SB_Where_to_go__c,SB_Where_to_go__r.W_Country__c,SB_Where_to_go__r.W_Country__r.name,SB_Where_to_go__r.name FROM
                                          Supplier_Booking__c WHERE SB_Opportunity__c = :OppRec.id
                                          ORDER BY SB_Order__c]){
                  /** List of selected where to go for travelling country*/
                  if((sb.SB_Where_to_go__r.W_Country__r.name != null && sb.SB_Where_to_go__r.W_Country__r.name != '') && (sb.SB_Where_to_go__r.name != null && sb.SB_Where_to_go__r.name != '')){
                      if(!MapCountryToWTGList.containsKey(sb.SB_Where_to_go__r.W_Country__r.name)){
                          MapCountryToWTGList.put(sb.SB_Where_to_go__r.W_Country__r.name,new Set<String>());
                      }
                      MapCountryToWTGList.get(sb.SB_Where_to_go__r.W_Country__r.name).add(sb.SB_Where_to_go__r.name+ '##' + sb.SB_Where_to_go__r.W_Country__r.Name);
                      Countrieslst += sb.SB_Where_to_go__r.W_Country__r.name+'  ';
                  }
                   /** List of selected accommodation for travelling country*/
                  if((sb.SB_Supplier__c != null && sb.SB_Supplier__r.name != '') && (sb.SB_Supplier__r.S_Country__c != null && sb.SB_Supplier__r.S_Type__c == 'Hotel')){
                      if(!mapCountryToAccom.containsKey(sb.SB_Supplier__r.S_Country__c)){
                          mapCountryToAccom.put(sb.SB_Supplier__r.S_Country__c, new Set<String>());
                      }
                      mapCountryToAccom.get(sb.SB_Supplier__r.S_Country__c).add(sb.SB_Supplier__r.name+ '##' + sb.SB_Supplier__r.S_Where_to_go__r.Name);
                      CountryListAcc += sb.SB_Supplier__r.S_Country__c +'  ';
                  }
             }
             strmapCountryToAccom = JSON.serialize(mapCountryToAccom);
             strMapCountryToWTGList = JSON.serialize(MapCountryToWTGList);
             return mapTC;
         }
         catch(Exception e){
             return mapTC;
         }
    }
    
    public Map<Integer,String> getASCIIMap(){
        Map<Integer,String> ASCIIMap = new Map<Integer,String>(); 
        ASCIIMap.put(65,'A');
        ASCIIMap.put(66,'B');
        ASCIIMap.put(67,'C');
        ASCIIMap.put(68,'D');
        ASCIIMap.put(69,'E');
        ASCIIMap.put(70,'F');
        ASCIIMap.put(71,'G');
        ASCIIMap.put(72,'H');
        ASCIIMap.put(73,'I');
        ASCIIMap.put(74,'J');
        ASCIIMap.put(75,'K');
        ASCIIMap.put(76,'L');
        ASCIIMap.put(77,'M');
        ASCIIMap.put(78,'N');
        ASCIIMap.put(79,'O');
        ASCIIMap.put(80,'P');
        ASCIIMap.put(81,'Q');
        ASCIIMap.put(82,'R');
        ASCIIMap.put(83,'S');
        ASCIIMap.put(84,'T');
        ASCIIMap.put(85,'U');
        ASCIIMap.put(86,'V');
        ASCIIMap.put(87,'W');
        ASCIIMap.put(88,'X');
        ASCIIMap.put(89,'Y');
        ASCIIMap.put(90,'AA');
        ASCIIMap.put(91,'AB');
        ASCIIMap.put(92,'AC');
        ASCIIMap.put(93,'AD');
        ASCIIMap.put(94,'AE');
        ASCIIMap.put(95,'AF');
        ASCIIMap.put(96,'AG');
        ASCIIMap.put(97,'AH');
        ASCIIMap.put(98,'AI');
        ASCIIMap.put(99,'AJ');
        return ASCIIMap;
    }
}