Sugati/src/objects/Activity__c.object
<CustomObject>
    <fields>
        <fullName>WH_Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WH_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>What_to_do</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WH_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipName>What_to_do</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <label>What to do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <fields>
        <fullName>C_Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <fields>
        <fullName>S_Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S_Country__c</fullName>
        <formula>IF(ISBLANK(S_What_to_do__c) ,  S_Where_to_go__r.W_Country__r.Name ,  S_What_to_do__r.WH_Country__r.Name )</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tourist Board</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>S_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <recordTypes>
        <fullName>Accommodation</fullName>
        <active>true</active>
        <label>Accommodation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Where_to_go__c.object
<CustomObject>
    <description>Places / Cities</description>
    <fields>
        <fullName>W_Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>W_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Where to go</relationshipLabel>
        <relationshipName>Where_to_go</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>W_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Where to go is within another place.</inlineHelpText>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipLabel>Where to go</relationshipLabel>
        <relationshipName>Where_to_go</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Where to go</label>
    <nameField>
        <label>Where to go Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Where to go</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/ContextSearchController.cls
public class ContextSearchController{
    public String json {get;set;}
     
    public void doSearch() {       
      try { 
      String searchFor = Apexpages.currentpage().getParameters().get('q');     
      String likeclause = '%'+searchfor+'%';
      String accom = 'Accommodation' ;
      String hot = 'Hotel' ;
     
      String wherequery = 'select id,name,W_Country__r.name,W_Where_to_go__r.name from Where_to_go__c where  W_Archive__c = false and ((name!=null AND W_Country__r.name != null) and (name like: likeclause OR W_Where_to_go__r.name like : likeclause )) ';
      String WhatQuery = 'select id,name,WH_Country__r.name,WH_Where_to_go__r.name from Activity__c where  WH_Archive__c = false and ((name!=null AND WH_Country__r.name != null) and (name like: likeclause OR WH_Where_to_go__r.name like : likeclause  ))  ';
      
      String SupplierQuery = 'Select id,Name,S_Country__c,S_Where_to_go__r.name from Supplier__c where S_Archive__c = false and (( S_Type__c =  \''+accom+'\' OR S_Type__c = \''+hot+'\' ) AND ( Name!=null AND S_Country__c!= null  ) and (Name like: likeclause  OR S_Where_to_go__r.name like : likeclause   ))  ';
      String CountryQuery = 'Select id,name from Country__c where C_Archive__c = false and ( name != null AND  name like: likeclause) ' ; 
                                                                                                       
      List<Where_to_go__c> wheretogo= Database.query(wherequery);
      integer i = 0;
      json = '[';
      for (Where_to_go__c wtg: wheretogo) {
          if (i ==0) {
              json += '{"value": "'+wtg.id+'", "name": "'+wtg.name+'", "Country": "'+wtg.W_Country__r.name+'" ,"WhereToGo": "'+ +'" ,"type":"WhereToGo"}';
              i ++;
          }
          else {
              json += ','+ '{"value": "'+wtg.id+'", "name": "'+wtg.name+'","Country": "'+wtg.W_Country__r.name+'" , "WhereToGo": "'+ +'" , "type":"WhereToGo"}';
          }
      }
      
      List<Country__c> countr = Database.query(CountryQuery);
      for (Country__c coun: countr) {
          if (i ==0) {
              json += '{"value": "'+coun.id+'", "name": "'+coun.name+'","Country": "'+ +'" ,"WhereToGo": "'+ +'" ,"type":"Country"}';
              i ++;
          }
          else {
              json += ','+ '{"value": "'+coun.id+'", "name": "'+coun.name+'","Country": "'+ +'" ,"WhereToGo": "'+ +'" ,"type":"Country"}';
          }
      }
      
      
      
      List<Activity__c> whattodo = Database.query(Whatquery);
      for (Activity__c wtd: whattodo ) {
          if (i ==0) {
              json += '{"value": "'+wtd.id+'", "name": "'+wtd.name+'","Country": "'+wtd.WH_Country__r.name+'" ,"WhereToGo": "'+wtd.WH_Where_to_go__r.name+'" , "type":"WhatToDo"}';
              i ++;
          }
          else {
              json += ','+ '{"value": "'+wtd.id+'", "name": "'+wtd.name+'","Country": "'+wtd.WH_Country__r.name+'" ,"WhereToGo": "'+wtd.WH_Where_to_go__r.name+'" , "type":"WhatToDo"}';
          }
      }
      
      List<Supplier__c> supplier = Database.query(SupplierQuery);
      for (Supplier__c supp: supplier ) {
          if (i ==0) {
              json += '{"value": "'+supp.id+'", "name": "'+supp.Name+'","Country": "'+supp.S_Country__c+'" ,"WhereToGo": "'+supp.S_Where_to_go__r.name+'",  "type":"WhereToStay"}';
              i ++;
          }
          else {
              json += ','+ '{"value": "'+supp.id+'", "name": "'+supp.Name+'","Country": "'+supp.S_Country__c+'" ,"WhereToGo": "'+supp.S_Where_to_go__r.name+'", "type":"WhereToStay"}';
          }
      }
      
                
      json += ']';
      
      } 
      catch(Exception e) {
          throw e;
      }     
    }
   
    // Returns the JSON result string
    public String getResult() {
        return json;
    }
    
    
     
}