Sugati/src/objects/Airport__c.object
<CustomObject>
    <description>A list of Airports.</description>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Airport_Terminal__c.object
<CustomObject>
    <fields>
        <fullName>AT_Airport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Airport</label>
        <referenceTo>Airport__c</referenceTo>
        <relationshipName>Airport_Terminals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AT_Carrier_Name__c</fullName>
        <label>Carrier Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AT_Class__c</fullName>
        <label>Class</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Airport Terminal &amp; Class</label>
    <nameField>
        <label>Terminal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Terminals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Email_Template__c.object
<CustomObject>
    <description>A list of email templates</description>
    <fields>
        <fullName>ET_Email_Closing__c</fullName>
        <label>Email Closing</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ET_Email_Intro__c</fullName>
        <label>Email Intro</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ET_Page_Section__c</fullName>
        <label>Page/Section Name</label>
        <picklist>
            <picklistValues>
                <fullName>Acknowledgement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday Suggestions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SupplierPayments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Int Flight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuck-Tuck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dom Flights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excursion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ferry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Light Aircraft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meet &amp; Greet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Jet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Road Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Speed Boat Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Transfer with Excursion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sea Plane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Road Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Speed Boat Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Transfer with Excursion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP Meet And Greet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cruise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SupplierPaymentsNew</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ET_Template_Name__c</fullName>
        <label>Template Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Email Template</label>
    <nameField>
        <displayFormat>HSET-{0000000000}</displayFormat>
        <label>Holiday Suggestion Email Template ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Client_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Group</label>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GM_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GM_Lead_Passenger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Passenger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GM_Salutation__c</fullName>
        <label>Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>Mr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Room_Type__c.object
<CustomObject>
    <description>A list of room types for each accommodation option.</description>
    <fields>
        <fullName>RT_Field_Name__c</fullName>
        <label>Field Name</label>
        <picklist>
            <picklistValues>
                <fullName>Meal Basis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Occupancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Room Type</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RT_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RT_Supplier__c</fullName>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Room Types</relationshipLabel>
        <relationshipName>Room_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Room Type</label>
    <nameField>
        <displayFormat>RT-{0000000000}</displayFormat>
        <label>Room Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Room Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <recordTypes>
        <fullName>Description</fullName>
        <active>true</active>
        <label>Description</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Cost__c.object
<CustomObject>
    <description>Supplier Cost</description>
    <label>Supplier Cost</label>
    <nameField>
        <displayFormat>SBC-{0000000000}</displayFormat>
        <label>Supplier Cost ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Where_to_go__c.object
<CustomObject>
    <description>Places / Cities</description>
    <label>Where to go</label>
    <nameField>
        <label>Where to go Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Where to go</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/ItineraryBuilderControllerTest.cls
/**
*  @Author         :   Naval Sharma
*  @Date           :   1-Mar-2016
*  @Description    :   Test class for "ItineraryBuilderController"
* 
**/
 
@isTest
public class  ItineraryBuilderControllerTest {

    /** Create test data for executing test cases  **/
    @testSetup
    static void createTestData(){
        Test.startTest();
        Opportunity opp = TestServices.createOpportunityRecords(1, null)[0];
        Account acc = [SELECT Id FROM Account Limit 1];
        List<Contact> contacts = TestServices.createContactRecords(4, acc.Id);
        List<Travelling_Country__c> travellingCountries = TestServices.createTravellingCountries(opp.Id);
        List<Supplier__c> supplierRecords = TestServices.createSupplierRecords(travellingCountries[0].TC_Country__c);
        List<Supplier_Booking__c> supplierBookingRecords = TestServices.createSupplierBookings(supplierRecords[1].Id, opp.Id);
        TestServices.createSupplierCostPayments(supplierRecords[1].Id, opp.Id);
        List<Client_Group__c> clientGroups = TestServices.createClientGroupRecords(2, opp.Id);
        TestServices.createSupplierCostRecords(supplierRecords[0].Id, clientGroups[0].Id);
        List<Group_Member__c>  groupMembers = TestServices.createGroupMembers(clientGroups[0].Id, new List<Contact>{contacts[0], contacts[1]});
        groupMembers.addAll(TestServices.createGroupMembers(clientGroups[1].Id, new List<Contact>{contacts[2], contacts[3]}));
        List<Where_to_go__c> WTGRecords = TestServices.createWTGRecords(travellingCountries[0].TC_Country__c);
        Campaign camp = new Campaign(Name = 'test', IsActive = true);
        insert camp;
        TestServices.createQuestions();
        TestServices.createHolidaySuggestions(supplierRecords[0].Id, Opp.Id);
        
        /*** Insert data *******/
        Airport__c airport = new Airport__c(Name = 'test');
        insert airport;
        Airport_Terminal__c at = new Airport_Terminal__c(Name = 'test', AT_Class__c = 'Business', AT_Airport__c = airport.Id, AT_Carrier_Name__c = 'test');
        insert at;
        Airport_Terminal__c at1 = new Airport_Terminal__c(Name = 'test', AT_Airport__c = airport.Id, AT_Carrier_Name__c = 'test');
        insert at1;
        
        Supplier__c supplier = [SELECT id FROM Supplier__c Limit 1];
        Room_Type__c rt = new Room_Type__c(RT_Field_Name__c='Room Type', RT_Name__c = 'test', RT_Supplier__c = supplier.Id);
        insert rt;    
        
        Email_Template__c et = new Email_Template__c(ET_Page_Section__c = 'test', ET_Email_Intro__c  = 'test',ET_Email_Closing__c  = 'test', ET_Template_Name__c = 'Itinerary Description');
        insert et;  
        Test.stopTest();  
    }
    
    /*** Test consturctor *****/
    static testMethod void testConstructor(){
        Test.startTest();
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity Limit 1];
        Test.setCurrentPage(Page.ItineraryBuilder);
        ApexPages.standardController controller = new ApexPages.standardController(opp);
        ItineraryBuilderController IBC = new ItineraryBuilderController(controller);
        
        Opportunity newOpp = TestServices.createOpportunityRecords(1, null)[0];
        Contact con = new Contact(FirstName = 'test', LastName ='test');
        insert con;
        Group_Member__c gm = new Group_Member__c(GM_Salutation__c='Lord',
         GM_First_Name__c = con.FirstName,
         GM_Last_Name__c = con.LastName,
         GM_Opportunity__c = newOpp.Id, 
         GM_Client_Group__c = null,
         GM_Lead_Passenger__c = true, 
         GM_Contact__c = con.Id
        );
        controller = new ApexPages.standardController(newOpp);
        ItineraryBuilderController IBC1 = new ItineraryBuilderController(controller);
        System.assertEquals(IBC.oppId, opp.Id);
        Test.stopTest();
    }
    
    /*** Test various operations *****/
    static testMethod void testIBMethods1(){
        Test.startTest();
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity Limit 1];
        Test.setCurrentPage(Page.ItineraryBuilder);
        ApexPages.standardController controller = new ApexPages.standardController(opp);
        ItineraryBuilderController IBC = new ItineraryBuilderController(controller);
        IBC.getRecordType();
        IBC.getData();
        //ItineraryBuilderController.getPicklistValues('Opportunity', 'Type');
        ItineraryBuilderController.includeFlightMargin(true, opp.Id);
        System.assertEquals(false, ItineraryBuilderController.saveGroupMembers(JSON.serialize(IBC.opp.Group_Members__r)));
        Opportunity newOpp = TestServices.createOpportunityRecords(1, null)[0];
        ItineraryBuilderController.getSupplierBookings(newOpp.Id);
        String sbJSON = ItineraryBuilderController.getSupplierBookings(opp.Id);
        ItineraryBuilderController.saveOrder(sbJSON, opp.Id);
        ItineraryBuilderController.saveSB(sbJSON, opp.Id);
        System.assertEquals('Success', ItineraryBuilderController.deleteSB(''));
        Supplier_Cost__c sc = [SELECT id from Supplier_Cost__c Limit 1];
        System.assertNotEquals(Null, ItineraryBuilderController.saveOpportunity(IBC.oppStr));
        System.assertNotEquals(Null, ItineraryBuilderController.CostOptions(opp.Id));
        //ItineraryBuilderController.getSupplierCostByClient(IBC.oppStr, opp.Id);
        System.assertEquals('Success', ItineraryBuilderController.deleteSupplierCost(sc.Id));
        Test.stopTest();
    }
    
     /*** Test various operations of BySupplierComponent*****/
    static testMethod void testBySupplierComponent(){
        Test.startTest();
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity Limit 1];
        ApexPages.currentPage().getParameters().put('id', opp.Id);
        BySupplierComponent bsc = new BySupplierComponent();
        bsc.getSBCostWrapper();
    }
}