Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <fields>
        <fullName>CG_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Groups</relationshipLabel>
        <relationshipName>Client_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CG_PDF_Quotation__c</fullName>
        <label>PDF Quotation Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Holiday_Type__c.object
<CustomObject>
    <label>Holiday Type</label>
    <nameField>
        <label>Holiday Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Itinerary_Text__c.object
<CustomObject>
    <fields>
        <fullName>IT_Holiday_Type__c</fullName>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Quote_Text</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IT_Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IT_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Quote_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Itinerary Text</label>
    <nameField>
        <displayFormat>IT-{0000000000}</displayFormat>
        <label>ItineraryText ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itinerary Text</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Adult__c</fullName>
        <inlineHelpText>Total no of adults in a given family.</inlineHelpText>
        <label>Adult</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Adult</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Choose an agent if this is an agent booking.</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Booking_Currency__c</fullName>
        <label>Booking Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Children__c</fullName>
        <label>Children</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Child</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Destination_Map_Image_ID__c</fullName>
        <label>Destination Map Image ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Infant__c</fullName>
        <label>Infant</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Infant</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Map_Type__c</fullName>
        <label>Map Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Outstanding__c</fullName>
        <formula>Amount - O_Total_Payment_Without_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>O_Quotation_Default_Text__c</fullName>
        <label>Quotation Default Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Quotation_Type__c</fullName>
        <label>Quotation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Default</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Client Group</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>O_Show_Option_text_for_quotation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Option text for quotation</label>
        <type>Checkbox</type>
    </fields>
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <recordTypes>
        <fullName>Accommodation</fullName>
        <active>true</active>
        <label>Accommodation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <recordTypes>
        <fullName>Transfer</fullName>
        <active>true</active>
        <label>Transfer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SB_Itinerary_Description__c</fullName>
        <label>Itinerary Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SB_New_Page__c</fullName>
        <defaultValue>true</defaultValue>
        <label>New Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SB_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SB_Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SB_Remove_Date_Title__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Remove Date Title</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SB_Remove_Images__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Remove Images</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SB_Remove_TextArea__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Remove TextArea</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SB_Show_in_Itinerary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show in Itinerary?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SB_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SB_To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <recordTypes>
        <fullName>Accommodation</fullName>
        <active>true</active>
        <description>Accommodation</description>
        <label>Accommodation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Description</fullName>
        <active>true</active>
        <label>Description</label>
    </recordTypes>
    <recordTypes>
        <fullName>Excursion</fullName>
        <active>true</active>
        <description>What to do</description>
        <label>Excursion</label>
    </recordTypes>
    <recordTypes>
        <fullName>Notes</fullName>
        <active>true</active>
        <label>Notes</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rail</fullName>
        <active>true</active>
        <label>Rail</label>
    </recordTypes>
    <recordTypes>
        <fullName>Transfer</fullName>
        <active>true</active>
        <description>Boat / Car etc...</description>
        <label>Transfer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/SupplierBookingImage__c.object
<CustomObject>
    <fields>
        <fullName>SBI_Attachement_Id__c</fullName>
        <label>Attachement Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBI_Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBI_Supplier_Booking__c</fullName>
        <label>Supplier Booking</label>
        <referenceTo>Supplier_Booking__c</referenceTo>
        <relationshipLabel>SupplierBookingImages</relationshipLabel>
        <relationshipName>SupplierBookingImages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SupplierBookingImage</label>
    <nameField>
        <displayFormat>SBI-{0000000000}</displayFormat>
        <label>SupplierBookingImage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SupplierBookingImages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Accommodation_Region__c</fullName>
        <label>Accommodation/Region</label>
        <picklist>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodation</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_DestinationMap_Image_ID__c</fullName>
        <label>DestinationMap Image ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/ItinerarySetting.cls
public without sharing class ItinerarySetting{

    public ItinerarySetting(HolidayEnquiryController controller) {

    }


    public Opportunity opp{get; set;}
    public String oppStr{get; set;}
    public String DestinationImgs{get; set;}
    public Boolean isOTUK{get; set;}
    public Supplier_Booking__c sbRecord{get; set;}
    public List<picklistValues> recordTypeOptions{get; set;}
    public transient String autoSuggestSupplier{get; set;}
    public transient String autoSuggestTime{get; set;}
    public Boolean haveTravellingCountry{get; set;}
    public transient  String pickLists{get; set;}
    public String lstSupp{get; set;}
    public String nameSpacePrefix{get; set;}
    String oppId;
    static String oppIdS;
        
    public ItinerarySetting(ApexPages.StandardController controller) {
        oppId = controller.getId(); 
        oppIdS = controller.getId();
        ApexClass cs =[select NamespacePrefix from ApexClass where Name =:'HolidayEnquiryController'];
        if(cs.NamespacePrefix != null){
            nameSpacePrefix = cs.NamespacePrefix+'__';
        }
        else{
            nameSpacePrefix = '';
        }  
        isOTUK  = false;
        recordTypeOptions = new List<picklistValues>();
        List<DestinationImages> lstDestinationImgs = new List<DestinationImages>();
        lstSupp = '';
        
        sbRecord = new Supplier_Booking__c();
        if(oppId != null){
            opp = [select id, O_Show_Option_text_for_quotation__c, O_Quotation_Type__c, O_Quotation_Default_Text__c, Name,Account.Name,O_Agent__r.id,O_Agent__r.Name, O_Departure_Date__c, O_Return_Date__c,Owner.Name,Owner.Username,
                       O_Adult__c,O_Children__c,O_Infant__c,O_Map_Type__c,O_Holiday_Type__c,Amount,O_Outstanding__c,O_Destination_Map_Image_ID__c,O_Booking_Currency__c,
                       (Select Id,Name,CG_PDF_Quotation__c from Client_Groups__r),
                       (Select Id, name, TC_Country__r.Name,TC_DestinationMap_Image_ID__c,TC_Accommodation_Region__c from Travelling_Countries__r order by TC_Country__r.Name)
                       from Opportunity  where Id=:oppId];
            setAutoSuggest();
        }
        for(Travelling_Country__c tc : Opp.Travelling_Countries__r){
           lstDestinationImgs.add(new DestinationImages(tc));    
        }
        
        DestinationImgs = JSON.serialize(lstDestinationImgs);
        oppStr = JSON.serialize(opp);
        pickLists = JSON.serialize(Utility.describePickLists('Opportunity'));
    }
    
    
    //Fetch all the PDF Setting Page Messages
    public String getHEPageErrorMessage(){
        return JSON.serialize(ErrorMessageController.getErrorMessage('PDFSetting'));
    }
    
    void setAutoSuggest(){
        //Set Supplier 
       
        
    }
   
    public string getData(){  
       String oppId = ApexPages.currentPage().getParameters().get('id');
       List<Supplier_Booking__c> lstSupplierBooking = new List<Supplier_Booking__c>();
       if(oppId != ''){
            for(Supplier_Booking__c sb : [select id, name, recordtype.name, SB_Remove_Images__c,SB_Remove_TextArea__c,SB_Remove_Date_Title__c, SB_New_Page__c, SB_Itinerary_Description__c,SB_From_Date__c, SB_To_Date__c,SB_Order__c,
                                        SB_Supplier__c,(select id,SBI_Attachement_Id__c,SBI_Order__c from SupplierBookingImages__r where SBI_Order__c != 3 and SBI_Order__c != 4 limit 4) 
                                        from Supplier_Booking__c  where SB_Opportunity__c =: oppId and SB_Show_in_Itinerary__c = true Order by SB_Order__c ASC]){
                if(sb.SB_Itinerary_Description__c == null){
                    sb.SB_Itinerary_Description__c = '<div><br/></div>';
                }
                lstSupplierBooking.add(sb);
            }
        }
        //system.assert(False,JSON.serialize(lstSupplierBooking));
        return JSON.serialize(lstSupplierBooking);
    } 
    
    
    
    public string getDataStay(){  
       String oppId = ApexPages.currentPage().getParameters().get('id');
       List<whereWillYouStay> lstSupplierBooking = new List<whereWillYouStay>();
       if(oppId != ''){
            Set<String> setSBIds = new Set<String>();
            String holidayType;
            List<Supplier_Booking__c> lstSB = [select id, name,SB_Opportunity__r.O_Holiday_Type__c, SB_Remove_Images__c,SB_Remove_TextArea__c,SB_Remove_Date_Title__c, recordtype.name, SB_New_Page__c, SB_Itinerary_Description__c,SB_From_Date__c, SB_To_Date__c,SB_Order__c,
                                        SB_Supplier__c,SB_Supplier__r.name,(select id,SBI_Attachement_Id__c,SBI_Order__c from SupplierBookingImages__r where SBI_Order__c = 3 OR SBI_Order__c = 4) 
                                        from Supplier_Booking__c  where SB_Opportunity__c =: oppId and recordtype.Name in ('Accommodation') Order by SB_Order__c];
            for(Supplier_Booking__c sb : lstSB){
                if(sb.SB_Supplier__c != null){
                    setSBIds.add(sb.SB_Supplier__c);
                }
                if(holidayType == null){
                    holidayType = sb.SB_Opportunity__r.O_Holiday_Type__c;
                }    
            }
            
            Map<String,Itinerary_Text__c> mapQT = new Map<String,Itinerary_Text__c>();
            if(holidayType != null){
                for(Itinerary_Text__c qt: [select IT_Message__c,IT_SUPPLIER__C,IT_Holiday_Type__c from Itinerary_Text__c where (IT_Holiday_Type__c = :holidayType)
                                        AND IT_SUPPLIER__C in :setSBIds order by IT_SUPPLIER__C desc ]){                              
                    mapQT.put(qt.IT_SUPPLIER__C,qt);   
                }   
            }
            for(Itinerary_Text__c qt: [select IT_Message__c,IT_SUPPLIER__C,IT_Holiday_Type__c from Itinerary_Text__c where 
                                     (IT_Holiday_Type__c != :Opp.O_Holiday_Type__c OR IT_Holiday_Type__r.Name='Generic')
                                          AND IT_SUPPLIER__C in :setSBIds order by IT_SUPPLIER__C desc ]){ 
                if(!mapQT.containsKey(qt.IT_SUPPLIER__C)){ 
                    mapQT.put(qt.IT_SUPPLIER__C,qt);       
                }      
            }       
            Set<String> setOfSupplier = new  Set<String>();   
            for(Supplier_Booking__c sb : lstSB){
                if(!setOfSupplier.contains(sb.SB_Supplier__c)){    
                    
                    if(mapQT.containsKey(sb.SB_Supplier__c)){
                        lstSupplierBooking.add(new whereWillYouStay(sb,mapQT.get(sb.SB_Supplier__c))); 
                        setOfSupplier.add(sb.SB_Supplier__c);   
                          
                    }
                    else{
                        lstSupplierBooking.add(new whereWillYouStay(sb,new Itinerary_Text__c()));   
                        setOfSupplier.add(sb.SB_Supplier__c);          
                    }
                }
            }
        }
        return JSON.serialize(lstSupplierBooking);
    } 
    
    
    public String getRecordType() {
        List<picklistValues > options = new List<picklistValues >();
        options.add(new picklistValues('','--Select--'));
        for (recordType  obj : [Select Id,Name from recordType where SobjectType = :Utility.getNameSpacePrefix()+'Supplier_Booking__c']) {
            options.add(new picklistValues(obj.Id,obj.Name));
        }
        
        return JSON.serialize(options);
    } 
    
    public void saveSB(){
        Utility.isCopied = true;
        update (List<Supplier_Booking__c>)JSON.deserialize(lstSupp, List<Supplier_Booking__c>.class);
    }
    
    @remoteAction
    public static String saveSBI(String SBID,String jsonDataImages,String oppId,boolean stay){
        if(!stay){
            List<SupplierBookingImage__c> lstSBImages = (List<SupplierBookingImage__c>)JSON.deserialize(jsonDataImages, List<SupplierBookingImage__c>.class);
            List<String> lstSBId = new List<String>();
            List<SupplierBookingImage__c> lstSBImages1 = new List<SupplierBookingImage__c>();
            String sbIds = SBID.trim().remove('"');
            delete Database.query('Select Id from SupplierBookingImage__c where SBI_Supplier_Booking__c =\''+sbIds+'\' and SBI_Order__c!= 3 and SBI_Order__c != 4');
            
            Integer order =1;
            for(SupplierBookingImage__c sbi: lstSBImages){
                if(sbi.SBI_Attachement_Id__c == null){
                    lstSBId.add(sbi.SBI_Supplier_Booking__c);
                }
                else{
                    sbi.Id = null;
                    sbi.SBI_Order__c = order;
                    lstSBImages1.add(sbi);
                    order++;
                }
            }
            //delete [Select Id from SupplierBookingImage__c where SBI_Supplier_Booking__c in :lstSBId and SBI_Supplier_Booking__r.SB_Opportunity__c =:oppId and SBI_Order__c!= 3 and SBI_Order__c != 4];
            Utility.isCopied = true;
            upsert lstSBImages1;
            return 'Success'+SBID;
        }
        else{
            List<SupplierBookingImage__c> lstSBImages = (List<SupplierBookingImage__c>)JSON.deserialize(jsonDataImages, List<SupplierBookingImage__c>.class);
            List<String> lstSBId = new List<String>();
            List<SupplierBookingImage__c> lstSBImages1 = new List<SupplierBookingImage__c>();
            String sbIds = SBID.trim().remove('"');
            delete Database.query('Select Id from SupplierBookingImage__c where SBI_Supplier_Booking__c =\''+sbIds+'\' and (SBI_Order__c= 3 or SBI_Order__c = 4)');
            
            Integer order =3;
            for(SupplierBookingImage__c sbi: lstSBImages){
                if(sbi.SBI_Attachement_Id__c == null){
                    lstSBId.add(sbi.SBI_Supplier_Booking__c);
                }
                else{
                    sbi.Id = null;
                    sbi.SBI_Order__c = order;
                    lstSBImages1.add(sbi);
                    order++;
                }
            }
            //delete [Select Id from SupplierBookingImage__c where SBI_Supplier_Booking__c in :lstSBId and SBI_Supplier_Booking__r.SB_Opportunity__c =:oppId and SBI_Order__c!= 3 and SBI_Order__c != 4];
            Utility.isCopied = true;
            upsert lstSBImages1;
            return 'Success'+SBID;    
        }
    }
    
    
    @remoteAction
    public static String saveSBITC(String jsonDataImages,String oppId){
        if(true){
            return 'Success';    
        }
        return null;
    }
    
    @remoteAction
    public static String saveSB(String jsonData,String jsonDataImages,String oppId){
        try{
           /*List<SupplierBookingImage__c> lstSBImages = (List<SupplierBookingImage__c>)JSON.deserialize(jsonDataImages, List<SupplierBookingImage__c>.class);
             List<Supplier_Booking__c> lstSB = (List<Supplier_Booking__c>)JSON.deserialize(jsonData, List<Supplier_Booking__c>.class);
             List<String> lstSBId = new List<String>();
            
            for(SupplierBookingImage__c sbi: lstSBImages){
                if(sbi.SBI_Attachement_Id__c == null){
                    lstSBId.add(sbi.SBI_Supplier_Booking__c);
                }
            }
            delete [Select Id from SupplierBookingImage__c where SBI_Supplier_Booking__c in :lstSBId and SBI_Supplier_Booking__r.SB_Opportunity__c =:oppId and SBI_Order__c!= 3 and SBI_Order__c != 4];
            upsert lstSBImages;*/
            
           
            Utility.isCopied = true;
            update (List<Supplier_Booking__c>)JSON.deserialize(jsonData, List<Supplier_Booking__c>.class);
            
            
           List<Supplier_Booking__c> lstSupplierBooking = new List<Supplier_Booking__c>();
           if(oppId != ''){
                for(Supplier_Booking__c sb : [select id, name, SB_Remove_Images__c,SB_Remove_TextArea__c,SB_Remove_Date_Title__c, recordtype.name, SB_New_Page__c, SB_Itinerary_Description__c,SB_From_Date__c, SB_To_Date__c,SB_Order__c,
                                            SB_Supplier__c,(select id,SBI_Attachement_Id__c,SBI_Order__c from SupplierBookingImages__r where SBI_Order__c != 3 and SBI_Order__c != 4 limit 4) 
                                            from Supplier_Booking__c  where SB_Opportunity__c =:oppId and recordtype.Name in ('Accommodation','Car Hire','Days at Leisure','Dom Flights','Excursion','Int Flight','Light Aircraft','Notes','Own arrangement','Rail','Transfer','Description') Order by SB_Order__c]){
                    if(sb.SB_Itinerary_Description__c == null){
                        sb.SB_Itinerary_Description__c = '<div><br/></div>';
                    }
                    lstSupplierBooking.add(sb);
                }
            }
            
            return JSON.serialize(lstSupplierBooking);
        }
        Catch(Exception e){
            return e.getMessage()+e.getStackTraceString();
        }
    }
    
    @remoteAction
    public static String saveSBS(String jsonData,String jsonDataImages,String oppstr, String lstDestinationImgstr, string clientGroups){
        try{
            
            Opportunity opp = (Opportunity)JSON.deserialize(oppstr, Opportunity.class);
            update opp;
            
            List<Client_Group__c> lstClientGroups = (List<Client_Group__c>)JSON.deserialize(clientGroups, List<Client_Group__c>.class);
            update lstClientGroups;
            
            List<DestinationImages> lstDestination = (List<DestinationImages>)JSON.deserialize(lstDestinationImgstr, List<DestinationImages>.class);
            List<Travelling_Country__c> lstTc = new List<Travelling_Country__c>();
            for(DestinationImages maps: lstDestination){
                lstTc.add(maps.tc);
            }
            update lstTc;
            
            Utility.isCopied = true;
            update (List<Supplier_Booking__c>)JSON.deserialize(jsonData, List<Supplier_Booking__c>.class);
            
            
           List<Supplier_Booking__c> lstSupplierBooking = new List<Supplier_Booking__c>();
           if(opp.Id != null){
                for(Supplier_Booking__c sb : [select id, name, SB_Remove_Images__c,SB_Remove_TextArea__c,SB_Remove_Date_Title__c, recordtype.name, SB_New_Page__c, SB_Itinerary_Description__c,SB_From_Date__c, SB_To_Date__c,SB_Order__c,
                                            SB_Supplier__c,(select id,SBI_Attachement_Id__c,SBI_Order__c from SupplierBookingImages__r where SBI_Order__c != 3 and SBI_Order__c != 4 limit 4) 
                                            from Supplier_Booking__c  where SB_Opportunity__c =: opp.Id and recordtype.Name in ('Accommodation','Car Hire','Days at Leisure','Dom Flights','Excursion','Int Flight','Light Aircraft','Notes','Own arrangement','Rail','Transfer','Description') Order by SB_Order__c]){
                    if(sb.SB_Itinerary_Description__c == null){
                        sb.SB_Itinerary_Description__c = '<div><br/></div>';
                    }
                    lstSupplierBooking.add(sb);
                }
            }
            
            return JSON.serialize(lstSupplierBooking);
        }
        Catch(Exception e){
            System.assert(false, e.getMessage()+e.getStackTraceString());
            return e.getMessage()+e.getStackTraceString();
        }
    }
    
    @remoteAction
    public static List<attachment> search(String searchContext){
        List<String> lstSelected = searchContext.split(',');
        
        if(lstSelected.size() != 0){
         return [select id, parentId,name from attachment 
            where (parentId in : lstSelected) and (NOT Name like '%cover%') ];
        }
        else{
            return null;
        }
    }
    
    @RemoteAction
    public static String doUploadAttachment(String acctId, String attachmentBody, String attachmentName, String attachmentId) {
        if(acctId != null) {
            if(acctId  != null) {
                if(attachmentBody != null) {
                    Attachment att = new Attachment();
                    String newBody = '';
                    if(att.Body != null) {
                        newBody = EncodingUtil.base64Encode(att.Body);
                    }
                    newBody += attachmentBody;
                    att.Body = EncodingUtil.base64Decode(newBody);
                    if(attachmentId == null) {
                        att.Name = attachmentName;
                        att.parentId = acctId;
                    }
                    upsert att;
                    if(acctId != null){
                        List<Travelling_Country__c> lstTC = new List<Travelling_Country__c>();
                        for(Travelling_Country__c tc : [Select Id from Travelling_Country__c where Id = :acctId]){
                            tc.TC_DestinationMap_Image_ID__c = att.Id;
                            lstTC.add(tc);
                        }
                        update lstTC;
                    }
                    return att.Id;
                } else {
                    return 'Attachment Body was null';
                }
            } else {
                return 'Account could not be found';
            }
        } else {
            return 'Account Id was null';
        }
    }
    
    
    public Class whereWillYouStay{
        public Supplier_Booking__c sb{get; set;}
        public Itinerary_Text__c qt{get; set;}
        
        public whereWillYouStay(Supplier_Booking__c sb, Itinerary_Text__c qt){
            this.sb = sb;
            this.qt = qt;    
        }
    }
    
    public class DestinationImages{
        public Travelling_Country__c tc{get;set;}
        public DestinationImages(Travelling_Country__c  tc){
            this.tc = tc;
        }    
    }
    
    public class picklistValues{
        String label {get; set;}
        String value {get; set;}
        
        public picklistValues(String value,String label){
            this.value = value;
            this.label = label;
        }
    }
}