Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <fields>
        <fullName>CG_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Groups</relationshipLabel>
        <relationshipName>Client_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Client_Payment__c.object
<CustomObject>
    <fields>
        <fullName>CP_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Payments</relationshipLabel>
        <relationshipName>Client_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CP_Receipt_AmountEx__c</fullName>
        <label>Receipt Amount (excl Credit Charge)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>CP_Opportunity__r.O_Country__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Client Payment</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Client Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>C_Lead_Passenger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Passenger</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Continent__c.object
<CustomObject>
    <description>A list of the regions - continents?</description>
    <label>Continent</label>
    <nameField>
        <label>Continent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Continents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <fields>
        <fullName>C_Continent__c</fullName>
        <inlineHelpText>Which region is the country in?</inlineHelpText>
        <label>Continent</label>
        <referenceTo>Continent__c</referenceTo>
        <relationshipLabel>Countries</relationshipLabel>
        <relationshipName>Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Client_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Group</label>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Lead_Passenger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Passenger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Holiday_Type__c.object
<CustomObject>
    <label>Holiday Type</label>
    <nameField>
        <label>Holiday Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/BookingFormControllerTest.cls
/**
 *  @Author         :   Naval Sharma
 *  @Date           :   2-Feb-2016
 *  @Description    :   Test class for "BookingFormController"
 * 
 * */
 
@isTest
public Class BookingFormControllerTest{
    
    @testSetup 
    static void testSetupMethod() {
        Holiday_Type__c ht= new Holiday_Type__c(Name='testHoliday');
        insert ht ;  
        system.assert(ht.Id != null); 
        
        Account TestAcc = new Account(Name = 'Test Test1');
        insert TestAcc ;  
        system.assert(TestAcc.Id != null);  
        
        Contact cont = new Contact(Salutation='testsal',LastName='testL',FirstName='testF',email='testemail@a.com',AccountId=TestAcc.Id);
        insert cont;
        system.assert(cont.Id != null);
        Opportunity opp =  new Opportunity (AccountId = TestAcc.Id,StageName = 'Enquiry',name = 'TestOpportunity',CloseDate = Date.today(),O_Departure_Date__c = Date.today(),O_Return_Date__c = Date.today(),
                                     O_Holiday_Type__c=ht.Id, Amount=1024, CurrencyISOCode='GBP');
        insert opp;
        system.assert(opp.Id != null);
        
        List<Client_Group__c> cgList = TestServices.createClientGroupRecords(2, opp.Id);
         
        List<Group_Member__c> gmList = new List<Group_Member__c>();
        
        for(Contact con : [Select id from Contact]){
            Group_Member__c gm = new Group_Member__c(GM_Client_Group__c = cgList[0].Id, GM_Contact__c = con.Id, GM_Opportunity__c = cgList[0].CG_Opportunity__c);    
            gmList.add(gm);
        }
        insert gmList;
        
        Client_Payment__c cp = new Client_Payment__c(CP_Receipt_AmountEx__c =90,CP_Opportunity__c=opp.id);
        insert cp;
        system.assert(cp.Id != null);
        
        Continent__c cn = new Continent__c(name='testcon');
        insert cn ;
        system.assert(cn.Id != null);   
        
        Country__c c= new Country__c(name='testcoun',C_Continent__c=cn.Id);
        insert c ;
        system.assert(c.Id != null);   
        
        Travelling_Country__c tc = new Travelling_Country__c(TC_Opportunity__c=opp.Id,TC_Country__c=c.Id);      
        insert tc;
        system.assert(tc.Id != null);   
                  
    }
    
    static testmethod void testMethod1(){
        List<Opportunity> opp = [Select ID from Opportunity];
        system.assert(opp[0].id != null);   
        ApexPages.StandardController stdctrl = new  ApexPages.StandardController(opp[0]); 
        ApexPages.currentPage().getParameters().put('id',opp[0].id); 
        BookingFormController AIC = new BookingFormController(stdctrl );
    }
    
    static testmethod void testMethod2(){
        List<Opportunity> opp = [Select ID, AccountId from Opportunity];
        system.assert(opp[0].id != null);   
        Contact con = new Contact(AccountId = opp[0].AccountId, FirstName = 'Test', LastName = 'Test1', C_Lead_Passenger__c = true);
        insert con;
        List<Client_Group__c> cgList = [Select Id, CG_Opportunity__c from Client_Group__c];
        Group_Member__c gm = new Group_Member__c(GM_Client_Group__c = cgList[0].Id, GM_Contact__c = con.Id, GM_Opportunity__c = cgList[0].CG_Opportunity__c, GM_Lead_Passenger__c = true);    
        insert gm;
        system.assert(gm.id != null);   
        ApexPages.StandardController stdctrl = new  ApexPages.StandardController(opp[0]); 
        ApexPages.currentPage().getParameters().put('id',opp[0].id); 
        BookingFormController AIC = new BookingFormController(stdctrl );
    }
    
    static testmethod void testMethod3(){
        List<Opportunity> opp = [Select ID, AccountId from Opportunity];
        system.assert(opp[0].id != null);   
         
        ApexPages.StandardController stdctrl = new  ApexPages.StandardController(opp[0]); 
        ApexPages.currentPage().getParameters().put('id',opp[0].id); 
        BookingFormController AIC = new BookingFormController(stdctrl );
        AIC.getSalutaionOptions();
        AIC.getnationalityOptions();
        AIC.Confirm();
    }
}