Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Cost__c.object
<CustomObject>
    <description>Supplier Cost</description>
    <fields>
        <fullName>SC_Client_Group__c</fullName>
        <label>Client Group</label>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Supplier Costs</relationshipLabel>
        <relationshipName>Supplier_Costs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SC_Option__c</fullName>
        <label>Option</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SC_Supplier_Booking__c</fullName>
        <label>Supplier Booking</label>
        <referenceTo>Supplier_Booking__c</referenceTo>
        <relationshipLabel>Supplier Costs</relationshipLabel>
        <relationshipName>Supplier_Costs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SC_Total_Client_Group_Cost__c</fullName>
        <label>Total Client Group Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SC_Total_Net_CostSC__c</fullName>
        <label>Total Net Cost Selling Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Supplier Cost</label>
    <nameField>
        <displayFormat>SBC-{0000000000}</displayFormat>
        <label>Supplier Cost ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/ChartController.cls
global class ChartController {

    public ChartController() {
    
    }

    
    public ChartController(Apexpages.standardController controller) {
    
    }
    
    
    @RemoteAction
    global static Map<String,List<Supplier_Cost__c>> getChartDataStr(String oId) {
        try{
            Map<String,List<Supplier_Cost__c>> mapSuppleirCost = new Map<String,List<Supplier_Cost__c>>();
            for(Supplier_Cost__c sc : [select id, SC_Option__c, SC_Total_Client_Group_Cost__c,SC_Total_Net_CostSC__c from Supplier_Cost__c 
                                        where SC_Supplier_Booking__r.SB_Opportunity__c =: oId order by SC_Option__c]){
                if(!mapSuppleirCost.containsKey(sc.SC_Option__c)){
                    mapSuppleirCost.put(sc.SC_Option__c, new List<Supplier_Cost__c>());
                }   
                mapSuppleirCost.get(sc.SC_Option__c).add(sc);
            }
            return mapSuppleirCost;
        }
        Catch(Exception e){
            System.assert(false, e.getstacktraceString());
            return null;
        }
    }
    
    @RemoteAction
    global static Map<String,Map<String,List<Supplier_Cost__c>>> getChartDataByClient(String oId) {
        try{
            Map<String,Map<String,List<Supplier_Cost__c>>> mapSuppleirCost = new Map<String,Map<String,List<Supplier_Cost__c>>>();
            for(Supplier_Cost__c sc : [select id, SC_Client_Group__c,SC_Total_Net_CostSC__c, SC_Client_Group__r.Name, SC_Option__c, SC_Total_Client_Group_Cost__c 
                                        from Supplier_Cost__c where SC_Supplier_Booking__r.SB_Opportunity__c =: oId order by SC_Option__c]){
                if(!mapSuppleirCost.containsKey(sc.SC_Client_Group__r.Name)){
                    mapSuppleirCost.put(sc.SC_Client_Group__r.Name, new Map<String,List<Supplier_Cost__c>>());
                }
                
                if(!mapSuppleirCost.get(sc.SC_Client_Group__r.Name).containsKey(sc.SC_Option__c)){
                    mapSuppleirCost.get(sc.SC_Client_Group__r.Name).put(sc.SC_Option__c, new List<Supplier_Cost__c>());
                }   
                mapSuppleirCost.get(sc.SC_Client_Group__r.Name).get(sc.SC_Option__c).add(sc);
            }
            return mapSuppleirCost;
        }
        Catch(Exception e){
            System.assert(false, e.getstacktraceString());
            return null;
        }
    }
    
    
    
}