Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <fields>
        <fullName>CG_Lead_Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Group Member</label>
        <referenceTo>Group_Member__c</referenceTo>
        <relationshipLabel>Client Groups</relationshipLabel>
        <relationshipName>Client_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CG_Selling_Price__c</fullName>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Client_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>CI_Client_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Client_Group__c.CG_Opportunity__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.I_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Client Invoices</relationshipLabel>
        <relationshipName>Client_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CI_Credit_Note_Amount__c</fullName>
        <label>Credit Note Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CI_Deposit_Overwrite__c</fullName>
        <formula>CI_Client_Group__r.CG_Deposit_Overwrite__c</formula>
        <label>Deposit Overwrite</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CI_Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI_Proforma_Type__c</fullName>
        <label>Proforma Type</label>
        <picklist>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>I_Balance_Outstanding__c</fullName>
        <description>IF(RecordType.DeveloperName &lt;&gt; &quot;Credit Note&quot;, IF(ISBLANK( ATOF__CI_Client_Group__r.Id ), ATOF__I_Opportunity__r.ATOF__O_Outstanding__c, ATOF__I_Total_Price__c -  ATOF__I_Payment_Received__c ), 0)</description>
        <formula>IF(RecordType.DeveloperName &lt;&gt; &quot;Credit Note&quot;, IF(ISBLANK( CI_Client_Group__r.Id ), I_Opportunity__r.O_Outstanding__c, I_Total_Price__c - I_Payment_Received__c ), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>I_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>I_Final_Payment_Due__c</fullName>
        <formula>I_Opportunity__r.O_Due_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Payment Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>I_Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>I_Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>I_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Invoices</relationshipLabel>
        <relationshipName>Client_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>I_Payment_Received__c</fullName>
        <formula>IF(ISBLANK( CI_Client_Group__r.Id ), I_Opportunity__r.O_Total_Payment1__c-I_Opportunity__r.O_Total_Credit_Card_Charges__c,  I_Payment_Received_CG__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>I_Total_Price__c</fullName>
        <description>IF(RecordType.Name != &apos;Deposit&apos;,IF(ISBLANK( ATOF__CI_Client_Group__r.Id ), ATOF__I_Opportunity__r.Amount, ATOF__CI_Client_Group__r.ATOF__CG_Selling_Price__c), IF(ISBLANK( ATOF__CI_Client_Group__r.Id ),  ATOF__I_Opportunity__r.ATOF__O_Deposit_Required__c ,  ATOF__I_Total_Price_CG__c ))</description>
        <formula>IF(AND(RecordType.Name != &apos;Deposit&apos;,OR(TEXT(CI_Proforma_Type__c)=&apos;Committed&apos;,ISBLANK(TEXT(CI_Proforma_Type__c)))) ,IF(ISBLANK( CI_Client_Group__r.Id ), I_Opportunity__r.Amount, CI_Client_Group__r.CG_Selling_Price__c), IF(ISBLANK( CI_Client_Group__r.Id ), I_Opportunity__r.O_Deposit_Required1__c , I_Total_Price_CG__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Client Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Client Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Invoices</pluralLabel>
    <recordTypes>
        <fullName>Proforma</fullName>
        <active>true</active>
        <description>This is a Proforma Invoice</description>
        <label>Proforma Invoice</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>ER_Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>ER-{00000000}</displayFormat>
        <label>Exchange Rate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <recordTypes>
        <fullName>Sell</fullName>
        <active>true</active>
        <label>Sell</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Adult__c</fullName>
        <inlineHelpText>Total no of adults in a given family.</inlineHelpText>
        <label>Adult</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Adult</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Choose an agent if this is an agent booking.</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Booking_Currency__c</fullName>
        <label>Booking Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Children__c</fullName>
        <label>Children</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Child</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Due_Date__c</fullName>
        <description>IF( O_Display_Due_Date__c&gt; 60 , O_Departure_Date__c - 90, O_Departure_Date__c - 60)</description>
        <formula>IF(  ISNULL(O_Display_Due_Date__c) , O_Departure_Date__c - 60, O_Departure_Date__c - O_Display_Due_Date__c)</formula>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Exchange_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exchange Rate</label>
        <referenceTo>Exchange_Rate__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Infant__c</fullName>
        <label>Infant</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Infant</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Itinerary_Cover_Name__c</fullName>
        <label>Itinerary Cover Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Margin__c</fullName>
        <label>Margin Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Outstanding__c</fullName>
        <formula>Amount - O_Total_Payment_Without_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>O_RecordType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Record Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Record_Type__c.RT_SObject_Type__c</field>
                <operation>equals</operation>
                <value>Opportunity</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Record_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Reference_Number__c</fullName>
        <label>Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/InvoiceController.cls
public class InvoiceController{
    public string oppId {get;set;}
    public string InvId {get;set;}
    public Opportunity Opp{get;set;}
    public Client_Invoice__c ClientInv {get; set;}
    public Decimal totalClientPayment{get; set;}
    public Decimal depositRequired{get; set;}
    public Contact GroupMemberContact {get;set;}
    public List<HeaderFooter> lstHF{get; set;}
    
    public PaymentMethods objPaymentMethods{get; set;}
    public Map<String,Exchange_Rate__c> mapExchangeRate{get;set;}
    
    public InvoiceController(Apexpages.standardcontroller controller){
        try{
            InvId = controller.getId();
            totalClientPayment = 0;
            depositRequired = 0;
            if (controller.getId() != null) {
                for(Client_Invoice__c CI : [select id,name,CI_Deposit_Overwrite__c ,CI_Proforma_Type__c,CI_Client_Group__c,CI_Client_Group__r.CG_Selling_Price__c,
                                            recordType.Name,recordTypeId,I_Opportunity__c,I_Invoice_Date__c,I_Total_Price__c,I_Balance_Outstanding__c,CI_Client_Group__r.CG_Lead_Group_Member__c,
                                            I_Final_Payment_Due__c,I_Payment_Received__c,I_Invoice_Number__c,CI_Credit_Note_Amount__c,I_Description__c,CI_Client_Group__r.CG_Lead_Group_Member__r.GM_Contact__c,
                                            CI_Invoice_Number__c from Client_Invoice__c where id = : InvId]){
                    ClientInv = CI;
                }   
                
                Opp = [select id,currencyISOCode,closeDate, O_RecordType__c,O_Exchange_Rate__r.ER_Exchange_Rate__c, Name,O_Margin__c, Account.Name,Account.BillingStreet,Account.BillingCity,Account.BillingState,Account.BillingCountry,Account.BillingPostalCode,O_Agent__r.id,O_Agent__r.Name, O_Departure_Date__c, O_Return_Date__c,Owner.Name,Owner.Username,
                       O_Adult__c,O_Children__c,O_Infant__c,O_Holiday_Type__c,Amount,O_Outstanding__c,O_Booking_Currency__c,StageName,O_Itinerary_Cover_Name__c,O_Reference_Number__c,O_Due_Date__c,O_Country__c,O_Deposit_Required1__c,
                       O_Itinerary_Display_Price__c,O_Total_Payment__c,(select GM_Contact__r.C_Full_Name_on_Passport__c
                                         from Group_Members__r),O_Suggested_Margin__r.M_Margin__c,
                         (Select ID,Previous_Recommended_Selling_Price__c,CG_Deposit_Required_I__c,CG_Recommended_Selling_Price_Rp__c, Name,CG_Total_Recommended_Selling_Price__c,CG_Selling_Price__c,
                       CG_Charity__c, CG_Regulatory_Charges__c, CG_FX_Transfer_Charges__c, CG_Arrival_Presents__c from Client_Groups__r)
                       from Opportunity where Id=:ClientInv.I_Opportunity__c];
                
                //Proporma Invoice Functionality
                if(ClientInv.recordType.Name == 'Proforma Invoice'){
                    ClientInv.recordType.Name = ClientInv.CI_Proforma_Type__c;
                }
                
                List<Client_Payment__c> lstClientPayment = [Select Id,CP_Receipt_AmountEx__c,CP_Amount__c,CP_Payee__c,CP_Client_Invoice__c from Client_payment__c where CP_Opportunity__c = :opp.Id and 
                                                            CP_Processed_On__c != null and CP_Payee__c != null];   
                List<Supplier_Cost__c> lstSupplierCost = [Select Id,SC_Supplier_Booking__c,SC_Total_Net_CostSC__c,SC_Supplier_Booking__r.recordType.Name,SC_Client_Group__c  
                                                                from Supplier_Cost__c where SC_Supplier_Booking__r.SB_Opportunity__c = :opp.Id];
                Map<String,Integer> mapCountOfSB = new Map<String,Integer>();
                for(Supplier_Cost__c sbc : lstSupplierCost){
                    if(!mapCountOfSB.containsKey(sbc.SC_Supplier_Booking__c)){
                        mapCountOfSB.put(sbc.SC_Supplier_Booking__c,0);
                    } 
                    Integer count = mapCountOfSB.get(sbc.SC_Supplier_Booking__c);
                    mapCountOfSB.put(sbc.SC_Supplier_Booking__c,count+1);
                }
                if(ClientInv.CI_Client_Group__c != null && ClientInv.CI_Client_Group__r.CG_Lead_Group_Member__c != null && ClientInv.CI_Client_Group__r.CG_Lead_Group_Member__r.GM_Contact__c != null)
                    GroupMemberContact = [Select id, salutation, firstName, lastName, MailingStreet, MailingState, MailingPostalCode,MailingCountry,
                                          MailingCity from Contact where id =: ClientInv.CI_Client_Group__r.CG_Lead_Group_Member__r.GM_Contact__c];
                //system.assert(false,GroupMemberContact); 
                for(Client_Group__c cg : opp.Client_Groups__r){
                    if(ClientInv.CI_Client_Group__c != null && cg.id == ClientInv.CI_Client_Group__c){
                        for(Client_Payment__c cp : lstClientPayment){
                            if(ClientInv.CI_Client_Group__c == cp.CP_Payee__c ){
                                totalClientPayment  +=  cp.CP_Receipt_AmountEx__c;
                            }
                        }
                        if(cg.CG_Deposit_Required_I__c != null){ 
                            depositRequired += cg.CG_Deposit_Required_I__c;
                        }
                        
                        
                    }    
                }
                
            }
        
            //Set Header/ Footer
            lstHF = new List<HeaderFooter>();
            List<Document> lstDoc = [Select Id,Name from Document where Name like '%Client Invoice%'];
            HeaderFooter header = new HeaderFooter('','');
            HeaderFooter footer = new HeaderFooter('','');
           
            for(Document doc : lstDoc){
                if(doc.name.contains('Header')){
                    header.imageId = doc.Id;
                }    
                if(doc.name.contains('Footer')){
                    footer.imageId = doc.Id;
                }
            }
            lstHF.add(header);
            lstHF.add(footer);
            
            //Payment Methods
            mapExchangeRate = new Map<String,Exchange_Rate__c>();
            Set<String> lstPmsCurrency = new Set<String>();
            List<Payment_Method__c> lstPM = [Select Id,CurrencyISOCode,recordType.DeveloperName,PM_Description__c from Payment_Method__c 
                                        where PM_Record_Type__c = :Opp.O_RecordType__c];
            List<Date> lstMinMaxDPDate = Utility.FindMinMaxDate(new Set<Date>{Opp.CloseDate});
            List<Date> lstMinMaxCloseDate = Utility.FindMinMaxDate(new Set<Date>{Opp.O_Departure_Date__c});
            
            for(Payment_Method__c pm : lstPM){
                lstPmsCurrency.add(pm.currencyISOCode);
            }
            for(Exchange_Rate__c er : SOQLServices.getExchangeRate(lstPmsCurrency,lstMinMaxCloseDate,lstMinMaxDPDate,'Sell')){
                if(er.ER_Base_Currency__c == Opp.CurrencyISOCOde){
                    mapExchangeRate.put(er.ER_Sales_Currency__c, er);
                }
            }
            objPaymentMethods = new PaymentMethods(new List<Payment_Method__c>(), new Payment_Method__c(), new Payment_Method__c(), new Payment_Method__c());
            for(Payment_Method__c pm : lstPM){
                if(pm.recordType.DeveloperName == 'Payment_Method'){
                    objPaymentMethods.lstMethods.add(pm);
                }
                if(pm.recordType.DeveloperName  == 'Important_Notes'){
                    objPaymentMethods.imprtantNotes = pm;
                }
                if(pm.recordType.DeveloperName == 'Cheques_Notes'){
                    objPaymentMethods.chequesNotes = pm;
                }
                if(pm.recordType.DeveloperName == 'Footer'){
                    objPaymentMethods.footer = pm;
                }
                
            }
            
            
        }
        catch(Exception e){
            System.assert(false, e.getStackTraceString());
        }
        
    }
    
    public Class PaymentMethods{
        public List<Payment_Method__c> lstMethods{get; set;}
        public Payment_Method__c imprtantNotes{get; set;}
        public Payment_Method__c  chequesNotes{get; set;}
        public Payment_Method__c footer{get;set;}
        public Exchange_Rate__c ex{get; set;}
        
        public PaymentMethods(List<Payment_Method__c> lstMethods, Payment_Method__c  imprtantNotes, Payment_Method__c  chquesNotes, Payment_Method__c footer){
            this.lstMethods = lstMethods;
            this.imprtantNotes = imprtantNotes;
            this.chequesNotes = chequesNotes;
            this.footer = footer;
        }
    }
    public class HeaderFooter{
        public String imageId{get; set;}
        public String text{get; set;}
        public HeaderFooter(String imageId, String text){
            this.imageId = imageId;
            this.text = text;
        }
    }
    
}