Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Client_Payment__c.object
<CustomObject>
    <fields>
        <fullName>CP_Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CP_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Payments</relationshipLabel>
        <relationshipName>Client_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CP_Payee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Client_Group__c.CG_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.CP_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Client Payments</relationshipLabel>
        <relationshipName>Client_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CP_Processed_On__c</fullName>
        <label>Processed On</label>
        <type>Date</type>
    </fields>
    <label>Client Payment</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Client Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Client_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Group</label>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Lead_Passenger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Passenger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/ClientPaymentsControllerTest.cls
/************************************************
** Module Name : ClientPaymentsControllerTest
** Description : Testing various operations of client payment
** Calls : TestServices
** Test Class : <Name of the test class that is used test this class>
** 
** Organization : Sugati
**
** Revision History:-
** Version    Date          Author          WO#     Description of Action
** 1.0        2-8-2016      Suraj Tripathi  NA      <NNNN>  Initial Version
** 1.0        2-25-2016     Naval Sharma    NA      Fixed the test methods which was written with wrong approach
************************************************/
@isTest
private class ClientPaymentsControllerTest {
     public static testMethod Void testMyController2(){
          
          test.startTest();
          List<Account>AccList=new List<Account>();
          Account Acc=new Account();
          Acc.Name='Test2';
          AccList.add(Acc);
          insert Acc;
          
          List<Contact>ConList=new List<Contact>();
          Contact Con=new Contact();
          Con.LastName='Con2';
          Con.CurrencyIsoCode='GBP';
          Con.AccountId=Acc.Id;
          con.Email = 'test@test.com';
          ConList.add(Con);
          insert ConList;
          
         
          List<Opportunity> oppList=new List<Opportunity>();
          Opportunity opp=new Opportunity();
          opp.name='opp1';
          opp.StageName='Enquiry';
          opp.CloseDate=system.today()+4;
          opp.AccountId=Acc.Id;
          opp.CurrencyIsoCode='GBP';
          oppList.add(opp);
          insert oppList;
         
          List<Client_Group__c> cgList = TestServices.createClientGroupRecords(2, oppList[0].Id);   
          Group_Member__c gm = new Group_Member__c(GM_Opportunity__c = oppList[0].Id, GM_Client_Group__c = cgList[0].Id, GM_Contact__c = con.Id, GM_Lead_Passenger__c = true);
          insert gm;
          List<Client_Payment__c> clList = new List<Client_Payment__c>();
          Client_Payment__c cl = new Client_Payment__c();
          cl.CP_Opportunity__c = oppList[0].Id;
          cl.CP_Amount__c = 100.00; 
          cl.CP_Processed_On__c = System.today();
          cl.CP_Payee__c = cgList[0].Id;
          clList.add(cl);
          insert cl;
          
          String oppId = oppList[0].Id;
          String CPJSON = JSON.serialize(cl);
         
          ApexPages.StandardController sc = new ApexPages.StandardController(opp);
          ClientPaymentsController ClientPay = new ClientPaymentsController(sc);
          ClientPay.getPickListValues();
          ClientPaymentsController.getClientPayments (oppId);
          ClientPaymentsController.saveClientPayment(CPJSON);
          cl.CP_Amount__c = null; 
          CPJSON = JSON.serialize(cl);
          ClientPaymentsController.saveClientPayment(CPJSON);
          ClientPay.getPageMessage();
     }

}