Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <fields>
        <fullName>CG_Arrival_Presents__c</fullName>
        <label>Arrival Presents</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CG_Charity__c</fullName>
        <label>Charity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CG_Exchange_Rate_GBP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exchange Rate GBP</label>
        <referenceTo>Exchange_Rate__c</referenceTo>
        <relationshipLabel>Client Groups</relationshipLabel>
        <relationshipName>Client_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CG_FX_Transfer_Charges__c</fullName>
        <label>FX Transfer Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CG_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Groups</relationshipLabel>
        <relationshipName>Client_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CG_Regulatory_Charges__c</fullName>
        <label>Regulatory Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CG_Selling_Price__c</fullName>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Exchange_Rate__c.object
<CustomObject>
    <fields>
        <fullName>ER_Base_Currency__c</fullName>
        <inlineHelpText>Foreign Currency</inlineHelpText>
        <label>Foreign Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FJD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HKD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JOD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MYR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PGK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QAR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ZAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ER_Book_From__c</fullName>
        <description>Booking Date From</description>
        <inlineHelpText>Booking Date From</inlineHelpText>
        <label>Book From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ER_Book_To__c</fullName>
        <label>Book To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ER_Exchange_Rate__c</fullName>
        <label>Exchange Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ER_Sales_Currency__c</fullName>
        <label>Sales Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ER_Travel_From__c</fullName>
        <label>Travel From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ER_Travel_To__c</fullName>
        <label>Travel To</label>
        <type>Date</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>ER-{00000000}</displayFormat>
        <label>Exchange Rate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <recordTypes>
        <fullName>Sell</fullName>
        <active>true</active>
        <label>Sell</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Booking_Currency__c</fullName>
        <label>Booking Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Booking_Number__c</fullName>
        <description>This is the field from the old system.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the field from the old system.</inlineHelpText>
        <label>Dhruv Booking No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Quote_No__c</fullName>
        <externalId>true</externalId>
        <label>Dhruv Quote No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Reference_Number__c</fullName>
        <label>Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>O_Total_Payment__c</fullName>
        <label>Total Payment Received</label>
        <summarizedField>Client_Payment__c.CP_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Client_Payment__c.CP_Processed_On__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Client_Payment__c.CP_Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Cost__c.object
<CustomObject>
    <description>Supplier Cost</description>
    <fields>
        <fullName>SC_Client_Group__c</fullName>
        <label>Client Group</label>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Supplier Costs</relationshipLabel>
        <relationshipName>Supplier_Costs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Supplier Cost</label>
    <nameField>
        <displayFormat>SBC-{0000000000}</displayFormat>
        <label>Supplier Cost ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Exchange_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exchange Rate</label>
        <referenceTo>Exchange_Rate__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/RefreshOpportunity.cls
public with sharing class RefreshOpportunity{
    public string oppId{get;set;}
    public Opportunity opp{get;set;}
    public String countries {get; set;}
    public String ExchangeRate{get; set;}
    
    private String oldBookingCurrency = 'GBP';
    private list<Client_Group__c> lstCG = new List<Client_Group__c>();
    
    
    public RefreshOpportunity(Apexpages.standardController controller) {
        try{
            oppId = controller.getId();
            countries = '';
            ExchangeRate = '1';
            
            if (oppId != null) {
                Opp();
                Integer i=1;
                for(Travelling_Country__c tc : Opp.Travelling_Countries__r){
                    if(i != Opp.Travelling_Countries__r.size())    
                        countries += tc.TC_Country__r.name+', ';
                    else
                        countries += tc.TC_Country__r.name;
                i++;
                }
            }
        }
        Catch(Exception e){
            ApexPages.addMessages(e);
        }
    }
    private void Opp(){
        opp = [select id,Owner.Name,Name,Account.Name,Amount,O_Total_Payment__c,CurrencyIsoCode,O_Booking_Currency__c,CreatedDate,StageName, 
                (Select Id,CG_Selling_Price__c,Name,CG_Charity__c,CG_Arrival_Presents__c,CG_Regulatory_Charges__c,CG_FX_Transfer_Charges__c 
                  from  Client_Groups__r), O_Departure_Date__c,O_Reference_Number__c , O_Quote_No__c, O_Booking_Number__c from Opportunity where id =: oppId];
            oldBookingCurrency = opp.currencyISOCode;
    }
    
    public void calculate(){
        
        if(opp.StageName != 'Booked' && opp.StageName != 'Booking Optional' && opp.Amount != null ){
            lstCG = new List<Client_Group__c>();
            String newCurrency = opp.CurrencyIsoCode;
            Opp();
            opp.CurrencyIsoCode = newCurrency;
            Map<String,Exchange_Rate__c> childExr = new Map<String,Exchange_Rate__c>();
            for(Exchange_Rate__c er : [Select id, ER_Base_Currency__c, ER_Book_From__c, ER_Book_To__c, ER_Exchange_Rate__c, ER_Sales_Currency__c, 
                                      ER_Travel_From__c, ER_Travel_To__c from Exchange_Rate__c where recordType.Name = 'Sell' and ER_Sales_Currency__c= :newCurrency]){
                if(opp.CreatedDate >= er.ER_Book_From__c && opp.CreatedDate <= er.ER_Book_To__c && opp.O_Departure_Date__c >= er.ER_Travel_From__c &&
                  opp.O_Departure_Date__c <= er.ER_Travel_To__c){
                      childExr.put(er.ER_Base_Currency__c,er);    
                }
            }
            if(childExr.containsKey(oldBookingCurrency)){
                opp.O_Booking_Currency__c = Opp.CurrencyIsoCode;
                ExchangeRate = ''+(childExr.get(oldBookingCurrency).ER_Exchange_Rate__c).setScale(4, RoundingMode.HALF_UP);
                Decimal totalAdditional = 0;
                for(Client_Group__c cg : opp.Client_Groups__r){
                    cg.CG_Selling_Price__c = (cg.CG_Selling_Price__c/childExr.get(oldBookingCurrency).ER_Exchange_Rate__c).setScale(2, RoundingMode.HALF_UP);
                    lstCG.add(cg);
                }
                opp.Amount = (opp.Amount/childExr.get(oldBookingCurrency).ER_Exchange_Rate__c).setScale(2, RoundingMode.HALF_UP);    
                    
            }
            
        }
        if(opp.StageName == 'Booked' || opp.StageName == 'Booking Optional'){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Can\'t refresh rates on Bookings'));    
        }
        
    } 
    public void save(){
        if(opp.StageName != 'Booked' && opp.StageName != 'Booking Optional'){
            upsert lstCG;
            upsert opp;
            List<Supplier_Cost__c> lstSC = [Select Id from Supplier_Cost__c where SC_Client_Group__c in : opp.Client_Groups__r];
            
            update lstSC;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Opportunity updated'));
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Can\'t refresh rates on Bookings'));
        }
    }   
}