Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Client_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Group</label>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Lead_Passenger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Passenger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    
    
    <fields>
        <fullName>O_Ts_Cs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Terms &amp; Conditions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pipeline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Pipeline</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Payment_Log__c.object
<CustomObject>
    <fields>
        <fullName>PL_Card_Token__c</fullName>
        <label>Card_Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PL_Card_Type__c</fullName>
        <label>Card_Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PL_Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PL_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PL_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payment Logs</relationshipLabel>
        <relationshipName>Payment_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PL_Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Payment Log</label>
    <nameField>
        <displayFormat>PL-{0000000}</displayFormat>
        <label>Payment Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/ProcessPaymentsControllerTest.cls
@isTest
public with sharing class ProcessPaymentsControllerTest{
    
    /*** Test case for successful payment ****/
    public static testMethod void uniTest1(){
        Account acc =new Account(name ='Test Account Checkout');
        insert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='clone@abc.com',AccountId=acc.id);
        insert con;
        
        Opportunity opp = new Opportunity(name = 'Test opp checkout',accountId = acc.id,CloseDate = date.today(),stageName = 'Closed Won',
                                        Amount = 1559,CurrencyISOCode = 'GBP' ,pipeline__c = false,O_Departure_Date__c = date.today(),
                                         O_Ts_Cs__c = false);
        insert opp;
        List<Client_Group__c> clientGroups = TestServices.createClientGroupRecords(2, opp.Id);
        
        Group_Member__c gm = new Group_Member__c(GM_Contact__c =con.id, GM_Client_Group__c = clientGroups[0].Id, GM_Lead_Passenger__c =true,GM_Opportunity__c = opp.id);
        insert gm; 
        
        Payment_Log__c pl = new Payment_Log__c(PL_Opportunity__c = opp.id, PL_Description__c ='hiiiii',PL_Payment_Amount__c = 123.00,PL_Currency_Code__c = 'GBP',
                                             PL_Card_Token__c='2345',PL_Card_Type__c ='Visa');
        insert pl;                                        
        System.assertNotEquals(pl.id, NULL);
        Test.setCurrentPage(Page.ProcessPayments);
        ApexPages.currentPage().getParameters().put('id', pl.id);
        ApexPages.currentPage().getParameters().put('name', 'test%20user');
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new CheckoutMockChargeSuccess());
        ProcessPaymentsController ppc = new  ProcessPaymentsController();
        ppc.processing();
    }
    
    
    /*** Test case for api error ****/
    public static testMethod void uniTest3(){
        Account acc =new Account(name ='Test Account Checkout');
        insert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='clone@abc.com',AccountId=acc.id);
        insert con;
        
        Opportunity opp = new Opportunity(name = 'Test opp checkout',accountId = acc.id,CloseDate = date.today(),stageName = 'Closed Won',
                                        Amount = 1559,CurrencyISOCode = 'GBP' ,pipeline__c = false,O_Departure_Date__c = date.today(),
                                         O_Ts_Cs__c = false);
        insert opp;
        
        List<Client_Group__c> clientGroups = TestServices.createClientGroupRecords(2, opp.Id);
        
        Group_Member__c gm = new Group_Member__c(GM_Contact__c =con.id, GM_Client_Group__c = clientGroups[0].Id, GM_Lead_Passenger__c =true,GM_Opportunity__c = opp.id);
        insert gm; 
        
        
        Payment_Log__c pl = new Payment_Log__c(PL_Opportunity__c = opp.id,PL_Description__c ='hiiiii',PL_Payment_Amount__c = 123.00,PL_Currency_Code__c = 'GBP',
                                             PL_Card_Token__c='2345',PL_Card_Type__c ='Visa');
        insert pl;                                        
        System.assertNotEquals(pl.id, NULL);
        
        Test.setCurrentPage(Page.ProcessPayments);
        ApexPages.currentPage().getParameters().put('id', pl.id);
        ApexPages.currentPage().getParameters().put('name', 'test%20user');
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new CheckoutMockChargeAPIError());
        ProcessPaymentsController ppc = new  ProcessPaymentsController();
        ppc.processing();
    }
    
    /*** Test case for payment error ****/
    public static testMethod void uniTest4(){
        Account acc =new Account(name ='Test Account Checkout');
        insert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='clone@abc.com',AccountId=acc.id);
        insert con;
        
        Opportunity opp = new Opportunity(name = 'Test opp checkout',accountId = acc.id,CloseDate = date.today(),stageName = 'Closed Won',
                                        Amount = 1559,CurrencyISOCode = 'GBP' ,pipeline__c = false,O_Departure_Date__c = date.today(),
                                         O_Ts_Cs__c = false);
        insert opp;
        
        List<Client_Group__c> clientGroups = TestServices.createClientGroupRecords(2, opp.Id);
        
        Group_Member__c gm = new Group_Member__c(GM_Contact__c =con.id, GM_Client_Group__c = clientGroups[0].Id, GM_Lead_Passenger__c =true,GM_Opportunity__c = opp.id);
        insert gm;  
        
        Payment_Log__c pl = new Payment_Log__c(PL_Opportunity__c = opp.id,PL_Description__c ='hiiiii',PL_Payment_Amount__c = 123.00,PL_Currency_Code__c = 'GBP',
                                             PL_Card_Token__c='2345',PL_Card_Type__c ='Visa');
        insert pl;                                        
        System.assertNotEquals(pl.id, NULL);
        
        Test.setCurrentPage(Page.ProcessPayments);
        ApexPages.currentPage().getParameters().put('id', pl.id);
        ApexPages.currentPage().getParameters().put('name', 'test%20user');
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new CheckoutMockChargeFail());
        ProcessPaymentsController ppc = new  ProcessPaymentsController();
        ppc.processing();
    }
    
    /*** Test case for failed payment ****/
    public static testMethod void uniTest2(){
        Account acc =new Account(name ='Test Account Checkout');
        insert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='clone@abc.com',AccountId=acc.id);
        insert con;
        
        Opportunity opp = new Opportunity(name = 'Test opp checkout',accountId = acc.id,CloseDate = date.today(),stageName = 'Closed Won',
                                        Amount = 1559,CurrencyISOCode = 'GBP' ,pipeline__c = false,O_Departure_Date__c = date.today(),
                                         O_Ts_Cs__c = false);
        insert opp;
        
        List<Client_Group__c> clientGroups = TestServices.createClientGroupRecords(2, opp.Id);
        
        Group_Member__c gm = new Group_Member__c(GM_Contact__c =con.id, GM_Client_Group__c = clientGroups[0].Id, GM_Lead_Passenger__c =true,GM_Opportunity__c = opp.id);
        insert gm; 
        
        Payment_Log__c pl = new Payment_Log__c(PL_Opportunity__c = opp.id,PL_Description__c ='hiiiii',PL_Payment_Amount__c = 123.00,PL_Currency_Code__c = 'GBP',
                                             PL_Card_Token__c='2345',PL_Card_Type__c ='Visa');
        insert pl;                                        
        System.assertNotEquals(pl.id, NULL);
        
        Test.setCurrentPage(Page.ProcessPayments);
        ApexPages.currentPage().getParameters().put('id', pl.id);
        ApexPages.currentPage().getParameters().put('name', 'test%20user');
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new CheckoutMockChargePaymentError());
        ProcessPaymentsController ppc = new  ProcessPaymentsController();
        ppc.processing();
        
        ApexPages.currentPage().getParameters().put('id', '');
        ApexPages.currentPage().getParameters().put('name', '');
        ppc = new  ProcessPaymentsController();
        ppc.processing();
        Test.StopTest();
    }
}