Sugati/src/objects/Client_Group__c.object
<CustomObject>
    <fields>
        <fullName>CG_Exchange_Rate_GBP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exchange Rate GBP</label>
        <referenceTo>Exchange_Rate__c</referenceTo>
        <relationshipLabel>Client Groups</relationshipLabel>
        <relationshipName>Client_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CG_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Groups</relationshipLabel>
        <relationshipName>Client_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Group</label>
    <nameField>
        <label>Client Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Client_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>CI_Client_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Client_Group__c.CG_Opportunity__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.I_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Client Invoices</relationshipLabel>
        <relationshipName>Client_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CI_Client_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this is a credit note, this field must be filled in.</description>
        <inlineHelpText>If this is a credit note, this field must be filled in.</inlineHelpText>
        <label>Client Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Client_Invoice__c.I_Opportunity__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.I_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Client_Invoice__c</referenceTo>
        <relationshipLabel>Client Invoices</relationshipLabel>
        <relationshipName>Client_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CI_Payment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Client Invoices</relationshipLabel>
        <relationshipName>Client_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>I_Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>I_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Invoices</relationshipLabel>
        <relationshipName>Client_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Client Invoice No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Invoices</pluralLabel>
    <recordTypes>
        <fullName>Committed</fullName>
        <active>true</active>
        <description>Committed Invoice</description>
        <label>Committed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <description>Deposit</description>
        <label>Deposit</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Client_Payment__c.object
<CustomObject>
    <fields>
        <fullName>CP_Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CP_Client_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Client_Invoice__c.I_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.CP_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Client_Invoice__c</referenceTo>
        <relationshipLabel>Client Payments</relationshipLabel>
        <relationshipName>Client_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CP_Credit_Memo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Memo</label>
        <referenceTo>Credit_Memo__c</referenceTo>
        <relationshipLabel>Client Payments</relationshipLabel>
        <relationshipName>Client_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CP_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Client Payments</relationshipLabel>
        <relationshipName>Client_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CP_Payee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payee</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Client_Group__c.CG_Opportunity__c</field>
                <operation>equals</operation>
                <valueField>$Source.CP_Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Client Payments</relationshipLabel>
        <relationshipName>Client_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CP_Payment_Method_C__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card - Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card - Amex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card - Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Memo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CP_Processed_On__c</fullName>
        <label>Processed On</label>
        <type>Date</type>
    </fields>
    <label>Client Payment</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Client Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Credit_Memo__c.object
<CustomObject>
    <fields>
        <fullName>CM_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CM_Credit_Expiry_Date__c</fullName>
        <label>Credit Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CM_Exchange_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exchange Rate</label>
        <referenceTo>Exchange_Rate__c</referenceTo>
        <relationshipLabel>Credit Memos</relationshipLabel>
        <relationshipName>Credit_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Memos</relationshipLabel>
        <relationshipName>Credit_Memos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CM_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Compensation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Credit Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Exchange_Rate__c.object
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <displayFormat>ER-{00000000}</displayFormat>
        <label>Exchange Rate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Booking_to_Departure__c</fullName>
        <formula>O_Departure_Date__c -  O_Booking_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Booking to Departure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Rule__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>R_Days_to_Departure_From__c</fullName>
        <label>Days to Departure From</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>R_Days_to_Departure_To__c</fullName>
        <label>Days to Departure To</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>R_Deposit_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deposit Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>R_Percentage__c</fullName>
        <label>% of total booking price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>R_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Rules</relationshipLabel>
        <relationshipName>Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <recordTypes>
        <fullName>Client_Payment</fullName>
        <active>true</active>
        <label>Client Payment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Site__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Run_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Run Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
</CustomObject>

Sugati/src/classes/ClientPaymentTriggers.cls
public with sharing Class ClientPaymentTriggers{

    public ClientPaymentTriggers(){
        
    }
    
    public static void ClientPaymentTriggerBefore(){
        if(Site__c.getInstance().Run_Trigger__c){
            Savepoint sp = Database.setSavepoint();
            try{
                List<String> lstOpps = new List<String>();
                //List<String> lstCMIds = new List<String>();
                Map<String,Client_Payment__c> mapClientPayments = new Map<String,Client_Payment__c>();
                for(Client_Payment__c cp : (List<Client_Payment__c>)trigger.new){
                    if(cp.CP_Processed_On__c != null){
                        lstOpps.add(cp.CP_Opportunity__c);
                       // lstCMIds.add(cp.CP_Credit_Memo__c);
                        if(!mapClientPayments.containsKey(cp.CP_Opportunity__c)){
                            mapClientPayments.put(cp.CP_Opportunity__c, cp);
                        }
                    }    
                }
                Map<String, Map<String,Exchange_Rate__c>> mapExchangeRates = Utility.getExchangeRates(lstOpps);
                /*Map<String,Credit_Memo__c> mapPositiveCM = new Map<String,Credit_Memo__c>();
                for(Credit_Memo__c cm : [Select Id, CM_Credit_Expiry_Date__c from Credit_Memo__c where Id in :lstCMIds]){
                    mapPositiveCM.put(cm.Id,cm);
                }*/
                lstOpps = new List<String>();
                List<Opportunity> lstOppsToUpdate = new List<Opportunity>();
               // List<Credit_Memo__c> lstCms = new List<Credit_Memo__c>();
                List<String> lstOppsForInvoice = new List<String>();
                
               
                for(Client_Payment__c cp : (List<Client_Payment__c>)trigger.new){
                    if(cp.CP_Processed_On__c != null){
                        lstOpps.add(cp.CP_Opportunity__c);
                        /*
                        if(mapExchangeRates.containsKey(cp.CP_Opportunity__c) && cp.CP_Credit_Memo__c!= null && mapPositiveCM.containsKey(cp.CP_Credit_Memo__c)){
                            if(trigger.isInsert){
                                //Credit Memo
                                if(cp.CP_Payment_Method_C__c == 'Credit Memo' && cp.CP_Credit_Memo__c != null){
                                    lstCms.add(new Credit_Memo__c(CM_Credit_Expiry_Date__c = mapPositiveCM.get(cp.CP_Credit_Memo__c).CM_Credit_Expiry_Date__c,CM_Opportunity__c = cp.CP_Opportunity__c,CM_Exchange_Rate__c = mapExchangeRates.get(cp.CP_Opportunity__c).get('GBP').Id,  CM_Amount__c = -cp.CP_Amount__c, CM_Type__c = 'Promotion'));
                                }
                            }
                            else if(trigger.isUpdate){
                                if(cp.CP_Processed_On__c != ((Client_Payment__c)Trigger.oldMap.get(cp.Id)).CP_Processed_On__c && cp.CP_Payment_Method_C__c == 'Credit Memo' && cp.CP_Credit_Memo__c != null){
                                    lstCms.add(new Credit_Memo__c(CM_Credit_Expiry_Date__c = mapPositiveCM.get(cp.CP_Credit_Memo__c).CM_Credit_Expiry_Date__c,CM_Opportunity__c = cp.CP_Opportunity__c, CM_Exchange_Rate__c = mapExchangeRates.get(cp.CP_Opportunity__c).get('GBP').Id,  CM_Amount__c = -cp.CP_Amount__c, CM_Type__c = 'Promotion'));
                                }    
                            }                        
                        }*/
                    }
                }
                
                //insert lstCms;
                Map<String,Client_Invoice__c> mapAlreadyExistedInvoices = new Map<String,Client_Invoice__c>();
                for(Client_Invoice__c cin : [Select Id,CI_Client_Group__c from Client_Invoice__c where I_Opportunity__c = :lstOpps]){
                    mapAlreadyExistedInvoices.put(cin.CI_Client_Group__c, cin);
                }
                for(Opportunity opp : [Select Id,StageName,(Select Id,CI_Client_Group__c from Client_Invoices__r),(Select Id from Client_Groups__r),O_Booking_to_Departure__c from Opportunity where 
                                        Id in :lstOpps]){
                    if(opp.StageName != 'Booked'){
                        opp.stageName = 'Booked';
                        opp.O_Booking_Date__c  = System.today();
                        lstOppsToUpdate.add(opp);
                        Boolean present = false;
                        for(Client_Invoice__c CI : opp.Client_Invoices__r){
                            if(mapClientPayments.get(opp.Id).CP_Payee__c == CI.CI_Client_Group__c){
                                present = true;
                            }
                        }
                        if(!present){
                            lstOppsForInvoice.add(opp.Id);
                        }
                    }
                    else{
                        if(opp.Client_Groups__r.size() > opp.Client_Invoices__r.Size()){
                            lstOppsForInvoice.add(opp.Id);
                        }    
                    }
                    
                }
                Update lstOppsToUpdate;
               
                if(lstOppsForInvoice.size() > 0){
                    //Map Rule with Opportunity
                    List<Rule__c> lstRules = [Select Id,R_Percentage__c,R_Days_to_Departure_From__c,R_Days_to_Departure_To__c,
                                             R_Deposit_Only__c,R_Supplier__c from Rule__c where RecordType.DeveloperName = 'Client_Payment' and Is_Active__c = true];
                    Map<String,List<Rule__c>> mapRuleWithOpp = new Map<String,List<Rule__c>>();
                    Map<String,String> mapRecordType = new Map<String,String>();
                    Map<String,Rule__c> mapRuleToSaveCP = new Map<String,Rule__c>();
                    
                    for(RecordType rt : [Select Id,DeveloperName from RecordType where SOBjectType = :Utility.getNameSpacePrefix()+'Client_Invoice__c']){
                        mapRecordType.put(rt.DeveloperName, rt.Id);
                    }
                    
                    for(Opportunity opp : [Select Id,O_Booking_to_Departure__c from Opportunity where Id in :lstOppsForInvoice]){
                        if(!mapRuleWithOpp.containsKey(opp.Id)){
                            mapRuleWithOpp.put(opp.Id, new List<Rule__c>());
                        }
                        for(Rule__c r : lstRules){
                            if(r.R_Days_to_Departure_From__c < opp.O_Booking_to_Departure__c){
                                mapRuleWithOpp.get(opp.Id).add(r);
                            }
                            if(r.R_Days_to_Departure_From__c < opp.O_Booking_to_Departure__c && r.R_Days_to_Departure_To__c > opp.O_Booking_to_Departure__c){
                                mapRuleToSaveCP.put(opp.Id,r);    
                            }
                        }
                    }
                    
                    //Create Invoice records
                    List<Client_Invoice__c> lstClientInvoice = new List<Client_Invoice__c>();
                    Map<String,String> mapClientInvoiceCP = new map<String,String>();
                    
                    for(String oppId : mapRuleWithOpp.keySet()){
                        for(Rule__c r : mapRuleWithOpp.get(oppId)){
                            
                            if(r.R_Deposit_Only__c && mapRecordType.containsKey('Deposit')){
                                Client_Invoice__c cInv = new Client_Invoice__c(I_Opportunity__c = oppId, recordTypeId = mapRecordType.get('Deposit'),
                                                     I_Invoice_Date__c = system.today(), CI_Payment_Rule__c  = r.Id);
                                if(mapClientPayments.containsKey(oppId)){
                                    cInv.CI_Client_Group__c = mapClientPayments.get(oppId).CP_Payee__c;
                                }
                                if(!mapAlreadyExistedInvoices.containsKey(cInv.CI_Client_Group__c)){                 
                                    lstClientInvoice.add(cInv);
                                }
                            }
                            if(!r.R_Deposit_Only__c && mapRecordType.containsKey('Committed')){
                                Client_Invoice__c cInv = new Client_Invoice__c(I_Opportunity__c = oppId, recordTypeId = mapRecordType.get('Committed'),
                                                     I_Invoice_Date__c = system.today(), CI_Payment_Rule__c  = r.Id);
                                if(mapClientPayments.containsKey(oppId)){
                                    cInv.CI_Client_Group__c = mapClientPayments.get(oppId).CP_Payee__c;
                                }  
                                if(!mapAlreadyExistedInvoices.containsKey(cInv.CI_Client_Group__c)){                                
                                    lstClientInvoice.add(cInv);
                                }
                            }
                            
                        }
                    }
                    
                    insert lstClientInvoice;
                    
                    List<Client_Payment__c> lstCP = new List<Client_Payment__c>();
                    for(Client_Payment__c cp : (List<Client_Payment__c>)trigger.new){
                        for(Client_Invoice__c CI : lstClientInvoice){
                            if(mapRuleToSaveCP.containsKey(CI.I_Opportunity__c) && mapRuleToSaveCP.get(CI.I_Opportunity__c).Id == CI.CI_Payment_Rule__c){
                                    cp.CP_Client_Invoice__c = CI.Id;
                                    lstCP.add(cp);
                            }   
                        }
                    }
                    //update lstCP;
                }    
            }
            Catch(Exception e){
                Database.rollback(sp);    
                System.assert(false,e.getMessage());
            }
        }
    }
    
    public static void ClientPaymentTriggerAfter(){
        if(Site__c.getInstance().Run_Trigger__c){
            
            
        }
    }
}