Sugati/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>C_Lead_Passenger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Passenger</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Client_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Group</label>
        <referenceTo>Client_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Lead_Passenger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lead Passenger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Booking_Number__c</fullName>
        <description>This is the field from the old system.</description>
        <externalId>true</externalId>
        <inlineHelpText>This is the field from the old system.</inlineHelpText>
        <label>Dhruv Booking No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Deposit_Required1__c</fullName>
        <label>Deposit Required</label>
        <summarizedField>Client_Group__c.CG_Deposit_Required_I__c</summarizedField>
        <summaryForeignKey>Client_Group__c.CG_Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Insurance_Company__c</fullName>
        <label>Insurance Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Outstanding__c</fullName>
        <formula>Amount - O_Total_Payment_Without_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>O_Quote_No__c</fullName>
        <externalId>true</externalId>
        <label>Dhruv Quote No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Reference_Number__c</fullName>
        <label>Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>O_Total_Payment1__c</fullName>
        <formula>O_Total_Payment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Payment with CC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Total_Payment_Without_CC__c</fullName>
        <label>Total Payment Without CC</label>
        <summarizedField>Client_Payment__c.CP_Receipt_AmountEx__c</summarizedField>
        <summaryFilterItems>
            <field>Client_Payment__c.CP_Processed_On__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Client_Payment__c.CP_Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Cover_Image__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cover Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TC_ImageID__c</fullName>
        <label>ImageID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Selected__c</fullName>
        <inlineHelpText>When was the cover selected?</inlineHelpText>
        <label>Selected</label>
        <type>DateTime</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/BookingDetailsController.cls
public without sharing class BookingDetailsController {

    public string oppId{get;set;}
    public Opportunity opp{get;set;}
    public String countries {get; set;}
    public contact leadGuest{get; set;}
    public List<contact> otherGuests{get; set;}
    public Boolean daysToDeparture{get; set;}
    public Decimal paymentDue{get; set;}
    /* changes----*/
    public Id cgid{get;set;}
    
    List<String> conIds = new List<String>();
    public BookingDetailsController() {
        try {
            cgid = apexpages.currentpage().getparameters().get('cgid');  
            oppId = Apexpages.currentPage().getParameters().get('id');
            System.debug(Apexpages.currentPage().getParameters().get('id'));
            countries = '';
            if (oppId != null) {
                List<Opportunity> opps= [select id,O_Deposit_Required1__c,O_Total_Payment_Without_CC__c,O_Booking_Date__c,O_Total_Payment1__c,currencyISOCode,AccountID,Owner.Name,Name,Amount,O_Outstanding__c,O_Insurance_Company__c,
                (Select Id,TC_Country__r.name from  Travelling_Countries__r), (Select ID, GM_Contact__c,GM_Lead_Passenger__c from Group_Members__r),O_Departure_Date__c,O_Reference_Number__c , O_Quote_No__c, O_Booking_Number__c from Opportunity where id =: oppId];
                if (opps.size() > 0) {
                    opp = opps[0];
                    Date d1 = (Opp.O_Departure_Date__c).addDays(70);
                    If(Opp.O_Booking_Date__c > d1){
                        daysToDeparture = true;
                        paymentDue = opp.O_Deposit_Required1__c-opp.O_Total_Payment_Without_CC__c;
                    }
                    else{
                        daysToDeparture = false;
                        if(opp.Amount != null && opp.O_Total_Payment_Without_CC__c != null)
                            paymentDue = opp.Amount-opp.O_Total_Payment_Without_CC__c;
                        else
                         paymentDue = 0;
                    }
                    Integer i=1;
                    for(Travelling_Country__c tc : Opp.Travelling_Countries__r){
                        if(i != Opp.Travelling_Countries__r.size())    
                            countries += tc.TC_Country__r.name+', ';
                        else
                            countries += tc.TC_Country__r.name;
                    i++;
                    }
                    for(Group_Member__c gm : opp.Group_Members__r){
                        conIds.add(gm.GM_Contact__c);
                    }
                }
            }
            guests();
        }
        Catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()+'--'+e.getStackTraceString()));
            //throw e;
        }
        
        
    }
    
    public String getFileId() {
        String CoverImg;
        //String fileId = '';
        List<Travelling_Country__c> lstTC = [select TC_ImageID__c,TC_Cover_Image__c  from Travelling_Country__c
                 where TC_Opportunity__r.Id= :oppId
                 AND TC_Selected__c != NULL 
                 AND TC_ImageID__c!= NULL 
                 //AND TC_Cover_Image__c = true
                Order by TC_Selected__c desc
                ];
                  //Name ='Cover.png' AND ParentId = :Opp.o_country__r.id];
          if(lstTC.size()>0) {
              if (lstTC[0].TC_Cover_Image__c) {
                  CoverImg = lstTC[0].TC_ImageID__c;
              }
          }
       
        
        return CoverImg;   
     }

     void guests(){
         Set<Id> conIds = new Set<Id>();
         otherGuests = new List<Contact>();
         leadGuest = new Contact();
         String leadConId ;
         for(Group_Member__c gm : [SELECT Id, Name,GM_Contact__c,GM_Lead_Passenger__c from Group_Member__c where GM_Opportunity__c=:opp.Id AND GM_Client_Group__c=:cgid]){
             conIds.add(gm.GM_Contact__c);
             if(gm.GM_Lead_Passenger__c){
                 leadConId = gm.GM_Contact__c;
             }
         }
         
         For(Contact con: [Select Id,birthDate,salutation,FirstName,lastname,Phone,C_Lead_Passenger__c,Email,MailingStreet,MailingState,
                                    MailingPostalCode,MailingCountry,MailingCity,OtherStreet,OtherState,OtherCountry,OtherPostalCode  
                           from Contact where Id in :conIds  order by createdDate]){ 
            if(con.Id == leadConId){
                leadGuest = con;
            }
            else{
                otherGuests.add(con);
            }    
        }
     }
    
}