Sugati/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>C_Full_Name_on_Passport__c</fullName>
        <label>Full Name on Passport</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Age__c</fullName>
        <label>Age</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GM_First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GM_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GM_Salutation__c</fullName>
        <label>Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>Mr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_ATOL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ATOL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>O_Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Infant__c</fullName>
        <label>Infant</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Infant</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_No_of_Nights__c</fullName>
        <formula>O_Return_Date__c -  O_Departure_Date__c</formula>
        <label>No of Nights</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Pax__c</fullName>
        <formula>IF(O_Is_Group_Booking__c,IF(Adult_Old__c &gt; 0, Adult_Old__c, O_Adult__c) + IF( O_Child_Old__c  &gt; 0, O_Child_Old__c, O_Children__c) + IF(  O_Infant_Old__c   &gt; 0, O_Infant_Old__c, O_Infant__c)-3,IF(Adult_Old__c &gt; 0, Adult_Old__c, O_Adult__c) + IF( O_Child_Old__c  &gt; 0, O_Child_Old__c, O_Children__c) + IF(  O_Infant_Old__c   &gt; 0, O_Infant_Old__c, O_Infant__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pax</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Reference_Number__c</fullName>
        <label>Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_Arrival_Airport_l__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Arrival Airport</label>
        <referenceTo>Airport__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SB_Check_In_Time__c</fullName>
        <label>Check In Time</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SB_Departure_Airport_l__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Departure Airport</label>
        <referenceTo>Airport__c</referenceTo>
        <relationshipLabel>Supplier Booking (Departure Airport)</relationshipLabel>
        <relationshipName>Supplier_Booking1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SB_Departure_Time__c</fullName>
        <label>Departure Time</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SB_Flight_No__c</fullName>
        <label>Flight No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SB_From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SB_From_Time__c</fullName>
        <label>From Time</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SB_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SB_Pax_for_Costing__c</fullName>
        <label>Pax for Costing</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SB_To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SB_To_Time__c</fullName>
        <label>To Time</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/ATOLCertificate.cls
public without sharing class ATOLCertificate {

  public Opportunity CurrentOpportunity {get;set;}
  public List<Group_Member__c> listGM {get;set;}
  public List<FB> listFB {get;set;}
  Public List<TC> listTC {get;set;}
  
  public string Resort {get;set;}
  public string ResortLink {get;set;}
  public string ResortImage {get;set;}
 
  public string BackgroundImage {get;set;}
  public decimal NumberOfPessenger {get;set;}
  
  public ATOLCertificate(ApexPages.StandardController controller){
    Resort = '';
    ResortLink = '#';
    ResortImage = '';
    BackgroundImage = 'pbrbg.gif';
 
 
   // Opportunity Details
     if(ApexPages.CurrentPage().getParameters().get('id') != null){
        
        for(Opportunity opp : [Select Id, Amount,O_Infant__c, Name, O_ATOL__c, Account.Name,O_No_of_Nights__c,O_Pax__c,O_Reference_Number__c,O_Booking_Date__c
                               From Opportunity Where Id = : ApexPages.CurrentPage().getParameters().get('id') ]){
                                   
            CurrentOpportunity = opp;
            
            NumberOfPessenger = opp.O_Pax__c - opp.O_Infant__c;
                                   
        }
    }
      
      
    // List of Group Memember Records 
    listGM = new List<Group_Member__c>();
    listGM = [Select Id,GM_Salutation__c,GM_First_Name__c,GM_Last_Name__c,GM_Age__c,GM_DOB__c,GM_Contact__r.C_Full_Name_on_Passport__c
              From Group_Member__c Where GM_Opportunity__c = : CurrentOpportunity.Id 
              Order By  GM_DOB__c DESC,GM_Last_Name__c ASC, GM_First_Name__c ASC];
      
      

    // List of Flight Details From Supplier Booking Records
    listFB = new List<FB>();
    for(Supplier_Booking__c f : [Select Id,RecordType.Name,SB_Arrival_Airport_l__c,SB_Departure_Time__c,SB_Check_In_Time__c ,SB_Departure_Airport_l__c,SB_To_Date__c,SB_From_Date__c,SB_From_Time__c,
                                SB_To_Time__c,SB_Pax_for_Costing__c,SB_Flight_No__c
                                From Supplier_Booking__c 
                                Where SB_Opportunity__c = : CurrentOpportunity.Id AND 
                                RecordType.Name In ('Int Flight','Light Aircraft','Dom Flights')
                                Order by SB_From_Date__c])
    {
       FB fb = new FB();
       f.SB_Pax_for_Costing__c = ''+NumberOfPessenger;
       
       fb.FBooking = f;
        listFB.add(fb);
    }
      // List of Flight Details From Supplier Booking Records
    listTC = new List<TC>();
    for(Travelling_Country__c t : [Select Id,TC_Country__r.Name
                                From Travelling_Country__c 
                                Where TC_Opportunity__c = : CurrentOpportunity.Id ])
    {
       TC tc = new TC();
       tc.TCountry = t;
        listTC.add(tc);
    }
  
  }
   
     
    Public class FB{
        public Supplier_Booking__c FBooking {get;set;}
     }
    
    Public Class TC{
        Public Travelling_Country__c TCountry {get;set;}
    }
}