Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <fields>
        <fullName>C_EU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EU</label>
        <type>Checkbox</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Images_AI__c.object
<CustomObject>
    <fields>
        <fullName>AI_Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AI_Image_ID__c</fullName>
        <label>Image ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AI_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Images_AI</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Images AI</label>
    <nameField>
        <displayFormat>AI-{000000}</displayFormat>
        <label>Images AI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Images AI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Margin__c.object
<CustomObject>
    <fields>
        <fullName>M_Book_From__c</fullName>
        <label>Book From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>M_Book_To__c</fullName>
        <label>Book To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>M_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Margins</relationshipLabel>
        <relationshipName>Margins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>M_Margin__c</fullName>
        <label>Margin</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M_Travel_From__c</fullName>
        <label>Travel From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>M_Travel_To__c</fullName>
        <label>Travel To</label>
        <type>Date</type>
    </fields>
    <label>Margin</label>
    <nameField>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Margin ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_EU__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the holiday in EU country?</description>
        <inlineHelpText>Is the holiday in EU country?</inlineHelpText>
        <label>EU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>O_Suggested_Margin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suggested Margin</label>
        <referenceTo>Margin__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Target_Mark_Up_Value__c</fullName>
        <label>Target Mark Up Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Target_Mark_Up__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Mark-Up</label>
        <referenceTo>Target_Mark_Up__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SB_Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SB_Own_Arrangement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Own Arrangement</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Target_Mark_Up__c.object
<CustomObject>
    <fields>
        <fullName>TMU_APC__c</fullName>
        <description>Licencible /Not EU</description>
        <inlineHelpText>LIC, NOT TO EU</inlineHelpText>
        <label>APC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMU_FFP__c</fullName>
        <inlineHelpText>NON-LIC, NOT TO EU</inlineHelpText>
        <label>FFP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMU_TOMS_APC__c</fullName>
        <inlineHelpText>LIC, TRAVEL TO EU</inlineHelpText>
        <label>TOMS + APC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMU_TOMS_FFP__c</fullName>
        <inlineHelpText>NON-LIC, TRAVEL TO EU</inlineHelpText>
        <label>TOMS + FFP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TMU_Target_Margin__c</fullName>
        <label>Target Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Target Mark-Up</label>
    <nameField>
        <displayFormat>TM-{0000000}</displayFormat>
        <label>Target Margin ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Mark-Ups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>TC_Country__r.Name</formula>
        <label>Country Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(TC_Opportunity__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TC_Accommodation_Region__c</fullName>
        <label>Accommodation/Region</label>
        <picklist>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodation</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Cover_Image__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cover Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TC_DestinationMap_Image_ID__c</fullName>
        <label>DestinationMap Image ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TC_ImageID__c</fullName>
        <label>ImageID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Selected__c</fullName>
        <inlineHelpText>When was the cover selected?</inlineHelpText>
        <label>Selected</label>
        <type>DateTime</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/TravellingCountryTriggerHandler.cls
public with sharing class TravellingCountryTriggerHandler implements ITrigger{
    
    String imageId;
    String objectName;
    String marginString;
    String  country= '';
    Decimal oppMargin;
    
    boolean isIntFlight = false;
    
    Set<String> countries = new Set<String>();
    Set<String> oppIds = new Set<String>();
    Set<String> usrIds = new Set<String>();
    Set<String> setAttIds = new Set<String>();
    List<String> oppQueryId = new List<String>();

    List<Attachment> lstAtt  = new  List<Attachment>();
    List<Travelling_Country__c> travelCountriesList = new List<Travelling_Country__c>();
    List<Opportunity> lstOpp = new List<Opportunity>();
    List<String> travellingC = new List<String>(); 
    List<Travelling_Country__c> tcList = new List<Travelling_Country__c>();
    List<Images_AI__c> img = new List<Images_AI__c>();
    List<Opportunity> Opps = new  List<Opportunity>();
    List<Supplier_Booking__c> sbList = new List<Supplier_Booking__c>();
    List<Target_Mark_Up__c> tmuList = new List<Target_Mark_Up__c>();
    List<Recordtype> rtList= new List<Recordtype>();
    List<Margin__c> marginList = new List<Margin__c>();
    List<Margin__c> mg = new List<Margin__c>();
    
   
    Map<String, String> mapParentAttachment = new Map<String, String>();
    Map<String,List<Supplier_Booking__c>> mapOppSB = new Map<String,List<Supplier_Booking__c>>();
    Map<Decimal , Target_Mark_Up__c > mapTargetMarkUP = new Map<Decimal , Target_Mark_Up__c>();
    Map<String,String> mapRecordtype = new Map<String,String>();

    public TravellingCountryTriggerHandler(){
        objectName = Utility.getNameSpacePrefix()+'Supplier_Booking__c';
    }
    
    public void bulkBefore(Schema.sObjectType soType){
        lstAtt = [Select Id, ParentId, Name from Attachment where parentid in: countries AND name LIKE '%cover%' order by createdDate];
        tcList = [SELECT Id, TC_Accommodation_Region__c,Country_Name__c,TC_Cover_Image__c,TC_DestinationMap_Image_ID__c,TC_ImageID__c,TC_Selected__c,Stage__c,TC_Country__c,TC_Opportunity__c FROM Travelling_Country__c];
        sbList = [Select Id, recordTypeId,recordType.Name,SB_Own_Arrangement__c,SB_Opportunity__c  from Supplier_Booking__c
                   where SB_Opportunity__c in : oppIds order by SB_Order__c];
        tmuList = [Select Id, TMU_APC__c, TMU_FFP__c, TMU_TOMS_APC__c, TMU_TOMS_FFP__c, TMU_Target_Margin__c from Target_Mark_Up__c ] ; 
        rtList = [Select id,name,sobjecttype  from recordtype where sobjecttype = :objectName order by name];
        
        CheckingConditionOnDelete(); 
        beforeUpdateAndInsert();
        onDelete();
    
    
    }

    public void bulkAfter(Schema.sObjectType soType){
        CheckingConditionOnDelete();
        beforeUpdateAndInsert();
        onDelete();
   }
    
    public void beforeInsert(SObject so){}
    
    public void beforeUpdate(SObject oldSo, SObject so){}
    
    public void beforeDelete(SObject so){}
    
    public void afterInsert(SObject so){}
    
    public void afterUpdate(SObject oldSo, SObject so){}
    
    public void afterDelete(SObject so){}
    
    public void CheckingConditionOnDelete(){
         if(!trigger.isDelete){
            for (Travelling_Country__c  tc: (List<Travelling_Country__c>)Trigger.New) {
                countries.add(tc.TC_country__c);
                oppIds.add(tc.TC_Opportunity__c);
            }
            
         }
         else{
            for (Travelling_Country__c  tc : (List<Travelling_Country__c>)Trigger.old) {
                oppIds.add(tc.TC_Opportunity__c);
            }
         }
       OppQuery(oppIds);
    }
    
    
    public List<Opportunity> OppQuery(Set<String> oppIds){
          for(Opportunity opp : [select id, OwnerId ,closeDate,O_Target_Mark_Up__r.TMU_APC__c, O_Target_Mark_Up__r.TMU_FFP__c,  O_Target_Mark_Up__r.TMU_TOMS_APC__c,O_Target_Mark_Up__r.TMU_TOMS_FFP__c,O_Target_Mark_Up__r.TMU_Target_Margin__c ,(Select Id, TC_Country__c, TC_Country__r.name from Travelling_Countries__r),  O_Departure_Date__c,O_Suggested_Margin__r.M_Margin__c,O_Return_Date__c ,O_Suggested_Margin__c from Opportunity where id in: oppIds]){
            Opps.add(opp);
          }
         return Opps;
    }
    
    
    
    public void beforeUpdateAndInsert(){
        for(Attachment att : lstAtt){
            setAttIds.add(att.Id);
            mapParentAttachment.put(att.ParentId,att.Id);
         }
       
       for(Opportunity opp : Opps){
            usrIds.add(opp.OwnerId);
        }
        
        img = [Select Id,AI_Image_ID__c,AI_Count__c from Images_AI__c where AI_User__c in :usrIds and AI_Image_ID__c in :setAttIds Order by AI_Count__c];
        if(img.size()>0){
            imageId = img[0].AI_Image_ID__c;
        }
        
        for(Travelling_Country__c tc :tcList ){
           if(tc.TC_ImageID__c == null && Utility.changeCoverImage){
             if(imageId == null){
                tc.TC_ImageID__c = mapParentAttachment.get(tc.TC_country__c);
             }
             else{
                tc.TC_ImageID__c = imageId;
             }
             tc.TC_Selected__c  = datetime.now();
             tc.TC_Cover_Image__c = true;    
            } 
        }
      }
     
     public void onDelete(){
        for(Supplier_Booking__c sb :sbList){
             if(!mapOppSB.containsKey(sb.SB_Opportunity__c)){
                 mapOppSB.put(sb.SB_Opportunity__c, new List<Supplier_Booking__c>());    
             }
         }
         
         for(Target_Mark_Up__c tmu : tmuList){
              mapTargetMarkUP.put(tmu.TMU_Target_Margin__c,tmu);
         }
         isIntFlight= false;
         
         for(Recordtype rt : rtList ){
             mapRecordtype.put(rt.id,rt.name);
         }
         
         for(Opportunity opp: Opps){
            if(mapOppSB.containsKey(opp.Id)){
                 for(Supplier_Booking__c sb : mapOppSB.get(opp.Id)){
                     if(sb.recordType.Name == 'Int Flight'){
                        isIntFlight = true;
                    }
                 }
            }
            for(Travelling_Country__c tc : opp.Travelling_Countries__r){
                 travellingC.add(tc.TC_Country__c);
            }
         
            if (opp.O_Suggested_Margin__c != null) {
                 opp.O_Suggested_Margin__c = null;
            }
            marginList =[select id,M_Book_From__c,M_Book_To__c ,M_Travel_From__c,M_Travel_To__c,M_Margin__c, M_Country__r.C_EU__c from Margin__c  WHERE M_Country__c IN :travellingC order by M_Margin__c asc];
            oppMargin = opp.O_Suggested_Margin__r.M_Margin__c; 
            for(Margin__c mrg : marginList ){
                if (opp.closeDate >= mrg.M_Book_From__c && opp.closeDate <= mrg.M_Book_To__c && opp.O_Departure_Date__c >= mrg.M_Travel_From__c && opp.O_Return_Date__c <= mrg.M_Travel_To__c ){
                  if(opp.O_Suggested_Margin__c == null || oppMargin  <= mrg.M_Margin__c){
                      opp.O_Suggested_Margin__c = mrg.id;
                      oppMargin = mrg.M_Margin__c;
                      List<Margin__c> mg = [Select Id, M_Margin__c, M_Country__r.C_EU__c from Margin__c  where Id  = :Opp.O_Suggested_Margin__c]; 
                      
                      if(mapTargetMarkUP.containsKey(mrg.M_Margin__c)){
                          opp.O_Target_Mark_Up__c = mapTargetMarkUP.get(mrg.M_Margin__c).Id;
                          if(mg.size() != 0){
                                if(mg[0].M_Country__r.C_EU__c){
                                    if(isIntFlight){
                                        opp.O_Target_Mark_Up_Value__c = mapTargetMarkUP.get(mrg.M_Margin__c).TMU_TOMS_APC__c; 
                                    }
                                    else{
                                        opp.O_Target_Mark_Up_Value__c = mapTargetMarkUP.get(mrg.M_Margin__c).TMU_TOMS_FFP__c; 
                                    }
                                }
                                else{
                                    if(isIntFlight){
                                        opp.O_Target_Mark_Up_Value__c = mapTargetMarkUP.get(mrg.M_Margin__c).TMU_APC__c; 
                                    }
                                    else{
                                        opp.O_Target_Mark_Up_Value__c = mapTargetMarkUP.get(mrg.M_Margin__c).TMU_FFP__c; 
                                    }   
                                }
                          }
                      }
                      
                      if(mrg.M_Country__r.C_EU__c){
                            opp.O_EU__c = true;
                      }
                      else{
                            opp.O_EU__c = false;
                      }
                 }
              }    
           }  
           opp.O_Country__c = '';
           for(Travelling_Country__c tc : opp.Travelling_Countries__r){
                country += tc.TC_Country__r.name+', ';
           }
           country = country.removeEnd(', ');
           opp.O_Country__c = country; 
           lstOpp.add(opp);
        }   
     }
     
     
      public void andFinally(){
          if(!lstOpp.isEmpty()){
            update lstOpp;  
          }
      }
       
  }