Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/CSS_Styler__c.object
<CustomObject>
    <fields>
        <fullName>CS_Travelling_Country_Marker__c</fullName>
        <label>Travelling Country Marker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS Styler</label>
    <nameField>
        <label>CSS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Stylers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/TravellingCountryMapController.cls
global with sharing class TravellingCountryMapController {
    
    global String mapURL {get;set;}
    global TravellingCountryMapController(){
        mapURL = '';
        for(CSS_Styler__c cs : [select CS_Travelling_Country_Marker__c from CSS_Styler__c where Is_Active__c = true limit 1]){
            if(cs.CS_Travelling_Country_Marker__c != null)
                mapURL = cs.CS_Travelling_Country_Marker__c;
        }
    }
    
    
    @RemoteAction
    global static List<String> getTravellingCountriesLocation(String oppId){
        List<String> tcLst = new List<String>();
        for(Travelling_Country__c tc : [Select TC_Country__c, TC_Country__r.Name from Travelling_Country__c where TC_Opportunity__c =: oppId]){
            if(tc.TC_Country__c != null)
                tcLst.add(tc.TC_Country__r.Name);    
        }
        return tcLst;
    }
}