Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_RecordType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Record Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Record_Type__c.RT_SObject_Type__c</field>
                <operation>equals</operation>
                <value>Opportunity</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Record_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Record_Type__c.object
<CustomObject>
    <description>Custom Object to maintain opportunity record type</description>
    <fields>
        <fullName>RT_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RT_SObject_Type__c</fullName>
        <label>SObject Type</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Questionnaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Booking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Record Type</label>
    <nameField>
        <label>Record Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Selected_Itinerary_Content_Category__c.object
<CustomObject>
    <label>Selected Content Category</label>
    <nameField>
        <displayFormat>SICC-{0000000000}</displayFormat>
        <label>Itinerary Category ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Content Categories</pluralLabel>
    <recordTypes>
        <fullName>Categories</fullName>
        <active>true</active>
        <description>All Categories</description>
        <label>Print</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/CategoryControllerTest.cls
/**
 *  @Author         :   Naval Sharma
 *  @Date           :   24-Feb-2016
 *  @Description    :   Test class for "CategoryController"
 * 
 * */

@isTest
private class CategoryControllerTest{

    /** Setting up test data  **/
    
    @testSetup
    static void setupTestData(){
        Account TestAcc = new Account(Name = 'TestAccount');
        insert TestAcc ;  
        system.assert(TestAcc.Id != null);  
        
        //Create Record Type
        Record_Type__c rt = new Record_Type__c(Name = 'ST', RT_SObject_Type__c = 'Opportunity', RT_Active__c = true);
        insert rt;
        List<Opportunity>oppList=new List<Opportunity>();
        Opportunity opp=new Opportunity();
        opp.name='opp1';
        opp.stageName='Enquiry';
        opp.CloseDate=system.today()+4;
        opp.CurrencyIsoCode='GBP';
        opp.AccountId = TestAcc.Id;
        opp.O_RecordType__c = rt.Id;
        oppList.add(opp);
        insert oppList;
        
        Contact cont = new Contact(Salutation='testsal',LastName='testL',FirstName='testF',email='testemail@a.com',AccountId=TestAcc.Id);
        insert cont;
        system.assert(cont.Id != null);
        
        //Create ITC Records
        TestServices.createITCRecords();
        Country__c country = TestServices.createCountryRecords()[0];
        TestServices.createWTGRecords(country.Id);
        List<Supplier__c> lstSuppliers = TestServices.createSupplierRecords(country.Id);
        TestServices.createHolidaySuggestions(lstSuppliers[0].Id, opp.Id);
        TestServices.createSICCRecords(opp.Id, TestServices.createITCRecords()); 
        
    }
    
    /** Test various operations of the controller **/
    public static testMethod void testCategoryForData(){
        Opportunity opp = [SELECT id from Opportunity Limit 1];
        
        Test.StartTest();
        /*** Test Starts here  ****/
        ApexPages.StandardController stdctrl = new  ApexPages.StandardController(opp); 
        ApexPages.currentPage().getParameters().put('id',opp.id); 
        
        CategoryController AIC = new CategoryController(stdctrl);
        AIC.getCategories();
        AIC.getPageMessage();
        AIC.getFinalDocsCategories();
        AIC.FinalDocs_Save();
        CategoryController.changeCategories('Categories', opp.Id);
        CategoryController.Save(AIC.getCategories(), opp.Id, 'Categories');
        CategoryController.changeCategories('FinalDoc', opp.Id);
        CategoryController.Save(AIC.getCategories(), opp.Id, 'FinalDoc');
        
        /*** Test Ends here  ****/        
        Test.StopTest();

    }
    
     /** Test various operations of the controller **/
    public static testMethod void testCategoryForNoData(){
        Opportunity opp = [SELECT id from Opportunity Limit 1];
        delete [Select id from Selected_Itinerary_Content_Category__c];
        Test.StartTest();
        /*** Test Starts here  ****/
        ApexPages.StandardController stdctrl = new  ApexPages.StandardController(opp); 
        ApexPages.currentPage().getParameters().put('id',opp.id); 
        
        CategoryController AIC = new CategoryController(stdctrl);
        AIC.getCategories();
        AIC.getPageMessage();
        AIC.getFinalDocsCategories();
        AIC.FinalDocs_Save();
        CategoryController.changeCategories('Categories', opp.Id);
        CategoryController.Save(AIC.getCategories(), opp.Id, 'Categories');
        CategoryController.changeCategories('FinalDoc', opp.Id);
        CategoryController.Save(AIC.getCategories(), opp.Id, 'FinalDoc');
        
        /*** Test Ends here  ****/        
        Test.StopTest();

    }
}