Sugati/src/objects/Country__c.object
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Holiday_Suggestions__c.object
<CustomObject>
    <fields>
        <fullName>HS_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Holiday Suggestions</relationshipLabel>
        <relationshipName>Holiday_Suggestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HS_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Holiday Suggestions</relationshipLabel>
        <relationshipName>Holiday_Suggestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HS_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Holiday Suggestions</relationshipLabel>
        <relationshipName>Holiday_Suggestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Holiday Suggestion</label>
    <nameField>
        <displayFormat>HS-{0000000000}</displayFormat>
        <label>Holiday Suggestions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holiday Suggestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Holiday_Type__c.object
<CustomObject>
    <label>Holiday Type</label>
    <nameField>
        <label>Holiday Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Itinerary_Content_Category__c.object
<CustomObject>
    <label>Itinerary Category</label>
    <nameField>
        <label>Itinerary Content Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itinerary Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Itinerary_Text__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <formula>IF(ISBLANK(IT_What_to_do__c) ,  IT_Where_to_go__r.W_Country__r.Name ,  IT_What_to_do__r.WH_Country__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Countryf</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Quote_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Holiday_Type__c</fullName>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Quote_Text</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IT_Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IT_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IT_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Quote_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Itinerary_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Itinerary Text</label>
    <nameField>
        <displayFormat>IT-{0000000000}</displayFormat>
        <label>ItineraryText ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itinerary Text</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Selected_Itinerary_Content_Category__c.object
<CustomObject>
    <fields>
        <fullName>ICC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Itinerary_Content_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ICC_Page_No__c</fullName>
        <label>Page No</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SICC_Itinerary_Content_Category__c</fullName>
        <label>Itinerary Content Category</label>
        <referenceTo>Itinerary_Content_Category__c</referenceTo>
        <relationshipName>Selected_Itinerary_Content_Categories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Selected Content Category</label>
    <nameField>
        <displayFormat>SICC-{0000000000}</displayFormat>
        <label>Itinerary Category ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Content Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <fields>
        <fullName>S_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tourist Board</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_Day__c</fullName>
        <label>Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SB_From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SB_From_Place__c</fullName>
        <label>From Place</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SB_From_Time__c</fullName>
        <label>From Time</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SB_Holiday_Suggestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Suggestion</label>
        <referenceTo>Holiday_Suggestions__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SB_Notes__c</fullName>
        <description>OTUK</description>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SB_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SB_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SB_To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SB_To_Place__c</fullName>
        <label>To Place</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SB_To_Time__c</fullName>
        <label>To Time</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SB_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <recordTypes>
        <fullName>Description</fullName>
        <active>true</active>
        <label>Description</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Where_to_go__c.object
<CustomObject>
    <description>Places / Cities</description>
    <label>Where to go</label>
    <nameField>
        <label>Where to go Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Where to go</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/PreviewPdfControllerTest.cls
/**
*  @Author         :   Naval Sharma
*  @Date           :   5-Mar-2016
*  @Description    :   Test class for "PreviewPdfController"
* 
**/

@isTest
Public class PreviewPdfControllerTest{
    
    @testSetup
    static void setupTestData(){
        Test.startTest();
        /** Create custom setting data  **/
        TestServices.createTriggerCustomSetting();
        TestServices.createSiteCustomSetting();
        
        /** Create test data for PDF **/
        List<Opportunity> lstOpportunity = TestServices.createOpportunityRecords(1, null);
        List<Contact> lstContact = TestServices.createContactRecords(2, lstOpportunity[0].AccountId);
        TestServices.createTravellingCountries(lstOpportunity [0].Id);
        List<Country__c> lstCountry = [SELECT id FROM Country__c];
        List<Where_to_go__c> lstWTG =  TestServices.createWTGRecords(lstCountry[0].Id);   
        List<Supplier__c> lstSupplier = TestServices.createSupplierRecords(lstCountry[0].Id);
        List<Group_Member__c> lstGroupMembers = TestServices.createGroupMembers(TestServices.createClientGroupRecords(2, lstOpportunity[0].Id)[0].Id, lstContact);
        TestServices.createFlightBookings(lstGroupMembers[0].Id, TestServices.createSupplierBookings(lstSupplier[0].Id, lstOpportunity[0].Id)[0].Id);
        TestServices.createHolidaySuggestions(lstSupplier[0].Id, lstOpportunity[0].Id);
        List<Itinerary_Content_Category__c> ITCRecords = TestServices.createITCRecords();
        Selected_Itinerary_Content_Category__c SICC = New Selected_Itinerary_Content_Category__c(SICC_Itinerary_Content_Category__c = ITCRecords[0].Id,
            ICC_Opportunity__c = lstOpportunity[0].Id,
            ICC_Page_No__c=1);   
        insert SICC; 
        List<Holiday_Suggestions__c> HSRec = new List<Holiday_Suggestions__c>([Select id,HS_Holiday_Type__c from Holiday_Suggestions__c Where HS_Supplier__c =: lstSupplier[0].Id AND HS_Opportunity__c = :lstOpportunity[0].Id]);
        String hsId = HSRec[0].Id;
        String oppId = lstOpportunity[0].Id;
        String supplierId = lstSupplier[0].Id;
        
        TestServices.createSICCRecords(oppId, ITCRecords);  
        List<Itinerary_Text__c> lstItineraryText = new List<Itinerary_Text__c>();
        lstItineraryText.add(new Itinerary_Text__c(
            IT_Country__c = lstCountry[0].Id,
            IT_Holiday_Type__c = HSRec[0].HS_Holiday_Type__c,
            IT_Message__c = 'test',
            IT_Status__c = 'Submitted'
            
        ));   
        lstItineraryText.add(new Itinerary_Text__c(
            IT_Holiday_Type__c = HSRec[0].HS_Holiday_Type__c,
            IT_Message__c = 'test',
            IT_Status__c = 'Submitted',
            IT_Where_to_go__c = lstWTG[0].Id
            
        ));
        lstItineraryText.add(new Itinerary_Text__c(
            IT_Holiday_Type__c = HSRec[0].HS_Holiday_Type__c,
            IT_Message__c = 'test',
            IT_Status__c = 'Submitted',
            IT_Supplier__c = supplierId
            
        ));
        insert lstItineraryText;
        
        System.assertNotEquals(lstItineraryText[0].Id, null);
        //Create Target Markup
        TestServices.createTargetMarkups();
        Test.stopTest();
    }

    static testMethod void testPreviewPdfController(){
    
        Opportunity TestOpp = [SELECT Id,StageName from Opportunity Limit 1]; 
        Holiday_Type__c ht = [SELECT id from Holiday_Type__c limit 1];
        TestOpp.O_Holiday_Type__c = ht.id;
        
        upsert TestOpp;
        system.assert(TestOpp.id != null);
         
        /** Create Supplier Booking for Car Hire', 'Int Flight'  **/
        List<Supplier__c> lstSupplier = [SELECT Id FROM Supplier__c WHERE S_Type__c = 'Hotel' Limit 1];
        String supplierId = lstSupplier[0].Id;
        String oppId = testOpp.Id;
        List<Holiday_Suggestions__c> HSRec = TestServices.createHolidaySuggestions(supplierId,  oppId);
        String hsId = HSRec[0].Id;
        
        Where_To_Go__c wtg = [SELECT Id FROM Where_To_Go__c LIMIT 1];
        List<Supplier_Booking__c> SBRec = new List<Supplier_Booking__c>();
        Map<String, String> recordTypeMap = new Map<String, String>();
        for(RecordType rt : [SELECT Id, Name FROM RecordType WHERE SObjectType = :Utility.getNameSpacePrefix()+'Supplier_Booking__c' AND Name in ('Car Hire', 'Int Flight')]){
            recordTypeMap.put(rt.Name, rt.Id);     
        }
        SBRec.add(new Supplier_Booking__c(
            SB_Day__c = 2, SB_From_Time__c = '11:30',
            SB_From_Date__c = Date.today(), SB_To_Date__c = Date.today() +1 , 
            SB_From_Place__c = 'TestLondon', SB_To_Time__c = '16:30',
            SB_To_Place__c = 'TestItaly', SB_Holiday_Suggestion__c = hsId,
            RecordTypeId = recordTypeMap.get('Car Hire'), SB_Notes__c = 'test',
            SB_Where_to_go__c = wtg.Id,
            SB_Opportunity__c = oppId, SB_Supplier__c = supplierId )
        );
        SBRec.add(new Supplier_Booking__c(
            SB_Day__c = 2, SB_From_Time__c = '11:30',
            SB_From_Date__c = Date.today(), SB_To_Date__c = Date.today()+1 , 
            SB_From_Place__c = 'TestLondon', SB_To_Time__c = '16:30',
            SB_To_Place__c = 'TestItaly', SB_Holiday_Suggestion__c = hsId,
            SB_Where_to_go__c = wtg.Id,
            RecordTypeId = recordTypeMap.get('Int Flight'), SB_Notes__c = 'test',
            SB_Opportunity__c = oppId, SB_Supplier__c = supplierId )
        );
        insert SBRec;   
        system.assert(SBRec.size()>0);
        
        ApexPages.standardController std =  new ApexPages.standardController(TestOpp);
        
        PreviewPdfController ppc = new PreviewPdfController(std);
        
        // execute all methods of PreviewPdfController
        ppc.getWhereYouWillStay();
        ppc.getWhereStay();
        ppc.getflight();
        ppc.getItineraryGlanceFlight();
        ppc.getItineraryFlightMessage();
        ppc.getItineraryFlightMessage1();
        
        system.assert(ppc.attachedFiles == null) ;
         
        TestOpp.StageName = 'Booking Optional';
        upsert TestOpp;
        ppc.getItineraryFlightBookedMessage();
        ppc.getItineraryFlightBookedMessage1();
        List<Supplier_Booking__c> sbcLst =  ppc.getItineraryGlanceAccommodation();
        
        system.assert(sbcLst != null);
        system.assert(ppc.lstSelectedItinerary == null);
        system.assert(ppc.lstStr == null);
        system.assert(ppc.attachedMap == null);
        system.assert(ppc.attachedUserPhoto == null);
        system.assert(ppc.lstDetailedItinerary == null);
        system.assert(ppc.lstTC == null);
        system.assert(ppc.lstTCMap == null);
        system.assert(ppc.lstTravelCountry == null);
        system.assert(ppc.lstCountry == null);
        
        
        ppc.getLogo();
        ppc.getOTUKLogo();
        ppc.getColor();
        ppc.getYourGuides();
        ppc.getAcc();
        ppc.getDetailedItinerary1();
        ppc.getGroupMembers();
         
         
    }
}