Sugati/src/objects/CSS_Styler__c.object
<CustomObject>
    <fields>
        <fullName>Backgroundcolor__c</fullName>
        <label>Backgroundcolor</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSS__c</fullName>
        <label>CSS</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Font_Family__c</fullName>
        <label>Font-Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Font_Size__c</fullName>
        <label>Font-Size</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Font_Style__c</fullName>
        <label>Font-Style</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H1color__c</fullName>
        <label>H1color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H2color__c</fullName>
        <label>H2color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H3color__c</fullName>
        <label>H3color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H4color__c</fullName>
        <label>H4color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header_Color__c</fullName>
        <label>Header-Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header_Font_Style__c</fullName>
        <label>Header-Font-Style</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header_Font_size__c</fullName>
        <label>Header-Font-size</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hr_Background__c</fullName>
        <label>Hr-Background</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hr_Height__c</fullName>
        <label>Hr-Height</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Table_Backgroundcolor__c</fullName>
        <label>Table Backgroundcolor</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Border_Color__c</fullName>
        <label>Table Border Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Font_Family__c</fullName>
        <label>Table Font-Family</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Font_Size__c</fullName>
        <label>Table Font-Size</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Font_Style__c</fullName>
        <label>Table Font-Style</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Footer_Backgroundcolor__c</fullName>
        <label>Table Footer Backgroundcolor</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Footer_Text_Color__c</fullName>
        <label>Table Footer Text Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Header_Backgroundcolor__c</fullName>
        <label>Table Header Backgroundcolor</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Header_Text_Color__c</fullName>
        <label>Table Header Text Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Typography__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Typography</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS Styler</label>
    <nameField>
        <label>CSS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Stylers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/CSSStyler.cls
public with sharing class CSSStyler {

    public CSSStyler(ApexPages.StandardController controller) {

    }
    
    public CSSStyler() {

    }

    public CSS_Styler__c cssObj{get; set;}
    public string pagename{get;set;}
    
    public string getCss() {
        List<CSS_Styler__c> CSSStyles = new List<CSS_Styler__c>();
        
        if(pagename != null){
            CSSStyles = [select CSS__c,Backgroundcolor__c,Font_Family__c,Font_Size__c,Font_Style__c,H1color__c,H2color__c,
                        Table_Backgroundcolor__c,Table_Border_Color__c,Table_Font_Family__c,Table_Font_Size__c,Table_Font_Style__c,
                        Table_Footer_Backgroundcolor__c,Table_Footer_Text_Color__c,Table_Header_Backgroundcolor__c,Table_Header_Text_Color__c,
                        H3color__c,H4color__c,Header_Color__c,Header_Font_size__c,Header_Font_Style__c,Hr_Background__c,Hr_Height__c,
                        Is_Active__c,Typography__c
                         from CSS_Styler__c where name =:pagename and Is_Active__c = true];
        }
        else{
            CSSStyles = [select CSS__c,Backgroundcolor__c,Font_Family__c,Font_Size__c,Font_Style__c,H1color__c,H2color__c,
                        Table_Backgroundcolor__c,Table_Border_Color__c,Table_Font_Family__c,Table_Font_Size__c,Table_Font_Style__c,
                        Table_Footer_Backgroundcolor__c,Table_Footer_Text_Color__c,Table_Header_Backgroundcolor__c,Table_Header_Text_Color__c,
                        H3color__c,H4color__c,Header_Color__c,Header_Font_size__c,Header_Font_Style__c,Hr_Background__c,Hr_Height__c,
                        Is_Active__c,Typography__c from CSS_Styler__c where name = 'ClientInvoice' and Is_Active__c = true];
        }
        //System.assert(false,CSSStyles);
        if(CSSStyles.size() > 0){
            cssObj = CSSStyles[0];
            return CSSStyles[0].CSS__c;
        }
        else
            return '';
    }
    
    
}