Sugati/src/objects/CSS_Styler__c.object
<CustomObject>
    <fields>
        <fullName>CSS__c</fullName>
        <label>CSS</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS Styler</label>
    <nameField>
        <label>CSS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Stylers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/CSSStylerTest.cls
@isTest
public with sharing class CSSStylerTest {
    @isTest public static void testGetCss() {
        
       
        /**
         * Test with valid pagename        
         */
        String pagename   = 'TestPage';
        String csscontent = 'CSS Content';
        
        // Insert test page
        CSS_Styler__c objCSS = new CSS_Styler__c(name = pagename, CSS__c = csscontent, Is_Active__c = true);
        insert objCSS;
        ApexPages.StandardController controller = new ApexPages.StandardController(objCSS);
        CSSStyler css = new CSSStyler(controller);
        
        css.pagename = pagename;
        System.assertEquals(csscontent, css.getCss());
        
        
        /**
         * Test with invalid pagename        
         */
        css.pagename = 'InvalidPage';
        System.assertEquals('', css.getCss());
        
        
        /**
         * Test with blank pagename        
         */
        css.pagename = '';
        System.assertEquals('', css.getCss());
    }
}