Sugati/src/objects/CSS_Styler__c.object
<CustomObject>
    <fields>
        <fullName>Backgroundcolor__c</fullName>
        <label>Backgroundcolor</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Button__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Button</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CS_Address_Marker__c</fullName>
        <label>Address Marker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Itinerary_Page_Marker__c</fullName>
        <label>Itinerary Page Marker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Font_Color__c</fullName>
        <label>Email Font Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Font_Family__c</fullName>
        <label>Email Font-Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Font_Style__c</fullName>
        <label>Email Font Style</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Font_Family__c</fullName>
        <label>Font-Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Font_Size__c</fullName>
        <label>Font-Size</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Font_Style__c</fullName>
        <label>Font-Style</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H1color__c</fullName>
        <label>H1color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H2color__c</fullName>
        <label>H2color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H3color__c</fullName>
        <label>H3color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>H4color__c</fullName>
        <label>H4color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hr_Background__c</fullName>
        <label>Hr-Background</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hr_Height__c</fullName>
        <label>Hr-Height</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Typography__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Typography</label>
        <type>Checkbox</type>
    </fields>
    <label>CSS Styler</label>
    <nameField>
        <label>CSS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSS Stylers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/CSSControllerTest.cls
/**
*  @Author         :   Naval Sharma
*  @Date           :   1-Mar-2016
*  @Description    :   Test class for "CSSController"
* 
**/
 
@isTest
Private class CSSControllerTest {
   
    /** Test various operations of CSSController for new record **/
    Private Static testMethod void TestCSSController1(){
        
        Test.startTest();
        
        CSSController css = new CSSController();  
        String JSONData = css.getCSSData();
        css.getPageNames();
        CSSController.SaveCssData(JSONData); 
        
        Test.stopTest();
    }
    
    /** Test various operations of CSSController for existing record **/
    Private Static testMethod void TestCSSController2(){
        
        CSS_Styler__c cssRecord = new CSS_Styler__c(
            CS_Address_Marker__c = 'test', 
            Backgroundcolor__c = 'test', 
            CS_Itinerary_Page_Marker__c = 'test', 
            H1color__c  = 'test', 
            H2color__c  = 'test', 
            H3color__c  = 'test', 
            H4color__c  = 'test', 
            Hr_Background__c = 'test', 
            Hr_Height__c = 'test', 
            Email_Font_Family__c = 'test', 
            Email_Font_Style__c = 'test', 
            Email_Font_Color__c = 'test', 
            Font_Family__c = 'test', 
            Font_Size__c = 'test', 
            Font_Style__c = 'test',            
            Is_Active__c = true,
            Button__c = true,
            Email__c = true,
            Typography__c = true
        );
        insert cssRecord; 
        cssRecord.Id = null; 
        insert cssRecord; 
        
        Test.startTest();
        
        ApexPages.currentPage().getParameters().put('Id', cssRecord.Id);
        CSSController css = new CSSController();
        CSSController.getAddressMarkerURL();      
        CSSController.getItineraryMarkerURL();     
        String JSONData = css.getCSSData();
        CSSController.SaveCssData(JSONData); 
        
        Test.stopTest();
    }
}