Sugati/src/objects/Error_Message__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>AckPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClientPayments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CopyOpportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CoverPageSelector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FileUpload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FinalDoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HolidayEnquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HolidaySuggestion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ItineraryBuilder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ItineraryCategory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ManageTasks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDFSetting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SendEmail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SupplierPayments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Error Message</label>
    <nameField>
        <label>Error Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/ErrorMessageController.cls
public with sharing class ErrorMessageController {

    public ErrorMessageController(Object obj) {

    }
    
    public ErrorMessageController(ApexPages.StandardController controller){
     
    }
    
    public static string HOLIDAY_SUGGESTION = 'HolidaySuggestion';
    public static string HOLIDAY_ENQUIRY = 'HolidayEnquiry';
    public static string ITINERARY_BUILDER = 'ItineraryBuilder';
        
    
    public static Map<String, String> getErrorMessage(string pagename) {
         pagename = pagename.replaceAll('sugati__','');
         Map<String,String> mapErrorMessage;
         if (mapErrorMessage == null) {
             mapErrorMessage = new Map<String,String>();
             for(Error_Message__c errorMessage: [select id, name, page_name__c, error_message__c from error_message__c where page_name__c=: pagename]) {
                 mapErrorMessage.put(errorMessage.name, errorMessage.error_message__c );
             }
         }
         return mapErrorMessage;
    }
    
    public static string getHolidaySuggestionText(string pagename, String errorMessageName) {
        return getErrorMessage(pagename).get(HOLIDAY_SUGGESTION + errorMessageName);
    }
    public static string getHolidayEnquiryText(string pagename, String errorMessageName) {
        return getErrorMessage(pagename).get(HOLIDAY_ENQUIRY + errorMessageName);
    }
    
    @remoteAction
    public static Map<string, String> getErrorMessages(String pagename) {
        return getErrorMessage(pagename);
    }
}