Sugati/src/objects/Error_Message__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>AckPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClientPayments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CopyOpportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CoverPageSelector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FileUpload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FinalDoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HolidayEnquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HolidaySuggestion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ItineraryBuilder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ItineraryCategory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ManageTasks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDFSetting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SendEmail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SupplierPayments</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Error Message</label>
    <nameField>
        <label>Error Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/ErrorMessageControllerTest.cls
/**
*  @Author         :   Naval Sharma
*  @Date           :   1-Mar-2016
*  @Description    :   Test class for "ErrorMessageController"
* 
**/
 
@isTest
public class  ErrorMessageControllerTest {

    /** Create test data for executing test cases  **/
    @testSetup
    static void createTestData(){
        
        List<Error_Message__c> lstErrorMessage = new List<Error_Message__c>();
        lstErrorMessage.add(new Error_Message__c(Page_Name__c = 'HolidayEnquiry', Name = 'HolidayEnquiryTestMessage', Error_Message__c = 'test'));
        lstErrorMessage.add(new Error_Message__c(Page_Name__c = 'ItineraryBuilder', Name = 'ItineraryBuilderTestMessage', Error_Message__c = 'test'));
        lstErrorMessage.add(new Error_Message__c(Page_Name__c = 'HolidaySuggestion', Name = 'HolidaySuggestionTestMessage', Error_Message__c = 'test'));
        insert lstErrorMessage;
    }
    /** Test various operations of ErrorMessageController  **/
    static testMethod void errorMessageTest1(){
        
        Error_Message__c em = new Error_Message__c();
        ApexPages.standardController controller = new ApexPages.standardController(em);
        
        ErrorMessageController emc = new ErrorMessageController(controller);
        ErrorMessageController emc1 = new ErrorMessageController(em);
        
        ErrorMessageController.getHolidaySuggestionText('HolidaySuggestion', 'TestMessage');
        ErrorMessageController.getHolidayEnquiryText('HolidayEnquiry', 'TestMessage');
        ErrorMessageController.getErrorMessages('HolidayEnquiry'); 
    }
    
}