Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>BirthDate_Formula__c</fullName>
        <formula>IF(  
   AND(
       OR(
         MONTH(GM_Opportunity__r.O_Departure_Date__c)&lt;= MONTH(GM_Contact__r.Birthdate),                 
	 MONTH(GM_Contact__r.Birthdate)&lt;= MONTH(GM_Opportunity__r.O_Return_Date__c)
         ),          
       OR(
         DAY(GM_Opportunity__r.O_Departure_Date__c)&lt;= DAY(GM_Contact__r.Birthdate), 
         DAY(GM_Contact__r.Birthdate)&lt;= DAY(GM_Opportunity__r.O_Return_Date__c)
         )
    ),
         true,false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BirthDate Formula</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Birthday_Alert_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Birthday Alert Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/BirthDateAlert.cls
global class BirthDateAlert implements Database.Batchable<Sobject>,Database.Stateful{
     
    global List<Group_Member__c> grpMemberListUpdate = new List<Group_Member__c>();
    global List<Task> alertTaskList = new List<Task>();
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        Id opid;
        String query='SELECT Id,GM_Contact__c, GM_Opportunity__r.OwnerId,Name,GM_Opportunity__r.Id,GM_Contact__r.id,GM_Opportunity__r.O_Departure_Date__c,GM_Contact__r.Birthdate,GM_Opportunity__r.O_Return_Date__c,BirthDate_Formula__c,Birthday_Alert_Check__c from Group_Member__c where GM_Opportunity__r.StageName=\'Booked\' AND  BirthDate_Formula__c= true AND Birthday_Alert_Check__c=false';
        return Database.getQueryLocator(query);
    }
        
    global void execute(Database.BatchableContext BC,List<Group_Member__c> scope){
        Set<Id> conId = new Set<Id>();
       
        for(Group_Member__c gm : scope){
          Task alertTask= new Task();
          if(gm.BirthDate_Formula__c){ 
             gm.Birthday_Alert_Check__c=true;
             alertTask.OwnerId =gm.GM_Opportunity__r.OwnerId;
             alertTask.Type='Email';
             alertTask.Subject='Happy Birthday!!';
             alertTask.WhoId=gm.GM_Contact__r.id;
             alertTask.WhatId= gm.GM_Opportunity__r.Id;
             grpMemberListUpdate.add(gm);
             alertTaskList.add(alertTask);
            }
        }
     }
    
    global void finish(Database.BatchableContext BC){
        try{
            insert alertTaskList;
            update grpMemberListUpdate;
            
        }
        catch(system.DMLException e){
            system.debug('Following Error has Occured'+ e.getMessage());
        }
    }


}