Sugati/src/objects/Group_Member__c.object
<CustomObject>
    <description>A list of people that are travelling...</description>
    <fields>
        <fullName>GM_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GM_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Group Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/BirthDateAlertTest.cls
@isTest
private class BirthDateAlertTest{
    
    @testSetup 
    static void testData() {
      Opportunity opp = new Opportunity();
      opp.Name='Test'; 
      opp.StageName='Active';
      opp.O_Departure_Date__c=date.newInstance(2016, 8, 4);
      opp.O_Return_Date__c=date.newInstance(2016, 8, 14);
      opp.StageName = 'Booked';
      opp.CloseDate=system.today();
      insert opp;
      
      Contact con = new Contact();
      con.LastName = 'Test LastName';
      con.Birthdate=date.newInstance(1995, 8, 4);
      insert con;
      
      Group_Member__c gmc = new Group_Member__c();
      gmc.GM_Opportunity__c=opp.Id;
      gmc.GM_Contact__c=con.Id;
      insert gmc;    
      
      Task tsk = new Task();
      tsk.Type='Email';
      tsk.Subject='Test';
      tsk.WhoId=con.Id;
      tsk.WhatId=opp.Id;
      insert tsk;
 
    }
    static testMethod void batchTestOne(){
        
      List<Task> qry = new List<Task>([SELECT Id from Task LIMIT 1 ]);
      Test.startTest();
      BirthDateAlert bdayalert = new BirthDateAlert();
      Database.executeBatch(bdayalert,1);
      Test.stopTest();
    
    }
    
   

}