Sugati/src/objects/Holiday_Question__c.object
<CustomObject>
    <fields>
        <fullName>HQ_Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>HQ_Create_Task__c</fullName>
        <formula>HQ_Question__r.Q_Task__c</formula>
        <label>Create Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HQ_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Holiday_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HQ_OwnerID_F__c</fullName>
        <formula>HQ_Opportunity__r.Owner.Id</formula>
        <label>OwnerID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HQ_Question_F__c</fullName>
        <formula>HQ_Question__r.Q_Question_Name__c</formula>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <label>Preference</label>
    <nameField>
        <displayFormat>HEQ-{0000000}</displayFormat>
        <label>Holiday Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Site__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Run_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Run Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
</CustomObject>

Sugati/src/classes/HolidayQuestion.cls
public Class HolidayQuestion{

    public HolidayQuestion(){
    }
    
    public Static void TriggerBefore(){
         if(Site__c.getInstance().Run_Trigger__c){
             List<Holiday_Question__c> selectedHQ = new List<Holiday_Question__c>();
             List<String> lstHQIDS = new List<String>();
             Map<String,Task> mapExistingTasks = new Map<String,Task>();
             List<Task> newTasks = new List<Task>();
             for(Holiday_Question__c hq : (List<Holiday_Question__c>)Trigger.New){
                 if(hq.HQ_Create_Task__c){
                     selectedHQ.add(hq);
                     lstHQIDS.add(hq.Id);
                 }
             }
             for(Task tk : [Select Id,WhatId,Status,Subject,ActivityDate,Preference__c from Task where Preference__c in :lstHQIDS]){
                 mapExistingTasks.put(tk.Preference__c, tk);
             }
             for(Holiday_Question__c hq : selectedHQ){
                 if(mapExistingTasks.containsKey(hq.Id)){
                     Task tsk = mapExistingTasks.get(hq.Id);
                     tsk.ActivityDate  = Date.parse(hq.HQ_Answer__c);
                     newTasks.add(tsk);
                 }
                 else{
                     newTasks.add(new Task(OwnerId = hq.HQ_OwnerID_F__c,Subject = hq.HQ_Question_F__c,WhatId = hq.HQ_Opportunity__c,ActivityDate = Date.parse(hq.HQ_Answer__c),Status='Not Started',Preference__c=hq.Id));
                 }
             }
             
             upsert newTasks;
         }        
    }
}