Sugati/src/objects/Holiday_Suggestions__c.object
<CustomObject>
    <fields>
        <fullName>HS_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Holiday Suggestions</relationshipLabel>
        <relationshipName>Holiday_Suggestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HS_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Holiday Suggestions</relationshipLabel>
        <relationshipName>Holiday_Suggestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HS_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Holiday Suggestions</relationshipLabel>
        <relationshipName>Holiday_Suggestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Holiday Suggestion</label>
    <nameField>
        <displayFormat>HS-{0000000000}</displayFormat>
        <label>Holiday Suggestions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holiday Suggestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Itinerary_Text__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <formula>IF(ISBLANK(IT_What_to_do__c) ,  IT_Where_to_go__r.W_Country__r.Name ,  IT_What_to_do__r.WH_Country__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Countryf</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Quote_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Holiday_Type__c</fullName>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Quote_Text</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IT_Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IT_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IT_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Quote_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipLabel>Itinerary Text</relationshipLabel>
        <relationshipName>Itinerary_Text</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Itinerary Text</label>
    <nameField>
        <displayFormat>IT-{0000000000}</displayFormat>
        <label>ItineraryText ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itinerary Text</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Choose an agent if this is an agent booking.</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Selected_Itinerary_Content_Category__c.object
<CustomObject>
    <fields>
        <fullName>ICC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Itinerary_Content_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ICC_Page_No__c</fullName>
        <label>Page No</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SICC_Itinerary_Content_Category__c</fullName>
        <label>Itinerary Content Category</label>
        <referenceTo>Itinerary_Content_Category__c</referenceTo>
        <relationshipName>Selected_Itinerary_Content_Categories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Selected Content Category</label>
    <nameField>
        <displayFormat>SICC-{0000000000}</displayFormat>
        <label>Itinerary Category ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Content Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_Payment_Type__c</fullName>
        <description>This is for Tickets and Vouchers</description>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prepaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <recordTypes>
        <fullName>Description</fullName>
        <active>true</active>
        <label>Description</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Cost_Payment__c.object
<CustomObject>
    <fields>
        <fullName>SCP_Is_Agent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Agent</label>
        <type>Checkbox</type>
    </fields>
    <label>Supplier Cost &amp; Payment</label>
    <nameField>
        <displayFormat>SCP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs &amp; Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Payment__c.object
<CustomObject>
    <fields>
        <fullName>SB_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SP_Bank_Account__c</fullName>
        <label>Bank Account</label>
        <picklist>
            <picklistValues>
                <fullName>Account 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account 4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SP_Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SP_Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SP_Paid_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Paid By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Supplier_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SP_Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SP_Transferred_To_Accts__c</fullName>
        <label>Transferred To Accts</label>
        <type>Date</type>
    </fields>
    <label>Supplier Payment</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier_Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/SupplierPaymentsControllerTest.cls
/***
* @Description - Unit test class to test functionality of SupplierPaymentsController.cls
* @Author - Naval Sharma (Appcino)
* @Date - 29 Feb 2016
** */

@isTest
class SupplierPaymentsControllerTest{
    
    @testSetup
    static void createTestData(){
        
        Test.startTest();
         /** Create custom setting data  **/
        TestServices.createTriggerCustomSetting();
        TestServices.createSiteCustomSetting();
        
        /** Create test data for PDF **/
        List<Opportunity> lstOpportunity = TestServices.createOpportunityRecords(1, null);
        List<Contact> lstContact = TestServices.createContactRecords(2, lstOpportunity[0].AccountId);
        TestServices.createTravellingCountries(lstOpportunity [0].Id);
        List<Country__c> lstCountry = [SELECT id FROM Country__c];
        List<Where_to_go__c> lstWTG =  TestServices.createWTGRecords(lstCountry[0].Id);   
        List<Supplier__c> lstSupplier = TestServices.createSupplierRecords(lstCountry[0].Id);
        List<Client_Group__c> lstClientGroups = TestServices.createClientGroupRecords(2, lstOpportunity[0].Id);
        List<Group_Member__c> lstGroupMembers = TestServices.createGroupMembers(lstClientGroups[0].Id, lstContact);
        TestServices.createFlightBookings(lstGroupMembers[0].Id, TestServices.createSupplierBookings(lstSupplier[0].Id, lstOpportunity[0].Id)[0].Id);
        TestServices.createHolidaySuggestions(lstSupplier[0].Id, lstOpportunity[0].Id);
        List<Itinerary_Content_Category__c> ITCRecords = TestServices.createITCRecords();
        Selected_Itinerary_Content_Category__c SICC = New Selected_Itinerary_Content_Category__c(SICC_Itinerary_Content_Category__c = ITCRecords[0].Id,
            ICC_Opportunity__c = lstOpportunity[0].Id,
            ICC_Page_No__c=1);   
        insert SICC; 
        List<Holiday_Suggestions__c> HSRec = new List<Holiday_Suggestions__c>([Select id,HS_Holiday_Type__c from Holiday_Suggestions__c Where HS_Supplier__c =: lstSupplier[0].Id AND HS_Opportunity__c = :lstOpportunity[0].Id]);
        String hsId = HSRec[0].Id;
        String oppId = lstOpportunity[0].Id;
        String supplierId = lstSupplier[0].Id;
        
        TestServices.createSICCRecords(oppId, ITCRecords);  
        List<Itinerary_Text__c> lstItineraryText = new List<Itinerary_Text__c>();
        lstItineraryText.add(new Itinerary_Text__c(
            IT_Country__c = lstCountry[0].Id,
            IT_Holiday_Type__c = HSRec[0].HS_Holiday_Type__c,
            IT_Message__c = 'test',
            IT_Status__c = 'Submitted'
            
        ));   
        lstItineraryText.add(new Itinerary_Text__c(
            IT_Holiday_Type__c = HSRec[0].HS_Holiday_Type__c,
            IT_Message__c = 'test',
            IT_Status__c = 'Submitted',
            IT_Where_to_go__c = lstWTG[0].Id
            
        ));
        lstItineraryText.add(new Itinerary_Text__c(
            IT_Holiday_Type__c = HSRec[0].HS_Holiday_Type__c,
            IT_Message__c = 'test',
            IT_Status__c = 'Submitted',
            IT_Supplier__c = supplierId
            
        ));
        insert lstItineraryText;
        
        System.assertNotEquals(lstItineraryText[0].Id, null);
        TestServices.createSupplierCostRecords(supplierId, lstClientGroups[0].Id);
        TestServices.createSupplierCostPayments(supplierId, oppId);
        //Create Target Markup
        TestServices.createTargetMarkups();
        Test.stopTest();
        
    }
    
    
    /** Test various operations of itinerary pdf  **/
    static testMethod void itineraryPDFTest1(){
        
        /** Set an opportunity to render pdf **/
        Opportunity TestOpp = [SELECT Id from Opportunity Limit 1];   
        Supplier__c supplier = [SELECT id from Supplier__c Limit 1];
        Holiday_Type__c ht = [SELECT id from Holiday_Type__c Limit 1];
        TestOpp.O_Holiday_Type__c = ht.Id;
        TestOpp.O_Agent__c = supplier.Id;
        update TestOpp;
        Supplier_Cost_Payment__c scp = [SELECT Id FROM Supplier_Cost_Payment__c LIMIT 1];
        scp.SCP_Is_Agent__c = true;
        update scp;
        Supplier_Payment__c sp = new Supplier_Payment__c(
            SP_Bank_Account__c = 'Handles Bank Account EUR - 71697839',
            SP_Note__c = 'test',
            SP_Transferred_To_Accts__c = Date.today(),
            SB_Payment_Type__c = 'Deposit',
            SP_Payment_Date__c = Date.today(),
            SP_Paid_By__c = UserInfo.getUserId(),
            SP_Due_Date__c = Date.today()+5,
            SP_Currency__c = 'GBP',
            SP_Comment__c = 'test',
            SBP_Supplier_Cost_Currency_Value__c = scp.Id,
            SP_Authorised_by__c = 'Ysobel Greenlees',
            P_Amount__c = 200
        );
        insert sp;
        
        Supplier_Booking__c sb = [SELECT Id FROM Supplier_Booking__c Limit 1];
       
        ApexPages.StandardController stdctrl = new  ApexPages.StandardController(TestOpp); 
        SupplierPaymentController spc = new SupplierPaymentController(stdctrl);
        spc.preLoadComplete();
        spc.oneByOne();
        spc.edit();
        spc.selectedRow = 1;
        spc.ChangeSupplier();
        spc.savePaymetns();
    }  
    
    
    /** Test various operations of itinerary pdf  **/
    static testMethod void itineraryPDFTest2(){
        
        /** Set an opportunity to render pdf **/
        Opportunity TestOpp = [SELECT Id from Opportunity Limit 1];   
        Supplier__c supplier = [SELECT id from Supplier__c Limit 1];
        Holiday_Type__c ht = [SELECT id from Holiday_Type__c Limit 1];
        TestOpp.O_Holiday_Type__c = ht.Id;
        TestOpp.O_Agent__c = supplier.Id;
        update TestOpp;
        Supplier_Cost_Payment__c scp = [SELECT Id FROM Supplier_Cost_Payment__c LIMIT 1];
        scp.SCP_Is_Agent__c = true;
        update scp;
        
        
        Supplier_Booking__c sb = [SELECT Id FROM Supplier_Booking__c Limit 1];
        sb.SB_Own_Arrangement__c = true;
        update sb;
        ApexPages.StandardController stdctrl = new  ApexPages.StandardController(TestOpp); 
        SupplierPaymentController spc = new SupplierPaymentController(stdctrl);
        spc.preLoadComplete();
        
    }         
}