Sugati/src/objects/Itinerary_Content__c.object
<CustomObject>
    <description>Itinerary Content Library</description>
    <fields>
        <fullName>IC_ConfirmationLetter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmation Letter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IC_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>Itinerary_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IC_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IC_FinalDoc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FinalDoc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IC_Itinerary_Content_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Itinerary Content Category</label>
        <referenceTo>Itinerary_Content_Category__c</referenceTo>
        <relationshipName>Itinerary_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IC_Order__c</fullName>
        <label>Order</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IC_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Content</label>
    <nameField>
        <displayFormat>IC-{0000000000}</displayFormat>
        <label>Itinerary Content ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Itinerary_Content_Category__c.object
<CustomObject>
    <fields>
        <fullName>Final_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Doc</label>
        <type>Checkbox</type>
    </fields>
    <label>Itinerary Category</label>
    <nameField>
        <label>Itinerary Content Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itinerary Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Adult__c</fullName>
        <inlineHelpText>Total no of adults in a given family.</inlineHelpText>
        <label>Adult</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Adult</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Choose an agent if this is an agent booking.</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Booking_Currency__c</fullName>
        <label>Booking Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Children__c</fullName>
        <label>Children</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Child</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Display_Due_Date__c</fullName>
        <inlineHelpText>x number of days before Departure Date. To be used only to overwrite the standard 60 days before departure date.</inlineHelpText>
        <label>Display Due Date</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Due_Date__c</fullName>
        <description>IF( O_Display_Due_Date__c&gt; 60 , O_Departure_Date__c - 90, O_Departure_Date__c - 60)</description>
        <formula>IF(  ISNULL(O_Display_Due_Date__c) , O_Departure_Date__c - 60, O_Departure_Date__c - O_Display_Due_Date__c)</formula>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Infant__c</fullName>
        <label>Infant</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Infant</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Itinerary_Cover_Name__c</fullName>
        <label>Itinerary Cover Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Outstanding__c</fullName>
        <formula>Amount - O_Total_Payment_Without_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>O_Total_Payment__c</fullName>
        <label>Total Payment Received</label>
        <summarizedField>Client_Payment__c.CP_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Client_Payment__c.CP_Processed_On__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Client_Payment__c.CP_Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Selected_ICC_Copy__c.object
<CustomObject>
    <fields>
        <fullName>SICCO_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Itinerary Content Category</label>
        <referenceTo>Selected_Itinerary_Content_Category__c</referenceTo>
        <relationshipLabel>Selected ICCs Copy</relationshipLabel>
        <relationshipName>Selected_ICCs_Copy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SICCO_Confirmation_Letter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmation Letter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SICCO_Content__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content</label>
        <referenceTo>Itinerary_Content__c</referenceTo>
        <relationshipLabel>Selected ICCs Copy</relationshipLabel>
        <relationshipName>Selected_ICCs_Copy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SICCO_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Selected ICCs Copy</relationshipLabel>
        <relationshipName>Selected_ICCs_Copy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SICCO_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SICCO_FinalDoc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FinalDoc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SICCO_Order__c</fullName>
        <label>Order</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>999</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SICCO_Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>Selected ICC Copy</label>
    <nameField>
        <displayFormat>SICCO-{0000000000}</displayFormat>
        <label>Selected ICC Copy ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected ICCs Copy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Selected_Itinerary_Content_Category__c.object
<CustomObject>
    <fields>
        <fullName>ICC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Itinerary_Content_Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Selected Content Category</label>
    <nameField>
        <displayFormat>SICC-{0000000000}</displayFormat>
        <label>Itinerary Category ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Content Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TC_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/classes/ItineraryFinalDocsSettingController.cls
public class ItineraryFinalDocsSettingController{
    
   
    public String lstSICCOStr{get;set;}
    public String lstForgetStr{get;set;}
    public String letterStr{get; set;}
    public String errorMsg{get; set;}
    public String nameSpacePrefix{get;set;}
    
    Set<String> travelCountries = new Set<String>();
    Opportunity Opp;
    List<Selected_Itinerary_Content_Category__c> lstSICC;
    
    public ItineraryFinalDocsSettingController(ApexPages.StandardController controller){
        String oppId;
        try{
            oppId = controller.getId();
            String finalDocHolder;
            
            ApexClass cs =[select NamespacePrefix from ApexClass where Name =:'ItineraryFinalDocsSettingController'];
            if(cs.NamespacePrefix != null){
                nameSpacePrefix = cs.NamespacePrefix+'__';
            }
            else{
                nameSpacePrefix = '';
            }
            for(Itinerary_Content_Category__c IC : [Select Id from Itinerary_Content_Category__c where Final_Doc__c = true]){
                finalDocHolder = IC.Id;
            }
            if (controller.getId() != null) {
                List<DocWrapper> lstDocWrapper = new List<DocWrapper>();
                List<DocWrapper> lstForgetWrapper = new List<DocWrapper>();
                lstSICC = new List<Selected_Itinerary_Content_Category__c>();
                Set<String> setContentPresent = new Set<String>();
                
                
                Opp = [select id, Name,O_Display_Due_Date__c,  Account.Name,O_Agent__r.id,O_Agent__r.Name, O_Departure_Date__c,
                         O_Return_Date__c,Owner.Name,Owner.Username,Owner.FirstName,O_Adult__c,O_Children__c,O_Infant__c,Amount,
                         O_Outstanding__c,O_Booking_Currency__c,O_Itinerary_Cover_Name__c,O_Total_Payment__c,StageName,O_Due_Date__c
                        from Opportunity where Id=:oppId];
                //Set Of Travelling Countries
                for(Travelling_Country__c t: [select Name,TC_Country__r.name from Travelling_Country__c
                                             where TC_Opportunity__r.Id= :OppId]){
                    travelCountries.add(t.TC_Country__r.name);
                }
                
                List<Itinerary_Content__c> lstContent = [select Id,IC_Title__c,IC_Description__c,IC_Order__c,IC_Country__r.Name, IC_Itinerary_Content_Category__c,IC_Country__c,RecordTypeId,CurrencyIsoCode,IC_ConfirmationLetter__c,IC_FinalDoc__c
                                                   from Itinerary_Content__c where IC_Itinerary_Content_Category__c = :finalDocHolder 
                                                   AND ((IC_Country__r.Name in :travelCountries)OR (IC_Country__r.Name = '')) AND 
                                                   (IC_FinalDoc__c = TRUE OR IC_ConfirmationLetter__c = TRUE)  order by IC_Order__c];
                
                //Get Selected_ICC_Copy__c
                for(Selected_ICC_Copy__c SCCIO : [select Id,SICCO_Title__c,  SICCO_Content__r.IC_Description__c,SICCO_Description__c,SICCO_Order__c,SICCO_Country__r.Name,
                                                 CurrencyIsoCode,SICCO_Content__c,SICCO_Category__c,SICCO_Country__c,SICCO_FinalDoc__c,SICCO_Confirmation_Letter__c
                                                 from Selected_ICC_Copy__c  where SICCO_Category__r.ICC_Opportunity__c = :Opp.ID
                                                 AND SICCO_Category__r.SICC_Itinerary_Content_Category__c = :finalDocHolder 
                                                 AND ((SICCO_Country__r.Name in :travelCountries)OR (SICCO_Country__r.Name = ''))
                                                 order by SICCO_Order__c]){
                    setContentPresent.add(SCCIO.SICCO_Content__c);
                    DocWrapper dwr = new DocWrapper(SCCIO.SICCO_Content__c, SCCIO.Id, SCCIO.SICCO_Title__c,SCCIO.SICCO_Order__c,SCCIO.SICCO_Country__r.Name,SCCIO.SICCO_Country__c,
                        SCCIO.SICCO_Confirmation_Letter__c,SCCIO.SICCO_FinalDoc__c,SCCIO.SICCO_Description__c, SCCIO.CurrencyIsoCode);
                    dwr.Original_Description = SCCIO.SICCO_Content__r.IC_Description__c;
                    lstDocWrapper.add(dwr);
                }
                
                lstSICCOStr = JSON.serialize(lstDocWrapper);
                if(lstDocWrapper.size() == 0){
                    for(Itinerary_Content__c  ic : lstContent){
                        if(ic.IC_Title__c == 'Medical Advice'){
                            ic.IC_Description__c = '<span Class="label">'+ic.IC_Title__c+'</span><br/><br/>'+ic.IC_Description__c;
                        }       
                        lstForgetWrapper.add(new DocWrapper(ic.Id,'', ic.IC_Title__c,ic.IC_Order__c,ic.IC_Country__r.Name,ic.IC_Country__c,ic.IC_ConfirmationLetter__c,
                                            ic.IC_FinalDoc__c,ic.IC_Description__c,ic.CurrencyIsoCode));
                    }
                    lstForgetStr = JSON.serialize(lstForgetWrapper);
                }
                else{
                    for(Itinerary_Content__c  ic : [select Id,IC_Title__c,IC_Description__c,IC_Order__c,IC_Country__r.Name, IC_Itinerary_Content_Category__c,IC_Country__c,RecordTypeId,CurrencyIsoCode,IC_ConfirmationLetter__c,IC_FinalDoc__c
                                                   from Itinerary_Content__c where IC_Itinerary_Content_Category__c = :finalDocHolder And Id not in  :setContentPresent
                                                   AND ((IC_Country__r.Name in :travelCountries)OR (IC_Country__r.Name = '')) AND
                                                   (IC_FinalDoc__c = TRUE OR IC_ConfirmationLetter__c = TRUE)  order by IC_Order__c]){
                        if(ic.IC_Title__c == 'Medical Advice'){
                            ic.IC_Description__c = '<span Class="label">'+ic.IC_Title__c+'</span><br/><br/>'+ic.IC_Description__c;
                        }       
                        lstForgetWrapper.add(new DocWrapper(ic.Id,'', ic.IC_Title__c,ic.IC_Order__c,ic.IC_Country__r.Name,ic.IC_Country__c,ic.IC_ConfirmationLetter__c,
                                            ic.IC_FinalDoc__c,ic.IC_Description__c,ic.CurrencyIsoCode));
                    }
                    lstForgetStr = JSON.serialize(lstForgetWrapper);
                }
                
                letterStr = JSON.serialize(new LetterWrapper('','','',''));
                
                
            }
            
            if(finalDocHolder == null){
                errorMsg = 'Please select Content Category to store final doc.';
            }
        }
        Catch(Exception e){
            ApexPages.addMessages(e);
        }
    }
    
    //Save ICCO
    @remoteAction
    public static String saveICCO(List<DocWrapper> lstDocWrapper, String oppId, LetterWrapper letterObj, List<DocWrapper> lstOldDataWrapper) {
        try{
            String finalDocHolder;
            for(Itinerary_Content_Category__c IC : [Select Id from Itinerary_Content_Category__c where Final_Doc__c = true]){
                finalDocHolder = IC.Id;
            }
            //List<DocWrapper> lstDocWrapper = (List<DocWrapper>)JSON.deserialize(JSONICCO,List<DocWrapper>.class);
            List<Selected_Itinerary_Content_Category__c> lstSICC = [select ID from Selected_Itinerary_Content_Category__c where  ICC_Opportunity__c = :oppId
                              AND SICC_Itinerary_Content_Category__c = :finalDocHolder ];
            
            List<Selected_ICC_Copy__c> lstSICCO = new List<Selected_ICC_Copy__c>();
            if(lstSICC.size() > 0 && lstDocWrapper.size() > 0){
                String SICCO = lstSICC[0].Id;                  
                /* Insert records from Itinerary content to Copied Object */
                for(DocWrapper ic :lstDocWrapper){
                     lstSICCO.add(new Selected_ICC_Copy__c(SICCO_Content__c = Ic.DocId,SICCO_Category__c = SICCO,SICCO_Country__c=ic.SICCO_CountryID,SICCO_Title__c = ic.SICCO_Title,SICCO_Description__c = ic.SICCO_Description,SICCO_Order__c = ic.SICCO_Order, CurrencyIsoCode=ic.CurrencyCode,SICCO_FinalDoc__c = ic.SICCO_FinalDoc,SICCO_Confirmation_Letter__c= ic.SICCO_Confirmation_Letter)); 
                }
                insert lstSICCO;
                lstSICCO.add(new Selected_ICC_Copy__c(SICCO_Category__c = SICCO,SICCO_Title__c = 'Confirmation Letter Intro',SICCO_Description__c = letterObj.CLetterIntro,SICCO_FinalDoc__c=FALSE,SICCO_Confirmation_Letter__c=TRUE,SICCO_Order__c = '0',CurrencyIsoCode='GBP')); 
                lstSICCO.add(new Selected_ICC_Copy__c(SICCO_Category__c = SICCO,SICCO_Title__c = 'Confirmation Letter Closing',SICCO_Description__c = letterObj.CLetterEnd,SICCO_FinalDoc__c=FALSE,SICCO_Confirmation_Letter__c=TRUE,SICCO_Order__c = '998',CurrencyIsoCode='GBP')); 
                lstSICCO.add(new Selected_ICC_Copy__c(SICCO_Category__c = SICCO,SICCO_Title__c = 'Final Letter Intro',SICCO_Description__c = letterObj.FLetterIntro,SICCO_FinalDoc__c=TRUE,SICCO_Confirmation_Letter__c=FALSE,SICCO_Order__c = '0',CurrencyIsoCode='GBP')); 
                lstSICCO.add(new Selected_ICC_Copy__c(SICCO_Category__c = SICCO,SICCO_Title__c = 'Final Letter Closing',SICCO_Description__c = letterObj.FLetterEnd,SICCO_FinalDoc__c=TRUE,SICCO_Confirmation_Letter__c=FALSE,SICCO_Order__c = '999',CurrencyIsoCode='GBP')); 
                upsert lstSICCO;
            }
            else if(lstSICC.size() > 0 && lstOldDataWrapper.size() > 0){
                String SICCO = lstSICC[0].Id;                  
                for(DocWrapper ic :lstOldDataWrapper){
                     lstSICCO.add(new Selected_ICC_Copy__c(Id = Ic.recId,SICCO_Content__c = Ic.DocId,SICCO_Category__c = SICCO,SICCO_Country__c=ic.SICCO_CountryID,SICCO_Title__c = ic.SICCO_Title,SICCO_Description__c = ic.SICCO_Description,SICCO_Order__c = ic.SICCO_Order, CurrencyIsoCode=ic.CurrencyCode,SICCO_FinalDoc__c = ic.SICCO_FinalDoc,SICCO_Confirmation_Letter__c= ic.SICCO_Confirmation_Letter)); 
                }
                update lstSICCO;
            }
            if(lstSICC.size() == 0){
                return 'Error';
            }
            else{
                return 'Ok';
            }
        }
        Catch(Exception e){
            System.assert(false,e.getstacktraceString()+'############'+e.getMessage());
            return e.getMessage();
        }
    }
    
     //Fetch all the HE Page Messages
    public String getHEPageErrorMessage(){
        return JSON.serialize(ErrorMessageController.getErrorMessage('FinalDoc'));
    }
    
    //To Refresh Content
    @remoteAction
    public static String refreshContent(String sccId, String OppId){
        //List<Selected_ICC_Copy__c>    lstSelectedIccCopy  = [Select Id, SICCO_Content__c from Selected_ICC_Copy__c where Id = ! :sccId and ]
        return null;
    }
    
    public Class DocWrapper{
        public String DocId{get; set;}
        public String recId{get; set;}
        public String SICCO_Title{get; set;}
        public String SICCO_Order {get; set;}
        public String SICCO_Country{get; set;}
        public String SICCO_CountryID{get; set;}
        public Boolean SICCO_Confirmation_Letter{get; set;}
        public Boolean SICCO_FinalDoc{get; set;}
        public String SICCO_Description{get; set;}
        public String Original_Description{get; set;}
        public String CurrencyCode{get; set;}
        
        public DocWrapper(String DocId, String recId, String SICCO_Title, String SICCO_Order , String SICCO_Country, String SICCO_CountryID,
                            Boolean SICCO_Confirmation_Letter, Boolean SICCO_FinalDoc,String SICCO_Description, String CurrencyCode){
            this.DocId = DocId;
            this.recId = recId;
            this.SICCO_Title = SICCO_Title;
            this.SICCO_Order = SICCO_Order;
            this.SICCO_Country = SICCO_Country;
            this.SICCO_CountryID = SICCO_CountryID;
            this.SICCO_Confirmation_Letter = SICCO_Confirmation_Letter;
            this.SICCO_FinalDoc  = SICCO_FinalDoc;
            this.SICCO_Description = SICCO_Description;
            this.CurrencyCode = CurrencyCode;
        }
    }
    
    public Class LetterWrapper{
        public string CLetterIntro{get;set;}
        public string CLetterEnd{get;set;}
        public string FLetterIntro{get;set;}
        public string FLetterEnd{get;set;}
            
        public LetterWrapper(String CLetterIntro, String CLetterEnd, String FLetterIntro, String FLetterEnd){
            this.CLetterIntro = CLetterIntro;
            this.CLetterEnd = CLetterEnd;
            this.FLetterIntro = FLetterIntro;
            this.FLetterEnd = FLetterEnd;
           
        }
    }
}