Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Questionnaire_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Questionnaire Completed</label>
        <type>Checkbox</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Questinnaire__c.object
<CustomObject>
    <description>Client and HS Questionnaire</description>
    <fields>
        <fullName>Q_Audit_By__c</fullName>
        <label>Audit By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Q_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Q_Category_Checker__c</fullName>
        <label>Category Checker</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q_Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Q_Date_of_visit__c</fullName>
        <description>This is for HS Questionnaire</description>
        <label>Date of visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Q_Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>Q-{0000000000}</displayFormat>
        <label>Questinnaire ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Questionnaire</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>H_S</fullName>
        <active>true</active>
        <description>Health and Safety</description>
        <label>H&amp;S</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Questionnaire_Answer__c.object
<CustomObject>
    <description>Answers submitted by clients</description>
    <fields>
        <fullName>QA_Answer__c</fullName>
        <label>Open Text Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QA_Other__c</fullName>
        <label>Other</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QA_Questionnaire_Answer_Option__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire Answer Option</label>
        <referenceTo>Questionnaire_Answer_Options__c</referenceTo>
        <relationshipLabel>Questionnaire Answers</relationshipLabel>
        <relationshipName>Questionnaire_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Questionnaire_Question__c</fullName>
        <label>Questionnaire Question</label>
        <referenceTo>Questionnaire_Question__c</referenceTo>
        <relationshipLabel>Questionnaire Answers</relationshipLabel>
        <relationshipName>Questionnaire_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QA_Questionnaire__c</fullName>
        <label>Questionnaire</label>
        <referenceTo>Questinnaire__c</referenceTo>
        <relationshipLabel>Questionnaire Answers</relationshipLabel>
        <relationshipName>Questionnaire_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Questionnaire Answer</label>
    <nameField>
        <displayFormat>QA-{0000000000}</displayFormat>
        <label>Questionnaire Answer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Questionnaire_Answer_Options__c.object
<CustomObject>
    <description>A list of all the possible Answer Options</description>
    <fields>
        <fullName>QAO_Questionnaire_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire Question</label>
        <referenceTo>Questionnaire_Question__c</referenceTo>
        <relationshipLabel>Questionnaire Answer Options</relationshipLabel>
        <relationshipName>Questionnaire_Answer_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QAO_Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Questionnaire Answer Option</label>
    <nameField>
        <label>Questionnaire Answer Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Answer Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Questionnaire_Question__c.object
<CustomObject>
    <description>A list of Questions on each category.</description>
    <fields>
        <fullName>QQ_Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QQ_Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QQ_Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QQ_Questionnaire_Question_Category__c</fullName>
        <label>Questionnaire Question Category</label>
        <referenceTo>Questionnaire_Question_Category__c</referenceTo>
        <relationshipLabel>Questionnaire Questions</relationshipLabel>
        <relationshipName>Questionnaire_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Q_Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multiple-choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple choice with other text box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple text box choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single-choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single choice with other text box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single choice with text Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Questionnaire Question</label>
    <nameField>
        <displayFormat>QQ-{0000000000}</displayFormat>
        <label>Questionnaire Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Questionnaire_Question_Category__c.object
<CustomObject>
    <description>A list of categories for each question.</description>
    <fields>
        <fullName>QQC_Introduction_Text__c</fullName>
        <label>Introduction Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QQC_Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Live</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QQC_Order__c</fullName>
        <label>Order</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Record Type</label>
        <referenceTo>Record_Type__c</referenceTo>
        <relationshipLabel>Questionnaire Question Categories</relationshipLabel>
        <relationshipName>Questionnaire_Question_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire Question Category</label>
    <nameField>
        <label>Questionnaire Question Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Question Categories</pluralLabel>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Questionnaire Categories</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>H_S</fullName>
        <active>true</active>
        <description>Health &amp; Safty</description>
        <label>H&amp;S</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Record_Type__c.object
<CustomObject>
    <description>Custom Object to maintain opportunity record type</description>
    <label>Record Type</label>
    <nameField>
        <label>Record Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Record Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/ClientQuestionnaireThankYouController.cls
public class ClientQuestionnaireThankYouController{

    public String UrlId  {get; set;}
    Questinnaire__c NewQuestionnaire;
    public Questinnaire__c questnnaire {get;set;}
    List<Questionnaire_Answer__c> SelectedAnswerRec;
    public List<String> QuestionsCategories{get;set;}
    public List<String> QuestionsCategories1{get;set;}
    public Map<String,Decimal> CategoryAnswerPercent{get;set;}
    public List<String> QuenstionCategoryName{get;set;}
    public Map<String,Map<String, AnswerDetailWrapper>> QuesAnsLst{get;set;}
   
    String bookingId;
    String PropertQuesId;
    public String stage {get;set;}
    public String propertyName {get;set;}
    public ClientQuestionnaireThankYouController(){
        try{
            AnswerDetailWrapper ADW1 = new AnswerDetailWrapper();
            List<AnswerDetailWrapper> ADWList = new List<AnswerDetailWrapper>();
            ADWList.add(ADW1);
            CategoriesWrapper CW = new CategoriesWrapper('Test',ADWList);
            UrlId  = APexpages.currentpage().getParameters().get('id');  
            NewQuestionnaire = new Questinnaire__c();
            stage = '';
           
            if(UrlId != null){
                RecordType rt;
               
                String recordtypeName =''; 
                QuestionsCategories = new List<String>();
                QuestionsCategories1 = new List<String>();
                // check for Id param
                if(UrlId.startsWithIgnoreCase('006')){
                    NewQuestionnaire = [select id,Q_Booking__c,Q_Category_Checker__c,Q_Date_of_visit__c,RecordTypeId from Questinnaire__c where Q_Booking__c =:UrlId limit 1];    
                    bookingId = NewQuestionnaire.Q_Booking__c;
                    recordtypeName = 'Client';                
                }
               /* else{
                    PropertQuesId = APexpages.currentpage().getParameters().get('RecId');
                    propertyName = [select id, name from Property__c where id=:UrlId limit 1].name; 
                    if(PropertQuesId != null){
                        questnnaire =  [select id,Q_Booking__c,Q_Category_Checker__c, Q_Audit_By__c, Q_Completed_Date__c, Q_Date_of_visit__c,Q_Stage__c,RecordTypeId from Questinnaire__c where id =:PropertQuesId limit 1];    
                        stage = questnnaire.Q_Stage__c;
                    }
                    recordtypeName = 'H_S';   
                }*/
                
               // rt = [select id from RecordType where sobjectType = 'Questionnaire_Question_Category__c' and developername =:recordtypeName  limit 1];
                
                Map<String,String> QuestionnaireCategoryInfo = new Map<String,String>();
                QuenstionCategoryName = new List<String>();
                
                // get the questionnaire category based on record type.
                for(Questionnaire_Question_Category__c Qc :[select id,name,RecordTypeId,QQC_Live__c,QQC_Order__c,QQC_Introduction_Text__c,Record_Type__r.name
                from Questionnaire_Question_Category__c where Record_Type__r.name =: 'Client' and QQC_Live__c = true order by QQC_Order__c asc]){
                       QuestionnaireCategoryInfo.put(String.valueOf(Qc.id),Qc.name);
                       QuenstionCategoryName.add(Qc.name);
                       
                }
                if(UrlId.startsWithIgnoreCase('006')){
                
                    Double i=Math.ceil(QuestionnaireCategoryInfo.size()/2);
                    Integer k = 0;
                    
                    for(String name : QuenstionCategoryName){
                    
                       if(k<=Math.ceil(QuestionnaireCategoryInfo.size()/2)){
                            QuestionsCategories.add(name);
                        }else{
                            QuestionsCategories1.add(name);
                        }
                        k++;
                    }
                   
                   
                    Map<String,Integer> TotalQ= new Map<String,Integer>();
                    Map<String,Decimal> AnsweredQuesOfCategories = new Map<String,Decimal>();
                    Map<String,Decimal> TotalQuesOfCategories = new Map<String,Decimal>();
                    
                    //Get all answered Question score
                    for(AggregateResult Qa : [select QA_Questionnaire_Question__r.QQ_Questionnaire_Question_Category__c category,sum(QA_Questionnaire_Answer_Option__r.QAO_Score__c) total  
                                                         from Questionnaire_Answer__c
                                                         where QA_Questionnaire__c =:NewQuestionnaire.id and QA_Questionnaire_Answer_Option__c != null
                                                         group by QA_Questionnaire_Question__r.QQ_Questionnaire_Question_Category__c
                                                         ]){
                                                     
                            AnsweredQuesOfCategories.put((String)Qa.get('category'),(Decimal)Qa.get('total'));
                    } 
                    
                    //Get all Questions of Categories
                    
                    List<Questionnaire_Question__c> ClientQuestions = [select id,QQ_Live__c,QQ_Order__c,QQ_Question__c,
                                                                            QQ_Questionnaire_Question_Category__c,Q_Question_Type__c 
                                                                            from Questionnaire_Question__c 
                                                                            where QQ_Questionnaire_Question_Category__c In : QuestionnaireCategoryInfo.keyset() and QQ_Live__c =true order by QQ_Order__c asc];
                    
                    Map<String,List<Questionnaire_Question__c>> CategoryRelatedQuestion = new Map<String,List<Questionnaire_Question__c>>();
                    if(ClientQuestions != null){
                        for(Questionnaire_Question__c QQc : ClientQuestions){
                          
                            if(!CategoryRelatedQuestion.containsKey(QQc.QQ_Questionnaire_Question_Category__c)){
                                CategoryRelatedQuestion.put(QQc.QQ_Questionnaire_Question_Category__c,new List<Questionnaire_Question__c>());
                            }
                            CategoryRelatedQuestion.get(QQc.QQ_Questionnaire_Question_Category__c).add(QQc);
                        }
                            
                        //Map all Questions with highest scored option
                        
                        for(AggregateResult  QQc : [select max(QAO_Score__c) maximum,QAO_Questionnaire_Question__c Question
                                                       from Questionnaire_Answer_Options__c
                                                       where QAO_Questionnaire_Question__r.QQ_Questionnaire_Question_Category__c IN : QuestionnaireCategoryInfo.keyset()  and QAO_Questionnaire_Question__r.Q_Question_Type__c IN('Single-choice','Single choice with text Box')
                                                     group by QAO_Questionnaire_Question__c]){
                                                       
                               TotalQuesOfCategories.put((String)QQc.get('Question'),(Decimal)QQc.get('maximum'));
                        }   
                        system.debug('-----------------kkkkkkk'+TotalQuesOfCategories);
                                                  
                        Map<String,Decimal> CategoryRelatedTotalScore= new Map<String,Decimal>();
                        
                        //Map Maximum Score of each category
                        
                        for(String cr : CategoryRelatedQuestion.keyset()){
                            Decimal temp = 0.0;
                                for(Questionnaire_Question__c qc : CategoryRelatedQuestion.get(cr)){
                                    if(TotalQuesOfCategories.get(qc.id) != null){
                                        temp = temp + TotalQuesOfCategories.get(qc.id);
                                    }
                                }
                            CategoryRelatedTotalScore.put(cr,temp);
                        }
                        
                        CategoryAnswerPercent = new Map<String,Decimal>();
                        
                        for(String cm : QuestionnaireCategoryInfo.keyset()){
                            Decimal val = 0.0;
                            if(AnsweredQuesOfCategories.get(cm) != null && CategoryRelatedTotalScore.get(cm) != null){
                                val = (AnsweredQuesOfCategories.get(cm)/CategoryRelatedTotalScore.get(cm)) * 100;
                            }
                            CategoryAnswerPercent.put(QuestionnaireCategoryInfo.get(cm),val);
                                 
                        }
                        
                   }
               }/***else {
                   
                   
                   //system.assert(false,QuestionnaireList);  
                   List<Questionnaire_Answer__c> AnsweredLst = new List<Questionnaire_Answer__c>();
                   
                   Map<String,List<Questionnaire_Answer__c>> CategoryRelatedAnswers = new Map<String,List<Questionnaire_Answer__c>>();
                   
                   for(Questionnaire_Answer__c Qac : [select id,QA_Answer__c,QA_Other__c,QA_Questionnaire__c,QA_Questionnaire_Answer_Option__r.Name,
                                                       QA_Questionnaire_Question__r.QQ_Question__c,QA_Questionnaire_Question__r.QQ_Questionnaire_Question_Category__c,
                                                       QA_Questionnaire_Answer_Option__r.QAO_Score__c,QA_Questionnaire_Question__r.QQ_Order__c,QA_Questionnaire_Question__r.Q_Question_Type__c from Questionnaire_Answer__c where QA_Questionnaire__c =:PropertQuesId order by QA_Questionnaire_Question__r.QQ_Order__c asc]){
                                                       
                       if(!CategoryRelatedAnswers.containsKey(String.valueOf(Qac.QA_Questionnaire_Question__r.QQ_Questionnaire_Question_Category__c))){
                           CategoryRelatedAnswers.put(Qac.QA_Questionnaire_Question__r.QQ_Questionnaire_Question_Category__c,new List<Questionnaire_Answer__c>());
                       }
                       CategoryRelatedAnswers.get(Qac.QA_Questionnaire_Question__r.QQ_Questionnaire_Question_Category__c).add(Qac);
                       
                   }
                  QuesAnsLst = new Map<String,Map<String, AnswerDetailWrapper>>();
                  
                  for(String Qcc : QuestionnaireCategoryInfo.keyset()){
                     
                      QuesAnsLst.put(QuestionnaireCategoryInfo.get(Qcc),new Map<String,AnswerDetailWrapper>());
                       if(CategoryRelatedAnswers.get(Qcc) != null){
                          
                           //CategoriesWrapper cw  = new CategoriesWrapper(QuestionnaireCategoryInfo.get(Qcc),new List<AnswerDetailWrapper>());
                           //List<AnswerDetailWrapper> tempAnswerLst = new List<AnswerDetailWrapper>();
                           system.debug('Question *****   '+ CategoryRelatedAnswers.get(Qcc));
                           for(Questionnaire_Answer__c Qac: CategoryRelatedAnswers.get(Qcc)){
                               
                               AnswerDetailWrapper adw = new AnswerDetailWrapper();
                               if(Qac.QA_Questionnaire_Question__r.QQ_Question__c != null){
                                   adw.Question = Qac.QA_Questionnaire_Question__r.QQ_Question__c;
                               }
                               
                               if(Qac.QA_Questionnaire_Answer_Option__r.Name != null){
                                   adw.SelectedAnswer = Qac.QA_Questionnaire_Answer_Option__r.Name;
                               }
                               if(Qac.QA_Questionnaire_Question__r.Q_Question_Type__c == 'Multiple-choice'){
                                    adw.SelectedAnswer = Qac.QA_Answer__c;
                               }
                               if(Qac.QA_Questionnaire_Question__r.Q_Question_Type__c == 'Multiple choice with other text box'){
                                    adw.SelectedAnswer = Qac.QA_Answer__c;
                                    if(Qac.QA_Other__c != null){
                                       adw.Comment = Qac.QA_Other__c;
                                    }
                               }
                               if(Qac.QA_Questionnaire_Question__r.Q_Question_Type__c == 'Text'){
                                    adw.SelectedAnswer = Qac.QA_Answer__c;
                                    
                               }
                               if(Qac.QA_Questionnaire_Question__r.Q_Question_Type__c == 'Single choice with text Box'){
                                     if(Qac.QA_Answer__c != null){
                                           adw.Comment = Qac.QA_Answer__c;
                                     }
                                    
                                    
                               }
                              /* if(Qac.QA_Answer__c != null){
                                   adw.Comment = Qac.QA_Answer__c;
                               }
                               
                               if(Qac.QA_Other__c != null){
                                   adw.Comment = Qac.QA_Other__c;
                               }*/
                               
                              /* if(Qac.QA_Questionnaire_Answer_Option__r.QAO_Score__c != null){
                                   adw.Score = Qac.QA_Questionnaire_Answer_Option__r.QAO_Score__c;
                               }
                               System.debug('############ Cata'+Qcc);
                               
                               QuesAnsLst.get(QuestionnaireCategoryInfo.get(Qcc)).put(Qac.QA_Questionnaire_Question__c, adw);
                               //tempAnswerLst.add(adw);
                           }
                           
                           //QuesAnsLst.get(QuestionnaireCategoryInfo.get(Qcc)).addAll(tempAnswerLst);
                       }
                      
                   }
               }***/
            }
        }catch(Exception e){       
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()+' On Line Number :: '+e.getLineNumber());            
            ApexPages.addMessage(myMsg);
        }
    }
    
    public void updateBooking(){
        if(bookingId != null){
            List<Opportunity> lstOpp = new List<Opportunity>(); 
            for(Opportunity opp : [Select Id,O_Questionnaire_Completed__c from Opportunity where Id = :bookingId]){
                opp.O_Questionnaire_Completed__c = true;
                lstOpp.add(opp);
            }
            update lstOpp;
        }
    }
    
   
    
    public class CategoriesWrapper{
        public String Category{get;set;}
        public List<AnswerDetailWrapper> QuestinnaireQues{get;set;}
        CategoriesWrapper(String Category, List<AnswerDetailWrapper> QuestinnaireQues){
            this.Category = Category;
            this.QuestinnaireQues = QuestinnaireQues;
        }
    }
    public class AnswerDetailWrapper{
        
        public String Question{get;set;}
        public String SelectedAnswer{get;set;}
        public String  Comment{get;set;}
        public Decimal Score{get;set;}
        public AnswerDetailWrapper(){
                Question = '';
                SelectedAnswer = '';
                Comment = '';
                Score = 0.0;
        }        
    }  
    
                            
}