Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>O_Service_From_Date__c</fullName>
        <label>Service From Date</label>
        <type>Date</type>
    </fields>
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <fields>
        <fullName>S_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Accommodation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Hire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taxi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tourist Board</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Cost_Payment__c.object
<CustomObject>
    <fields>
        <fullName>SCP_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Costs &amp; Payments</relationshipLabel>
        <relationshipName>Supplier_Cost_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCP_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Costs &amp; Payments</relationshipLabel>
        <relationshipName>Supplier_Cost_payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Cost &amp; Payment</label>
    <nameField>
        <displayFormat>SCP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs &amp; Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Payment__c.object
<CustomObject>
    <fields>
        <fullName>P_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBP_Supplier_Cost_Currency_Value__c</fullName>
        <label>Supplier Cost Currency Value</label>
        <referenceTo>Supplier_Cost_Payment__c</referenceTo>
        <relationshipLabel>Supplier_Payments</relationshipLabel>
        <relationshipName>Supplier_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SP_Supplier__c</fullName>
        <formula>SBP_Supplier_Cost_Currency_Value__r.SCP_Supplier__c</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SP_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Supplier Payment</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier_Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Payment_Rule__c.object
<CustomObject>
    <description>For None Guarantee Contracts ONLY and Automatically queuing the supplier payment</description>
    <fields>
        <fullName>Percent_Value__c</fullName>
        <inlineHelpText>Is the amount percentage or value?</inlineHelpText>
        <label>Percent / Value</label>
        <picklist>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SPR_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SPR_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPR_Balance_Due_Date__c</fullName>
        <inlineHelpText>If payment is due on a specific date, insert date here</inlineHelpText>
        <label>Balance Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Balance_Due_Day__c</fullName>
        <inlineHelpText>+/- number of days</inlineHelpText>
        <label>Balance Due Day</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPR_Confirmation_From_Date__c</fullName>
        <inlineHelpText>Booking Confirmation From Date</inlineHelpText>
        <label>Confirmation From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Confirmation_To_Date__c</fullName>
        <inlineHelpText>Booking Confirmation To Date (inclusive)</inlineHelpText>
        <label>Confirmation To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Deposit_Due_Date__c</fullName>
        <inlineHelpText>Need to pay at a specific date</inlineHelpText>
        <label>Deposit Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Deposit_Due_Day__c</fullName>
        <inlineHelpText>+/- Number of days</inlineHelpText>
        <label>Deposit Due Day</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPR_Deposit_Due__c</fullName>
        <description>When should the payment be made?</description>
        <inlineHelpText>When should the payment be made?</inlineHelpText>
        <label>Deposit Due</label>
        <picklist>
            <picklistValues>
                <fullName>At Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Month of Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specific Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SPR_Notify__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Can we have a &apos;notify accounts&apos; flag (see above) in the payment record. If this is set to yes the system would add this payment to the Accounts Team &apos;tasks&apos; 4 days before the due date i.e. if due 7 days before the service date then it would notify accounts 11 days before.</description>
        <inlineHelpText>When ticked a task will be created for Account Team 4 days before the due date. (Only use if payment is due before the end of a month)</inlineHelpText>
        <label>Notify for Deposit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SPR_Notify_for_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When ticked a task will be created for Account Team 4 days before the due date. (Only use if payment is not at the end of a month)</inlineHelpText>
        <label>Notify for Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SPR_Service_From_Date__c</fullName>
        <inlineHelpText>Service Date Range Start Date</inlineHelpText>
        <label>Service From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Service_To_Date__c</fullName>
        <label>Service To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Supplier_Payment_Due_Type__c</fullName>
        <inlineHelpText>When is the payment due?</inlineHelpText>
        <label>Supplier Payment Due Type</label>
        <picklist>
            <picklistValues>
                <fullName>At Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Month after Serv Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specific Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SPR_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>In the future this may be used for none property based rules such as Transfer and Taxi providers etc..</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipName>Supplier_Payment_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Payment Rule</label>
    <nameField>
        <displayFormat>SPR-{0000000000}</displayFormat>
        <label>Supplier Payment Rule No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Payment Rules</pluralLabel>
    <recordTypes>
        <fullName>Balance</fullName>
        <active>true</active>
        <description>Balance</description>
        <label>Balance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <description>Deposit</description>
        <label>Deposit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/SupplierPaymentServicesTest.cls
@isTest
private class SupplierPaymentServicesTest{
@testSetup
    static void testData(){
        String RecordtypeId1 = [Select id, Name from Recordtype where (name='Deposit') AND SObjectType = 'Supplier_Payment_Rule__c'].id;
        String RecordtypeId2 = [Select id, Name from Recordtype where (name='Balance') AND SObjectType = 'Supplier_Payment_Rule__c'].id;
        
        Account A = new Account(Name='Test');
        insert A;
        System.assert(A.Id != null);
        
        Supplier__c SpObj = new Supplier__c(Name='Test', S_Type__c='Flight');
        Insert SpObj;
        system.assert(SpObj.Id != null);
        
        Opportunity Opp = new Opportunity(Name='Test Op',AccountId=A.Id,StageName='Available',O_Booking_Date__c=System.Today().addDays(-20),O_Service_From_Date__c=System.Today().addDays(-18),
                                       CloseDate=System.Today().addDays(30));
        Insert Opp;
        System.assert(Opp.Id != null);
        
        Supplier_Cost_Payment__c SCP1 = new Supplier_Cost_Payment__c(SCP_Opportunity__c=Opp.Id, SCP_Supplier__c=SpObj.Id);
        Insert SCP1;
        System.assert(SCP1.Id != null);
        
        Supplier_Cost_Payment__c SCP2 = new Supplier_Cost_Payment__c(SCP_Opportunity__c=Opp.Id, SCP_Supplier__c=SpObj.Id);
        Insert SCP2;
        System.assert(SCP2.Id != null);
        
        Supplier_Booking__c SB1 = new Supplier_Booking__c(SB_Opportunity__c=Opp.Id/*, SB_Supplier_Cost_and_Payment__c=SCP1.Id,SB_Sell__c=100*/);
        insert SB1;
        System.assert(SB1.Id != null);
        
        Supplier_Booking__c SB2 = new Supplier_Booking__c(SB_Opportunity__c=Opp.Id/*, SB_Supplier_Cost_and_Payment__c=SCP2.Id,SB_Sell__c=100*/);
        insert SB2;
        System.assert(SB2.Id != null);
        
        Supplier_Payment_Rule__c spr1 = new Supplier_Payment_Rule__c(SPR_Amount__c=10,SPR_Balance_Due_Date__c=System.Today().addDays(-20),SPR_Balance_Due_Day__c=20,SPR_Confirmation_From_Date__c=System.Today().addDays(-20),
                                       SPR_Confirmation_To_Date__c=System.Today().addDays(20),SPR_Deposit_Due__c='At Confirmation',SPR_Deposit_Due_Date__c=System.Today().addDays(-10),SPR_Deposit_Due_Day__c=10,SPR_Notify_for_Balance__c=true,
                                       SPR_Notify__c=true,Percent_Value__c='value', SPR_Service_From_Date__c=System.Today().addDays(-100),SPR_Service_To_Date__c=System.Today().addDays(100),
                                       SPR_Supplier__c=SpObj.id,SPR_Supplier_Payment_Due_Type__c='At Confirmation',SPR_Active__c=true,RecordtypeId=RecordtypeId1);
        insert spr1;
        System.assert(spr1.Id != null);
        Supplier_Payment_Rule__c spr2 = new Supplier_Payment_Rule__c(SPR_Amount__c=10,SPR_Balance_Due_Date__c=System.Today().addDays(-20),SPR_Balance_Due_Day__c=20,SPR_Confirmation_From_Date__c=System.Today().addDays(-20),
                                       SPR_Confirmation_To_Date__c=System.Today().addDays(20),SPR_Deposit_Due__c='At Confirmation',SPR_Deposit_Due_Date__c=System.Today().addDays(-10),SPR_Deposit_Due_Day__c=10,SPR_Notify_for_Balance__c=true,
                                       SPR_Notify__c=true,Percent_Value__c='Percent', SPR_Service_From_Date__c=System.Today().addDays(-100),SPR_Service_To_Date__c=System.Today().addDays(100),
                                       SPR_Supplier__c=SpObj.id,SPR_Supplier_Payment_Due_Type__c='Specific Date',SPR_Active__c=true,RecordtypeId=RecordtypeId2);
        insert spr2;
        System.assert(spr2.Id != null);
        
        Supplier_Payment__c SP1 = new Supplier_Payment__c(SBP_Supplier_Cost_Currency_Value__c=SCP1.id,/*SP_Supplier__c=SpObj.id,*/P_Amount__c=100,SP_Type__c='Deposit');
        insert SP1;
        System.assert(Sp1.Id != null);
        
        Supplier_Payment__c SP2 = new Supplier_Payment__c(SBP_Supplier_Cost_Currency_Value__c=SCP1.id,/*SP_Supplier__c=SpObj.id,*/P_Amount__c=100,SP_Type__c='Balance');
        insert SP2;
        System.assert(Sp2.Id != null);
    }
    static testMethod void testisrefresh() {
        Opportunity opp = [select Id,StageName,Name,O_Booking_Date__c,O_Service_From_Date__c FROM Opportunity LIMIT 1];
        Supplier_Payment_Rule__c spr = [Select Id,SPR_Deposit_Due__c,SPR_Supplier_Payment_Due_Type__c from Supplier_Payment_Rule__c where recordtype.name='Balance' limit 1];
        List<opportunity> lstopp = [select Id FROM Opportunity LIMIT 1];
        Opportunity newOpp = new Opportunity();
        Test.StartTest();
        SupplierPaymentServices spsObj1 = new SupplierPaymentServices();
        SupplierPaymentServices.createSupplierPayments(new Set<Id>{lstopp[0].id});
        SupplierPaymentServices spsObj2 = new SupplierPaymentServices();
        SupplierPaymentServices.createSupplierPayments(new Set<Id>{lstopp[0].id});
        SupplierPaymentServices.isBookedRecently(newOpp,opp);
        SupplierPaymentServices.isBooked(newOpp);
        SupplierPaymentServices.isRefresh = true;
        SupplierPaymentServices.createSupplierPayments(new Set<Id>{lstopp[0].id});
        Test.StopTest();   
    }
}