Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>O_Service_From_Date__c</fullName>
        <label>Service From Date</label>
        <type>Date</type>
    </fields>
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <fields>
        <fullName>S_Payment_From_Bank_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment From Bank Account</label>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>Suppliers</relationshipLabel>
        <relationshipName>Suppliers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>S_Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Bank_Detail__c.object
<CustomObject>
    <description>A list of bank details used by suppliers</description>
    <fields>
        <fullName>SBD_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBD_Supplier__c</fullName>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Bank Details</relationshipLabel>
        <relationshipName>Supplier_Bank_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supplier Bank Detail</label>
    <nameField>
        <displayFormat>SBD-{0000000000}</displayFormat>
        <label>Supplier Bank Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Bank Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Cost_Payment__c.object
<CustomObject>
    <fields>
        <fullName>SCP_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Costs &amp; Payments</relationshipLabel>
        <relationshipName>Supplier_Cost_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCP_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Supplier Costs &amp; Payments</relationshipLabel>
        <relationshipName>Supplier_Cost_payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCP_Total_Payment__c</fullName>
        <label>Total Payment</label>
        <summarizedField>Supplier_Payment__c.P_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Supplier_Payment__c.SP_Payment_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Supplier_Payment__c.SBP_Supplier_Cost_Currency_Value__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Supplier Cost &amp; Payment</label>
    <nameField>
        <displayFormat>SCP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Costs &amp; Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Payment__c.object
<CustomObject>
    <fields>
        <fullName>P_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBP_Supplier_Cost_Currency_Value__c</fullName>
        <label>Supplier Cost Currency Value</label>
        <referenceTo>Supplier_Cost_Payment__c</referenceTo>
        <relationshipLabel>Supplier_Payments</relationshipLabel>
        <relationshipName>Supplier_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SP_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Supplier Payments</relationshipLabel>
        <relationshipName>Supplier_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SP_Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SP_Order__c</fullName>
        <formula>CASE(TEXT(SP_Type__c),
     &apos;Deposit&apos;, 1,
     &apos;Balance&apos;, 2,
     3
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SP_Payment_From_Bank_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment From Bank Account</label>
        <referenceTo>Bank_Account__c</referenceTo>
        <relationshipLabel>Supplier_Payments</relationshipLabel>
        <relationshipName>Supplier_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SP_Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Bank Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cheque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SP_Supplier_Payment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Payment Rule</label>
        <referenceTo>Supplier_Payment_Rule__c</referenceTo>
        <relationshipLabel>Supplier_Payments</relationshipLabel>
        <relationshipName>Supplier_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SP_Supplier__c</fullName>
        <formula>SBP_Supplier_Cost_Currency_Value__r.SCP_Supplier__c</formula>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SP_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Supplier Payment</label>
    <nameField>
        <displayFormat>SP-{0000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier_Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Payment_Rule__c.object
<CustomObject>
    <description>For None Guarantee Contracts ONLY and Automatically queuing the supplier payment</description>
    <fields>
        <fullName>Percent_Value__c</fullName>
        <inlineHelpText>Is the amount percentage or value?</inlineHelpText>
        <label>Percent / Value</label>
        <picklist>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SPR_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SPR_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPR_Balance_Due_Date__c</fullName>
        <inlineHelpText>If payment is due on a specific date, insert date here</inlineHelpText>
        <label>Balance Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Balance_Due_Day__c</fullName>
        <inlineHelpText>+/- number of days</inlineHelpText>
        <label>Balance Due Day</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPR_Confirmation_From_Date__c</fullName>
        <inlineHelpText>Booking Confirmation From Date</inlineHelpText>
        <label>Confirmation From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Confirmation_To_Date__c</fullName>
        <inlineHelpText>Booking Confirmation To Date (inclusive)</inlineHelpText>
        <label>Confirmation To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Deposit_Due_Date__c</fullName>
        <inlineHelpText>Need to pay at a specific date</inlineHelpText>
        <label>Deposit Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Deposit_Due_Day__c</fullName>
        <inlineHelpText>+/- Number of days</inlineHelpText>
        <label>Deposit Due Day</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPR_Deposit_Due__c</fullName>
        <description>When should the payment be made?</description>
        <inlineHelpText>When should the payment be made?</inlineHelpText>
        <label>Deposit Due</label>
        <picklist>
            <picklistValues>
                <fullName>At Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Month of Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specific Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SPR_Notify__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Can we have a &apos;notify accounts&apos; flag (see above) in the payment record. If this is set to yes the system would add this payment to the Accounts Team &apos;tasks&apos; 4 days before the due date i.e. if due 7 days before the service date then it would notify accounts 11 days before.</description>
        <inlineHelpText>When ticked a task will be created for Account Team 4 days before the due date. (Only use if payment is due before the end of a month)</inlineHelpText>
        <label>Notify for Deposit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SPR_Notify_for_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When ticked a task will be created for Account Team 4 days before the due date. (Only use if payment is not at the end of a month)</inlineHelpText>
        <label>Notify for Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SPR_Rule_Execution_Order__c</fullName>
        <formula>CASE( RecordType.Name, 
      &apos;Deposit&apos;, 1, 
      &apos;Balance&apos;, 2, 
      3
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rule Execution Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPR_Service_From_Date__c</fullName>
        <inlineHelpText>Service Date Range Start Date</inlineHelpText>
        <label>Service From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Service_To_Date__c</fullName>
        <label>Service To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPR_Supplier_Payment_Due_Type__c</fullName>
        <inlineHelpText>When is the payment due?</inlineHelpText>
        <label>Supplier Payment Due Type</label>
        <picklist>
            <picklistValues>
                <fullName>At Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Month after Serv Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specific Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SPR_Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>In the future this may be used for none property based rules such as Transfer and Taxi providers etc..</description>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipName>Supplier_Payment_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Payment Rule</label>
    <nameField>
        <displayFormat>SPR-{0000000000}</displayFormat>
        <label>Supplier Payment Rule No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Payment Rules</pluralLabel>
    <recordTypes>
        <fullName>Balance</fullName>
        <active>true</active>
        <description>Balance</description>
        <label>Balance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <description>Deposit</description>
        <label>Deposit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/SupplierPaymentServices.cls
/************************************************************************************************
*        Name           : SupplierPaymentServices
*        Author         : Naval Sharma (naval.sharma@purple-vision.com)
*        Date           : 11th August 2016
*        Description    : This Service class used to automate creation of supplier payment 
*                         records when an opportunty is booked
*************************************************************************************************/

public without sharing class SupplierPaymentServices{
    
    //Set to true while updating Balance Supplier Payment records
    public static boolean isRefresh = false;
    
    /** Method to create supplier payments for provided set of opportunities ***/
    public static void createSupplierPayments(Set<Id> setBookedOppIds){
        
        try{
            //Get supplier rules for all the supplier which are part of these bookings
            Map<String, List<Supplier_Payment_Rule__c>> mapSupplierPaymentRules = new Map<String, List<Supplier_Payment_Rule__c>>();
            
            Map<String, Map<String, Map<String, Supplier_Payment__c>>> mapOppSCPToSupplierPaymentsExist = new Map<String, Map<String, Map<String, Supplier_Payment__c>>>();
            
            Map<String, Supplier_Bank_Detail__c> mapSupplierToBankDetail = new Map<String, Supplier_Bank_Detail__c>();
            
            //Get Supplier Payment Invoice Record Type so we can create the Invoice Supplier Payments 
            //RecordType supplierPaymentInvoiceRT = [SELECT Id FROM RecordType WHERE sObjectType = 'Supplier_Payment__c' AND RecordType.Name = 'Invoice' Limit 1];
            
            //Query opportunity with related Supplier Payment Cost and Supplier Payment records 
            List<Opportunity> lstOpportunities = [SELECT Id, O_Booking_Date__c, O_Service_From_Date__c,   
                                                 (SELECT Id, SBP_Supplier_Cost_Currency_Value__c, SP_Booking__c, P_Amount__c, SP_Type__c FROM Supplier_Payments__r /*WHERE RecordTypeId = :supplierPaymentInvoiceRT.Id*/ ORDER BY SP_Order__c),
                                                 (SELECT Id, SCP_Supplier__c, SCP_Supplier__r.S_Payment_Method__c, SCP_Supplier__r.S_Payment_From_Bank_Account__c, SCP_Total_Payment__c FROM Supplier_Cost_Payments__r)  
                                                 FROM Opportunity WHERE Id in :setBookedOppIds];
            System.debug('####### List of opportunities ########## ' + lstOpportunities);
            
            //Get the suppliers which have been used in the bookings
            for(Opportunity opp : lstOpportunities){
                
                //Check for Opportunity key exist in the Map
                if(!mapOppSCPToSupplierPaymentsExist.containsKey(opp.Id))
                    mapOppSCPToSupplierPaymentsExist.put(opp.Id, new Map<String, Map<String, Supplier_Payment__c>>());
                    
                for(Supplier_Cost_Payment__c scp : opp.Supplier_Cost_Payments__r){
                    
                    //Intialize mapSupplierPaymentRules map with the supplier Ids 
                    //so we can query the supplier rules for the each supplier
                    if(!mapSupplierPaymentRules.containsKey(scp.SCP_Supplier__c))
                        mapSupplierPaymentRules.put(scp.SCP_Supplier__c, new List<Supplier_Payment_Rule__c>());        
                        
                    //Intialize mapOppToSupplierPayments map's opportunities with the supplier cost and payment ids 
                    //so we can create the supplier payment for each supplier cost and payment         
                    if(!mapOppSCPToSupplierPaymentsExist.get(opp.Id).containsKey(scp.Id))
                        mapOppSCPToSupplierPaymentsExist.get(opp.Id).put(scp.Id, new Map<String, Supplier_Payment__c>());  
                      
                }
                
                //Get all the supplier payments created for the each supplier cost and payment record
                for(Supplier_Payment__c sp : opp.Supplier_Payments__r){
                                              
                     mapOppSCPToSupplierPaymentsExist.get(sp.SP_Booking__c).get(sp.SBP_Supplier_Cost_Currency_Value__c).put(sp.SP_Type__c, sp);
                }
            }
            
            //Fetch all the found supplier's Supplier_Payment_Rule__c and associate them with the relevent supplier
            for(Supplier_Payment_Rule__c spr : [SELECT Id, SPR_Amount__c, SPR_Balance_Due_Date__c, SPR_Balance_Due_Day__c, SPR_Confirmation_From_Date__c, SPR_Confirmation_To_Date__c, 
                                                SPR_Deposit_Due__c, SPR_Deposit_Due_Date__c, SPR_Deposit_Due_Day__c, SPR_Notify_for_Balance__c, SPR_Notify__c, Percent_Value__c, 
                                                SPR_Service_From_Date__c, SPR_Service_To_Date__c, SPR_Supplier__c,SPR_Supplier_Payment_Due_Type__c, SPR_Active__c,
                                                RecordType.Name    
                                                FROM Supplier_Payment_Rule__c 
                                                WHERE SPR_Supplier__c IN : mapSupplierPaymentRules.keySet()
                                                ORDER BY SPR_Rule_Execution_Order__c]){
                
                mapSupplierPaymentRules.get(spr.SPR_Supplier__c).add(spr);
            }
            System.debug('####### Supplier Payment Rules ########## ' + mapSupplierPaymentRules);
            
            //Fetch Bank details of all the suppliers
            for(Supplier_Bank_Detail__c sbd : [SELECT Id, SBD_Supplier__c FROM Supplier_Bank_Detail__c WHERE SBD_Supplier__c IN :mapSupplierPaymentRules.keySet() AND SBD_Primary__c = TRUE]){
                
                mapSupplierToBankDetail.put(sbd.SBD_Supplier__c, sbd);
            }

            //Now create supplier payment for each supplier cost & payment record based on the supplier rule
            Map<String, Map<String, Supplier_Payment__c>> mapSCPNewSupplierPayments = new Map<String, Map<String, Supplier_Payment__c>>();
            
            for(Opportunity opp : lstOpportunities){
                
                //Iterate over Supplier Cost and Payment records for this opportunity
                for(Supplier_Cost_Payment__c scp : opp.Supplier_Cost_Payments__r){
                    
                    //Iterate over the supplier payment rules
                    for(Supplier_Payment_Rule__c rule : mapSupplierPaymentRules.get(scp.SCP_Supplier__c)){

                        //Check for supplier cost and payment's opportunity booking and service date
                        if(mapSupplierPaymentRules.containsKey(scp.SCP_Supplier__c) && 
                           opp.O_Booking_Date__c >= rule.SPR_Confirmation_From_Date__c && 
                           opp.O_Booking_Date__c <= rule.SPR_Confirmation_To_Date__c && 
                           opp.O_Service_From_Date__c >= rule.SPR_Service_From_Date__c &&
                           opp.O_Service_From_Date__c <= rule.SPR_Service_To_Date__c &&
                           rule.SPR_Active__c 
                        ){
                            //Check if supplier payment record has already been created for the opportunity, if not then create the records
                            if(mapOppSCPToSupplierPaymentsExist.get(opp.Id).get(scp.Id).isEmpty()){
                                
                                if(!mapSCPNewSupplierPayments.containsKey(scp.Id)){
                                
                                    mapSCPNewSupplierPayments.put(scp.Id, new Map<String, Supplier_Payment__c>());
                                }
                                
                                //Check that there is no supplier payment is created for this supplier cost and payment record
                                if(!mapSCPNewSupplierPayments.get(scp.Id).containsKey(rule.RecordType.Name)){
                                    
                                    String bankDetailsRecordId = mapSupplierToBankDetail.containsKey(scp.SCP_Supplier__c) ? mapSupplierToBankDetail.get(scp.SCP_Supplier__c).Id : NULL;
                                    Decimal depositAmount = mapSCPNewSupplierPayments.get(scp.Id).containsKey('Deposit') ? mapSCPNewSupplierPayments.get(scp.Id).get('Deposit').P_Amount__c : 0;
                                    Supplier_Payment__c payment = SupplierPaymentServices.getSupplierPayment(opp, scp, rule,/* supplierPaymentInvoiceRT,*/ bankDetailsRecordId, depositAmount);
                                    
                                    mapSCPNewSupplierPayments.get(scp.Id).put(rule.RecordType.Name, payment);
                                }
                            }
                            else{
                                
                                if(!mapSCPNewSupplierPayments.containsKey(scp.Id)){
                                
                                    mapSCPNewSupplierPayments.put(scp.Id, new Map<String, Supplier_Payment__c>());
                                }
                                //Check there should not be existing supplier payment for this opportunity's supplier 
                                if(!mapOppSCPToSupplierPaymentsExist.get(opp.Id).get(scp.Id).containsKey(rule.RecordType.Name)){
                                    
                                    if(!mapSCPNewSupplierPayments.get(scp.Id).containsKey(rule.RecordType.Name)){
                                        
                                        String bankDetailsRecordId = mapSupplierToBankDetail.containsKey(scp.SCP_Supplier__c) ? mapSupplierToBankDetail.get(scp.SCP_Supplier__c).Id : NULL;
                                        Decimal depositAmount = 0;
                                        if(mapOppSCPToSupplierPaymentsExist.get(opp.Id).get(scp.Id).containsKey('Deposit'))
                                            depositAmount = mapOppSCPToSupplierPaymentsExist.get(opp.Id).get(scp.Id).get('Deposit').P_Amount__c;
                                        else
                                            depositAmount = mapSCPNewSupplierPayments.get(scp.Id).containsKey('Deposit') ? mapSCPNewSupplierPayments.get(scp.Id).get('Deposit').P_Amount__c : 0;
                                        
                                        Supplier_Payment__c payment = SupplierPaymentServices.getSupplierPayment(opp, scp, rule/*, supplierPaymentInvoiceRT*/, bankDetailsRecordId, depositAmount);
                                        
                                        mapSCPNewSupplierPayments.get(scp.Id).put(rule.RecordType.Name, payment);
                                    }
                                }
                                else{
                                    //Logic to update existing balance supplier payment
                                    System.debug('####### Is Refresh ########## ' + isRefresh);
                                    if(isRefresh && rule.RecordType.Name == 'Balance'){
                                    
                                        String bankDetailsRecordId = mapSupplierToBankDetail.containsKey(scp.SCP_Supplier__c) ? mapSupplierToBankDetail.get(scp.SCP_Supplier__c).Id : NULL;
                                        Decimal depositAmount = 0;
                                        if(mapOppSCPToSupplierPaymentsExist.get(opp.Id).get(scp.Id).containsKey('Deposit'))
                                            depositAmount = mapOppSCPToSupplierPaymentsExist.get(opp.Id).get(scp.Id).get('Deposit').P_Amount__c;
                                        else
                                            depositAmount = mapSCPNewSupplierPayments.get(scp.Id).containsKey('Deposit') ? mapSCPNewSupplierPayments.get(scp.Id).get('Deposit').P_Amount__c : 0;
                                        
                                        Supplier_Payment__c payment = SupplierPaymentServices.getSupplierPayment(opp, scp, rule/*, supplierPaymentInvoiceRT*/, bankDetailsRecordId, depositAmount);
                                        payment.Id = mapOppSCPToSupplierPaymentsExist.get(opp.Id).get(scp.Id).get('Balance').Id;
                                        
                                        mapSCPNewSupplierPayments.get(scp.Id).put(rule.RecordType.Name, payment);        
                                    }
                                }
                            }
                        }
                    }        
                }    
            }
            System.debug('####### Created Supplier Payments ########## ' + mapSCPNewSupplierPayments);

            //Create a list of supplier payment records to insert
            List<Supplier_Payment__c> lstSupplierPayments = new List<Supplier_Payment__c>();
            for(String key : mapSCPNewSupplierPayments.keySet()){
                
                lstSupplierPayments.addAll(mapSCPNewSupplierPayments.get(key).values());        
            }
            
            if(!lstSupplierPayments.isEmpty())
                upsert lstSupplierPayments;
        }
        catch(Exception e){
            System.assert(false, e.getLineNumber() + ' : ' + e.getMessage());
        } 
    }     
    
    
    /**** Method to create supplier payment based on the pre set of conditions  *****/
    public static Supplier_Payment__c getSupplierPayment(Opportunity opp, Supplier_Cost_Payment__c scp, Supplier_Payment_Rule__c rule/*, RecordType supplierPaymentInvoiceRT*/, String bankDetailsRecordId, Decimal depositAmount){
            
        Supplier_Payment__c payment = new Supplier_Payment__c(SP_Booking__c = opp.Id, /*SP_Supplier__c = scp.SCP_Supplier__c, */
                                                              SBP_Supplier_Cost_Currency_Value__c = scp.Id/*, 
                                                              RecordTypeId = supplierPaymentInvoiceRT.Id*/);
        
        //At Confirmation which means Due Date is Opportunity Booking Date
        if(rule.SPR_Supplier_Payment_Due_Type__c == 'At Confirmation')
            payment.SP_Due_Date__c = opp.O_Booking_Date__c;
        
        //End of Month after Service Date which means last day of the Month(Opportunity Service Date)
        else if(rule.SPR_Supplier_Payment_Due_Type__c == 'End of Month after Serv Date')  
            payment.SP_Due_Date__c = opp.O_Service_From_Date__c.addMonths(1).toStartofMonth().addDays(-1);  
        
        //Service Date which means Service From Date
        else if(rule.SPR_Supplier_Payment_Due_Type__c == 'Service Date') 
            payment.SP_Due_Date__c = opp.O_Service_From_Date__c;
        
        //Specific Date which is based on Due Date (date field) or Due Day which is + or - x number of days based on the Service Date  
        else if(rule.SPR_Supplier_Payment_Due_Type__c == 'Specific Date'){ 
            
            if(rule.SPR_Deposit_Due_Date__c != NULL)
                payment.SP_Due_Date__c = rule.SPR_Deposit_Due_Date__c;
            else
                payment.SP_Due_Date__c = opp.O_Service_From_Date__c.addDays(rule.SPR_Deposit_Due_Day__c!= NULL ? Integer.valueOf(rule.SPR_Deposit_Due_Day__c) : 0);
        }
        
        //Set all other essential field values
        //payment.SP_Supplier_Bank_Details__c = bankDetailsRecordId;
        payment.SP_Payment_Method__c = scp.SCP_Supplier__r.S_Payment_Method__c;
        payment.SP_Payment_From_Bank_Account__c = scp.SCP_Supplier__r.S_Payment_From_Bank_Account__c;
        payment.SP_Supplier_Payment_Rule__c = rule.Id;
        payment.SP_Booking__c = opp.Id;
        payment.SBP_Supplier_Cost_Currency_Value__c= scp.Id;
        //payment.SP_Serv_Date__c = opp.O_Service_From_Date__c;
        payment.SP_Type__c = rule.RecordType.Name;
        
        //Set the amount value based on the rule record type
        if(rule.RecordType.Name == 'Deposit')
            payment.P_Amount__c = rule.Percent_Value__c == 'Value' ? rule.SPR_Amount__c : scp.SCP_Total_Payment__c * rule.SPR_Amount__c / 100;
        else
            payment.P_Amount__c = scp.SCP_Total_Payment__c - depositAmount;
            
        return payment;
    }  
    
    
    public static boolean isBookedRecently(Opportunity newOpp, Opportunity oldOpp){
        if(oldOpp.StageName != 'Confirmed Booking' && oldOpp.StageName != 'Confirmed Web Booking' && oldOpp.StageName != 'Booked' && oldOpp.StageName != 'Web Booking')
            return (newOpp.StageName == 'Confirmed Booking' || newOpp.StageName == 'Confirmed Web Booking' || newOpp.StageName == 'Booked' || newOpp.StageName == 'Web Booking');
        return false;    
        
    }
    
    public static boolean isBooked(Opportunity newOpp){
        return (newOpp.StageName == 'Confirmed Booking' || newOpp.StageName == 'Confirmed Web Booking' || newOpp.StageName == 'Booked' || newOpp.StageName == 'Web Booking');
        
    }
}