Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Charity__c</fullName>
        <label>Charity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Destination__c</fullName>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Reference_Number__c</fullName>
        <label>Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Questinnaire__c.object
<CustomObject>
    <description>Client and HS Questionnaire</description>
    <fields>
        <fullName>Q_Audit_By__c</fullName>
        <label>Audit By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Q_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Q_Category_Checker__c</fullName>
        <label>Category Checker</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q_Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Q_Date_of_visit__c</fullName>
        <description>This is for HS Questionnaire</description>
        <label>Date of visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Q_Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StatusNA__c</fullName>
        <label>StatusNA</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>Q-{0000000000}</displayFormat>
        <label>Questinnaire ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Questionnaire</description>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>H_S</fullName>
        <active>true</active>
        <description>Health and Safety</description>
        <label>H&amp;S</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/QuestionnaireWelcomeController.cls
public without sharing class  QuestionnaireWelcomeController{

    public String UrlId  {get;set;}
    public List<Opportunity> HolidayQuesRec{get;set;}
    public List<SelectOption> charityLst{get;set;}
    //public Property__c objProperty {get;set;}
    public String userName {get;set;}
    public String visitDate {get;set;}
    public Questinnaire__c NewQuestionnaire {get;set;}
    public String verifyClientProperty{get;set;}
    public String oppAccName{get;set;}
    public String oppReferenceNo{get;set;}
    public String oppPropertyName{get;set;}
    public Date oppDepDate{get;set;}
    public String oppDepDate1 {get;set;}
    public Decimal oppCharityValue{get;set;}
    public String oppDestination{get;set;}
    public String propertyRegion {get;set;}
    public String auditByName {get;set;}
    
    public QuestionnaireWelcomeController(){
        UrlId  = APexpages.currentpage().getParameters().get('id');
        HolidayQuesRec = new List<Opportunity>();
        //objProperty = new Property__c() ;
        userName = userinfo.getname() ;
        NewQuestionnaire = new Questinnaire__c();
        visitDate = date.today().format();
        verifyClientProperty = '';
        oppDepDate1 = '' ;
        if(UrlId  != null){
        
            //if(UrlId.startsWithIgnoreCase('006')){
                verifyClientProperty = 'opp';
                HolidayQuesRec = [select id,Account.name,O_Reference_Number__c,O_Departure_Date__c,O_Charity__c,O_Destination__c from opportunity where id =: UrlId];
                Schema.DescribeFieldResult describeField = Opportunity.O_Charity__c.getDescribe();
                List<Schema.PicklistEntry> pickListValues = describeField.getPicklistValues();  
                charityLst = new List<SelectOption>();
                    
                for(Schema.PicklistEntry f : pickListValues){
                    charityLst.add(new selectOption(f.getLabel(),f.getValue()));
                }
                
                oppAccName = HolidayQuesRec[0].Account.name;
                oppReferenceNo = HolidayQuesRec[0].O_Reference_Number__c;
                //oppPropertyName = HolidayQuesRec[0].O_Property__c;
                oppDepDate =  HolidayQuesRec[0].O_Departure_Date__c;
                if(oppDepDate != null)
                    oppDepDate1 = oppDepDate.format();
                oppCharityValue =  HolidayQuesRec[0].O_Charity__c;
                oppDestination = HolidayQuesRec[0].O_Destination__c;
                propertyRegion = '';
                auditByName = '';
            //}
           /* else{
                verifyClientProperty = 'property';
                objProperty = [Select id,Name,P_Locality__r.Name,P_Region__c from Property__c  where id =: UrlId  ] ;
                auditByName = UserInfo.getName();
                propertyRegion = objProperty.P_Region__c;
                NewQuestionnaire.Q_Completed_Date__c = Date.today();
                NewQuestionnaire.Q_Date_of_visit__c = Date.today();
            }*/
        }
    }
    public pageReference BeginQuesionnaire(){
        //system.assert(false,'wwwwwwwwwwwwwwwwwwwwwww');
        if(UrlId  != null){
             recordtype rt;
             
             //if(UrlId.startsWithIgnoreCase('006')){
             
                rt = [select id from RecordType where sobjectType = :Utility.getNameSpacePrefix()+'Questinnaire__c' and developername = 'Client' limit 1];
                NewQuestionnaire = new Questinnaire__c(Q_Category_Checker__c = 1,Q_Booking__c = UrlId,Q_Date_of_visit__c = Date.today(),RecordTypeId =rt.id,Q_Stage__c = 'In Progress');
                
             /*}else{
                
                rt = [select id,name from RecordType where sobjectType = 'Questinnaire__c' and developername = 'H_S' limit 1];
                NewQuestionnaire = new Questinnaire__c(Q_Category_Checker__c = 1, Q_Audit_By__c=auditByName, Q_Completed_Date__c = NewQuestionnaire.Q_Completed_Date__c, Q_Property__c = UrlId,Q_Date_of_visit__c = NewQuestionnaire.Q_Date_of_visit__c ,RecordTypeId =rt.id,Q_Stage__c = 'In Progress',StatusNA__c='Green');
                
             }*/
             insert NewQuestionnaire;
             if(oppCharityValue != null && oppCharityValue != HolidayQuesRec[0].O_Charity__c){
                 HolidayQuesRec[0].O_Charity__c = oppCharityValue;
                 upsert HolidayQuesRec[0];
             }
             if(UrlId.startsWithIgnoreCase('006')){
                 pageReference pr = new pageReference('/apex/Client_Questionnaire?id='+UrlId);
                 return pr;
             }
            /* else{
                  pageReference pr = new pageReference('/apex/Client_Questionnaire?id='+UrlId+'&flag=New&RecId='+NewQuestionnaire.id);
                 return pr;
            
             }*/
         }
         return null;
    }
    public pageReference VerifyExisitingUser(){
        List<Questinnaire__c> ExistingQuestionnaire;
        if(UrlId.startsWithIgnoreCase('006')){
        
            ExistingQuestionnaire = [select id from Questinnaire__c where Q_Booking__c =:UrlId];
            
            if(ExistingQuestionnaire != null && ExistingQuestionnaire.size()>0) {
                return new pageReference('/apex/Client_Questionnaire?id='+UrlId);
            }
        } else{
            Boolean isCloned = APexpages.currentpage().getParameters().get('clone') != null ? true : false;
                
            if(!isCloned && APexpages.currentpage().getParameters().get('flag') == null){
                String RecordId = APexpages.currentpage().getParameters().get('RecId');
                return new pageReference('/apex/Client_Questionnaire?id='+UrlId+'&RecId='+RecordId);  
            }
        }
        return null;
        
    }
}