Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Adult__c</fullName>
        <inlineHelpText>Total no of adults in a given family.</inlineHelpText>
        <label>Adult</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Adult</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Choose an agent if this is an agent booking.</inlineHelpText>
        <label>Agency</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Booking_Currency__c</fullName>
        <label>Booking Currency</label>
        <picklist>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>O_Children__c</fullName>
        <label>Children</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Child</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Due_Date__c</fullName>
        <description>IF( O_Display_Due_Date__c&gt; 60 , O_Departure_Date__c - 90, O_Departure_Date__c - 60)</description>
        <formula>IF(  ISNULL(O_Display_Due_Date__c) , O_Departure_Date__c - 60, O_Departure_Date__c - O_Display_Due_Date__c)</formula>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Holiday_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Holiday Type</label>
        <referenceTo>Holiday_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Infant__c</fullName>
        <label>Infant</label>
        <summaryFilterItems>
            <field>Group_Member__c.GM_Occupancy_Type__c</field>
            <operation>equals</operation>
            <value>Infant</value>
        </summaryFilterItems>
        <summaryForeignKey>Group_Member__c.GM_Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>O_Itinerary_Cover_Name__c</fullName>
        <label>Itinerary Cover Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Itinerary_Display_Price__c</fullName>
        <inlineHelpText>Use this if you want to hide the Holiday Final Cost.</inlineHelpText>
        <label>Itinerary Display Price</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Margin__c</fullName>
        <label>Margin Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Outstanding__c</fullName>
        <formula>Amount - O_Total_Payment_Without_CC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Outstanding Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>O_Return_Date__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>O_Total_Payment__c</fullName>
        <label>Total Payment Received</label>
        <summarizedField>Client_Payment__c.CP_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Client_Payment__c.CP_Processed_On__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Client_Payment__c.CP_Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/SavePDF.cls
public Class SavePDF{
    
    String oppId;
    Opportunity opp;
    public SavePDF(Apexpages.standardcontroller controller){
        oppId = controller.getId();
        if (controller.getId() != null) {
            Opp = [select id, Name,O_Margin__c, Account.Name,Account.BillingStreet,Account.BillingCity,Account.BillingState,Account.BillingCountry,Account.BillingPostalCode,O_Agent__r.id,O_Agent__r.Name, O_Departure_Date__c, O_Return_Date__c,Owner.Name,Owner.Username,
                   O_Adult__c,O_Children__c,O_Infant__c,O_Holiday_Type__c,Amount,O_Outstanding__c,O_Booking_Currency__c,StageName,O_Itinerary_Cover_Name__c,O_Due_Date__c,
                   O_Itinerary_Display_Price__c,O_Total_Payment__c
                   from Opportunity 
            where Id=:oppId];
            
        }
    }
    
    //For save itinerary PDF page use only
    public void savePDF(){
        if(oppId != null){
            Pagereference PDFSS = new Pagereference('/apex/ItineraryPDFA4');
            PDFSS.getParameters().put('id',oppId);
            Attachment att = new Attachment();
            att.parentId = oppId;
            if(!Test.isRunningTest()){
                att.body = PDFSS.getContentAsPDF();
            }
            else{
                att.body = Blob.valueOf('Unit Test Attachment Body');
            }
            att.Name = Opp.name+'.pdf';
            insert att;
        }
    }
}