Sugati/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Charity__c</fullName>
        <label>Charity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_Departure_Date__c</fullName>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>O_Destination__c</fullName>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>O_Reference_Number__c</fullName>
        <label>Reference Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    
    
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Questinnaire__c.object
<CustomObject>
    <description>Client and HS Questionnaire</description>
    <fields>
        <fullName>Q_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Q_Category_Checker__c</fullName>
        <label>Category Checker</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Q_Date_of_visit__c</fullName>
        <description>This is for HS Questionnaire</description>
        <label>Date of visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Q_Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>Q-{0000000000}</displayFormat>
        <label>Questinnaire ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Client Questionnaire</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/QuestionnaireWelcomeControllerTest.cls
@isTest
public class QuestionnaireWelcomeControllerTest {
    public static testMethod void testBeginQuestionnaire(){
        try
        {
          string UrlId='006';
        
          List<Opportunity> HolidayQuesRec = new List<Opportunity>();
          HolidayQuesRec = [select id,Account.name,O_Reference_Number__c,O_Departure_Date__c,O_Charity__c,O_Destination__c from opportunity where id =: UrlId];
      recordtype rt = [select id from RecordType where sobjectType = :Utility.getNameSpacePrefix()+'Questinnaire__c' and developername = 'Client' limit 1];
          Questinnaire__c NewQuestionnaire = new Questinnaire__c(Q_Category_Checker__c =1, Q_Booking__c='', Q_Date_of_visit__c=Date.today(), RecordTypeId=rt.Id, Q_Stage__c='In Progress');
          insert NewQuestionnaire;
            system.Assert(NewQuestionnaire.Id!=null);
          HolidayQuesRec[0].O_Charity__c = 0.01;
          upsert HolidayQuesRec[0];
            system.Assert(HolidayQuesRec[0].Id!=null);
        }
        catch(Exception ex)
        {
            system.Assert(ex.getMessage()!=null);
        }
    }
    
    public static testMethod void testVerifyExistingUser(){
        try
        {
            List<Questinnaire__c> ExistingQuestionnaire;
            string UrlId='006';
            system.Assert(UrlId.startsWithIgnoreCase('006'));
            ExistingQuestionnaire = [select id from Questinnaire__c where Q_Booking__c =:UrlId];
            if(ExistingQuestionnaire==null){
                system.Assert(ExistingQuestionnaire==null);
            }else {
                if(ExistingQuestionnaire.size()>0){
                    system.Assert(ExistingQuestionnaire != null && ExistingQuestionnaire.size()>0);
                }
                
            }
            UrlId='004';
            Integer RetId=1;
            string returnstring ='';
            if(UrlId.startsWithIgnoreCase('006'))
            {
                system.Assert(RetId==1);
                returnstring = '/apex/Client_Questionnaire?id=';
            }
            else
            {
                system.Assert(RetId==1);
                returnstring = '/apex/Client_Questionnaire?id&recid';
            }
            
        }
        catch(Exception ex)
        {
            system.Assert(ex.getMessage()!=null);
        }
    }
}