Sugati/src/objects/Pro_UE__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Holiday_Suggestion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Holiday Suggestion</label>
        <type>Checkbox</type>
    </fields>
    <label>Pro User Edition</label>
</CustomObject>

Sugati/src/objects/Site__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Namespace__c</fullName>
        <label>Namespace</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
</CustomObject>

Sugati/src/classes/HolidaySuggestionController.cls
public class HolidaySuggestionController{

    public HolidaySuggestionController(ApexPages.StandardController controller){
        
    }
    
    public PageReference pageReferenceMethod() {
        
        if(Pro_UE__c.getInstance().Holiday_Suggestion__c){
            return null;
        }
        else{
            PageReference pageRef = new PageReference('/apex/'+Site__c.getInstance().Namespace__c+'NeedUpgrade');
            pageRef.setRedirect(true);
            return pageRef ;
        }
        
    }



}