Sugati/src/objects/Supplier__c.object
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <recordTypes>
        <fullName>DMC</fullName>
        <active>true</active>
        <label>DMC</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/objects/Supplier_Booking__c.object
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <fields>
        <fullName>SB_Where_to_go__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Where to go</label>
        <referenceTo>Where_to_go__c</referenceTo>
        <relationshipLabel>Supplier Booking</relationshipLabel>
        <relationshipName>Supplier_Booking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <recordTypes>
        <fullName>Description</fullName>
        <active>true</active>
        <label>Description</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Travelling_Country__c.object
<CustomObject>
    <fields>
        <fullName>TC_Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Travelling Countries</relationshipLabel>
        <relationshipName>Travelling_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sugati/src/objects/Where_to_go__c.object
<CustomObject>
    <description>Places / Cities</description>
    <label>Where to go</label>
    <nameField>
        <label>Where to go Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Where to go</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sugati/src/classes/DestinationMapControllerTest.cls
/**
*  @Author         :   Naval Sharma
*  @Date           :   1-Mar-2016
*  @Description    :   Test class for "DestinationMapController"
* 
**/
 
@isTest
public class  DestinationMapControllerTest {

    @testSetup
    static void setupTestData(){
        
        List<Opportunity> lstOpportunities = TestServices.createOpportunityRecords(1, null);
        List<Travelling_Country__c> travellingCountries = TestServices.createTravellingCountries(lstOpportunities[0].Id);
        List<Where_to_go__c> WTGRecords = TestServices.createWTGRecords(travellingCountries[0].TC_Country__c);
        List<Supplier__c> supplierRecords = TestServices.createSupplierRecords(travellingCountries[0].TC_Country__c);
        List<Supplier_Booking__c> supplierBookingRecords = TestServices.createSupplierBookings(supplierRecords[1].Id, lstOpportunities[0].Id);
        
        supplierBookingRecords[0].SB_Where_to_go__c = WTGRecords[0].Id;
        update supplierBookingRecords[0];
    }  
    
    /** Test methods to test functionality of DestinationMapController **/
    static testMethod void testMethod1(){
        
        Opportunity opp = [SELECT id FROM Opportunity Limit 1];
        ApexPages.standardController controller = new ApexPages.standardController(opp);
        DestinationMapController dmc = new DestinationMapController(controller);
        System.assertNotEquals(dmc.OppRec.Id, Null);
        dmc.getMapTravellingCountry();
        dmc.getASCIIMap();
        DestinationMapController defaultDMC = new DestinationMapController();
    }
    
}