Sugati/src/objects/Trigger_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Setting</label>
</CustomObject>

Sugati/src/objects/UserEdition__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Active User Edition</label>
</CustomObject>

Sugati/src/classes/Configurations.cls
public with sharing class Configurations{
    
    public static Trigger_Setting__c triggerSettings {
    
        get {return Trigger_Setting__c.getInstance();}
    }
    
    public static string BASIC = 'basic';
    public static string PRO = 'pro';
    public static UserEdition__c userEditions{
    
        get {return UserEdition__c.getInstance();}
    }
    
    public static boolean isBasic {
        get {
            if(userEditions.Version__c == BASIC) {
                return true;
            }
            return false;
        }
    }
}